set_property SRC_FILE_INFO {cfile:F:/FPGA/project/Vivado/Filter2D/image_process.srcs/constrs_1/new/xdc.xdc rfile:../../../image_process.srcs/constrs_1/new/xdc.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:2 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN G18 IOSTANDARD DIFF_SSTL15} [get_ports clk_n]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN H19 IOSTANDARD DIFF_SSTL15} [get_ports clk_p]
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AR13 IOSTANDARD LVCMOS18} [get_ports reset]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN AY19 IOSTANDARD LVCMOS18} [get_ports uart_rxd]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN BA19 IOSTANDARD LVCMOS18} [get_ports uart_txd]
