// Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
// --------------------------------------------------------------------------------
// Tool Version: Vivado v.2018.2 (win64) Build 2258646 Thu Jun 14 20:03:12 MDT 2018
// Date        : Fri Nov  9 15:13:15 2018
// Host        : DESKTOP-7JLTO9Q running 64-bit major release  (build 9200)
// Command     : write_verilog -force -mode synth_stub -rename_top design_1_riffa_controller_0_0 -prefix
//               design_1_riffa_controller_0_0_ design_1_riffa_controller_0_0_stub.v
// Design      : design_1_riffa_controller_0_0
// Purpose     : Stub declaration of top-level module interface
// Device      : xc7vx690tffg1761-3
// --------------------------------------------------------------------------------

// This empty module with port declaration file causes synthesis tools to infer a black box for IP.
// The synthesis directives are for Synopsys Synplify support to prevent IO buffer insertion.
// Please paste the declaration into a Verilog source file or add the file as an additional source.
(* X_CORE_INFO = "riffa_controller,Vivado 2018.2" *)
module design_1_riffa_controller_0_0(S_AXIS_CQ_TVALID, S_AXIS_CQ_TLAST, 
  S_AXIS_CQ_TDATA, S_AXIS_CQ_TKEEP, S_AXIS_CQ_TUSER, S_AXIS_CQ_TREADY, S_AXIS_RC_TVALID, 
  S_AXIS_RC_TLAST, S_AXIS_RC_TDATA, S_AXIS_RC_TKEEP, S_AXIS_RC_TUSER, S_AXIS_RC_TREADY, 
  M_AXIS_CC_TREADY, M_AXIS_CC_TVALID, M_AXIS_CC_TLAST, M_AXIS_CC_TDATA, M_AXIS_CC_TKEEP, 
  M_AXIS_CC_TUSER, M_AXIS_RQ_TREADY, M_AXIS_RQ_TVALID, M_AXIS_RQ_TLAST, M_AXIS_RQ_TDATA, 
  M_AXIS_RQ_TKEEP, M_AXIS_RQ_TUSER, USER_CLK, USER_RESET, CFG_INTERRUPT_INT, 
  CFG_INTERRUPT_PENDING, CFG_INTERRUPT_MSI_ENABLE, CFG_INTERRUPT_MSI_MASK_UPDATE, 
  CFG_INTERRUPT_MSI_DATA, CFG_INTERRUPT_MSI_SELECT, CFG_INTERRUPT_MSI_INT, 
  CFG_INTERRUPT_MSI_PENDING_STATUS, CFG_INTERRUPT_MSI_SENT, CFG_INTERRUPT_MSI_FAIL, 
  CFG_INTERRUPT_MSI_ATTR, CFG_INTERRUPT_MSI_TPH_PRESENT, CFG_INTERRUPT_MSI_TPH_TYPE, 
  CFG_INTERRUPT_MSI_TPH_ST_TAG, CFG_INTERRUPT_MSI_FUNCTION_NUMBER, CFG_FC_CPLH, 
  CFG_FC_CPLD, CFG_FC_SEL, CFG_NEGOTIATED_WIDTH, CFG_CURRENT_SPEED, CFG_MAX_PAYLOAD, 
  CFG_MAX_READ_REQ, CFG_FUNCTION_STATUS, CFG_RCB_STATUS, PCIE_CQ_NP_REQ, RST_OUT, 
  CHNL_TX_CLK, CHNL_TX, CHNL_TX_ACK, CHNL_TX_LAST, CHNL_TX_LEN, CHNL_TX_OFF, CHNL_TX_DATA, 
  CHNL_TX_DATA_VALID, CHNL_TX_DATA_REN, CHNL_RX_CLK, CHNL_RX, CHNL_RX_ACK, CHNL_RX_LAST, 
  CHNL_RX_LEN, CHNL_RX_OFF, CHNL_RX_DATA, CHNL_RX_DATA_VALID, CHNL_RX_DATA_REN)
/* synthesis syn_black_box black_box_pad_pin="S_AXIS_CQ_TVALID,S_AXIS_CQ_TLAST,S_AXIS_CQ_TDATA[127:0],S_AXIS_CQ_TKEEP[3:0],S_AXIS_CQ_TUSER[84:0],S_AXIS_CQ_TREADY,S_AXIS_RC_TVALID,S_AXIS_RC_TLAST,S_AXIS_RC_TDATA[127:0],S_AXIS_RC_TKEEP[3:0],S_AXIS_RC_TUSER[74:0],S_AXIS_RC_TREADY,M_AXIS_CC_TREADY,M_AXIS_CC_TVALID,M_AXIS_CC_TLAST,M_AXIS_CC_TDATA[127:0],M_AXIS_CC_TKEEP[3:0],M_AXIS_CC_TUSER[32:0],M_AXIS_RQ_TREADY,M_AXIS_RQ_TVALID,M_AXIS_RQ_TLAST,M_AXIS_RQ_TDATA[127:0],M_AXIS_RQ_TKEEP[3:0],M_AXIS_RQ_TUSER[59:0],USER_CLK,USER_RESET,CFG_INTERRUPT_INT[3:0],CFG_INTERRUPT_PENDING[1:0],CFG_INTERRUPT_MSI_ENABLE[1:0],CFG_INTERRUPT_MSI_MASK_UPDATE,CFG_INTERRUPT_MSI_DATA[31:0],CFG_INTERRUPT_MSI_SELECT[3:0],CFG_INTERRUPT_MSI_INT[31:0],CFG_INTERRUPT_MSI_PENDING_STATUS[63:0],CFG_INTERRUPT_MSI_SENT,CFG_INTERRUPT_MSI_FAIL,CFG_INTERRUPT_MSI_ATTR[2:0],CFG_INTERRUPT_MSI_TPH_PRESENT,CFG_INTERRUPT_MSI_TPH_TYPE[1:0],CFG_INTERRUPT_MSI_TPH_ST_TAG[8:0],CFG_INTERRUPT_MSI_FUNCTION_NUMBER[2:0],CFG_FC_CPLH[7:0],CFG_FC_CPLD[11:0],CFG_FC_SEL[2:0],CFG_NEGOTIATED_WIDTH[3:0],CFG_CURRENT_SPEED[2:0],CFG_MAX_PAYLOAD[2:0],CFG_MAX_READ_REQ[2:0],CFG_FUNCTION_STATUS[7:0],CFG_RCB_STATUS[1:0],PCIE_CQ_NP_REQ,RST_OUT,CHNL_TX_CLK[0:0],CHNL_TX[0:0],CHNL_TX_ACK[0:0],CHNL_TX_LAST[0:0],CHNL_TX_LEN[31:0],CHNL_TX_OFF[30:0],CHNL_TX_DATA[127:0],CHNL_TX_DATA_VALID[0:0],CHNL_TX_DATA_REN[0:0],CHNL_RX_CLK[0:0],CHNL_RX[0:0],CHNL_RX_ACK[0:0],CHNL_RX_LAST[0:0],CHNL_RX_LEN[31:0],CHNL_RX_OFF[30:0],CHNL_RX_DATA[127:0],CHNL_RX_DATA_VALID[0:0],CHNL_RX_DATA_REN[0:0]" */;
  input S_AXIS_CQ_TVALID;
  input S_AXIS_CQ_TLAST;
  input [127:0]S_AXIS_CQ_TDATA;
  input [3:0]S_AXIS_CQ_TKEEP;
  input [84:0]S_AXIS_CQ_TUSER;
  output S_AXIS_CQ_TREADY;
  input S_AXIS_RC_TVALID;
  input S_AXIS_RC_TLAST;
  input [127:0]S_AXIS_RC_TDATA;
  input [3:0]S_AXIS_RC_TKEEP;
  input [74:0]S_AXIS_RC_TUSER;
  output S_AXIS_RC_TREADY;
  input M_AXIS_CC_TREADY;
  output M_AXIS_CC_TVALID;
  output M_AXIS_CC_TLAST;
  output [127:0]M_AXIS_CC_TDATA;
  output [3:0]M_AXIS_CC_TKEEP;
  output [32:0]M_AXIS_CC_TUSER;
  input M_AXIS_RQ_TREADY;
  output M_AXIS_RQ_TVALID;
  output M_AXIS_RQ_TLAST;
  output [127:0]M_AXIS_RQ_TDATA;
  output [3:0]M_AXIS_RQ_TKEEP;
  output [59:0]M_AXIS_RQ_TUSER;
  input USER_CLK;
  input USER_RESET;
  output [3:0]CFG_INTERRUPT_INT;
  output [1:0]CFG_INTERRUPT_PENDING;
  input [1:0]CFG_INTERRUPT_MSI_ENABLE;
  input CFG_INTERRUPT_MSI_MASK_UPDATE;
  input [31:0]CFG_INTERRUPT_MSI_DATA;
  output [3:0]CFG_INTERRUPT_MSI_SELECT;
  output [31:0]CFG_INTERRUPT_MSI_INT;
  output [63:0]CFG_INTERRUPT_MSI_PENDING_STATUS;
  input CFG_INTERRUPT_MSI_SENT;
  input CFG_INTERRUPT_MSI_FAIL;
  output [2:0]CFG_INTERRUPT_MSI_ATTR;
  output CFG_INTERRUPT_MSI_TPH_PRESENT;
  output [1:0]CFG_INTERRUPT_MSI_TPH_TYPE;
  output [8:0]CFG_INTERRUPT_MSI_TPH_ST_TAG;
  output [2:0]CFG_INTERRUPT_MSI_FUNCTION_NUMBER;
  input [7:0]CFG_FC_CPLH;
  input [11:0]CFG_FC_CPLD;
  output [2:0]CFG_FC_SEL;
  input [3:0]CFG_NEGOTIATED_WIDTH;
  input [2:0]CFG_CURRENT_SPEED;
  input [2:0]CFG_MAX_PAYLOAD;
  input [2:0]CFG_MAX_READ_REQ;
  input [7:0]CFG_FUNCTION_STATUS;
  input [1:0]CFG_RCB_STATUS;
  output PCIE_CQ_NP_REQ;
  output RST_OUT;
  input [0:0]CHNL_TX_CLK;
  output [0:0]CHNL_TX;
  input [0:0]CHNL_TX_ACK;
  output [0:0]CHNL_TX_LAST;
  output [31:0]CHNL_TX_LEN;
  output [30:0]CHNL_TX_OFF;
  output [127:0]CHNL_TX_DATA;
  output [0:0]CHNL_TX_DATA_VALID;
  input [0:0]CHNL_TX_DATA_REN;
  input [0:0]CHNL_RX_CLK;
  input [0:0]CHNL_RX;
  output [0:0]CHNL_RX_ACK;
  input [0:0]CHNL_RX_LAST;
  input [31:0]CHNL_RX_LEN;
  input [30:0]CHNL_RX_OFF;
  input [127:0]CHNL_RX_DATA;
  input [0:0]CHNL_RX_DATA_VALID;
  output [0:0]CHNL_RX_DATA_REN;
endmodule
