// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module getGaussianKernel (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        sigmaX,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9,
        ap_return_10,
        ap_return_11,
        ap_return_12,
        ap_return_13,
        ap_return_14,
        ap_return_15,
        ap_return_16,
        ap_return_17,
        ap_return_18,
        ap_return_19,
        ap_return_20,
        ap_return_21,
        ap_return_22,
        ap_return_23,
        ap_return_24
);

parameter    ap_ST_fsm_state1 = 132'd1;
parameter    ap_ST_fsm_state2 = 132'd2;
parameter    ap_ST_fsm_state3 = 132'd4;
parameter    ap_ST_fsm_state4 = 132'd8;
parameter    ap_ST_fsm_state5 = 132'd16;
parameter    ap_ST_fsm_state6 = 132'd32;
parameter    ap_ST_fsm_state7 = 132'd64;
parameter    ap_ST_fsm_state8 = 132'd128;
parameter    ap_ST_fsm_state9 = 132'd256;
parameter    ap_ST_fsm_state10 = 132'd512;
parameter    ap_ST_fsm_state11 = 132'd1024;
parameter    ap_ST_fsm_state12 = 132'd2048;
parameter    ap_ST_fsm_state13 = 132'd4096;
parameter    ap_ST_fsm_state14 = 132'd8192;
parameter    ap_ST_fsm_state15 = 132'd16384;
parameter    ap_ST_fsm_state16 = 132'd32768;
parameter    ap_ST_fsm_state17 = 132'd65536;
parameter    ap_ST_fsm_state18 = 132'd131072;
parameter    ap_ST_fsm_state19 = 132'd262144;
parameter    ap_ST_fsm_state20 = 132'd524288;
parameter    ap_ST_fsm_state21 = 132'd1048576;
parameter    ap_ST_fsm_state22 = 132'd2097152;
parameter    ap_ST_fsm_state23 = 132'd4194304;
parameter    ap_ST_fsm_state24 = 132'd8388608;
parameter    ap_ST_fsm_state25 = 132'd16777216;
parameter    ap_ST_fsm_state26 = 132'd33554432;
parameter    ap_ST_fsm_state27 = 132'd67108864;
parameter    ap_ST_fsm_state28 = 132'd134217728;
parameter    ap_ST_fsm_state29 = 132'd268435456;
parameter    ap_ST_fsm_state30 = 132'd536870912;
parameter    ap_ST_fsm_state31 = 132'd1073741824;
parameter    ap_ST_fsm_state32 = 132'd2147483648;
parameter    ap_ST_fsm_state33 = 132'd4294967296;
parameter    ap_ST_fsm_state34 = 132'd8589934592;
parameter    ap_ST_fsm_state35 = 132'd17179869184;
parameter    ap_ST_fsm_state36 = 132'd34359738368;
parameter    ap_ST_fsm_state37 = 132'd68719476736;
parameter    ap_ST_fsm_state38 = 132'd137438953472;
parameter    ap_ST_fsm_state39 = 132'd274877906944;
parameter    ap_ST_fsm_state40 = 132'd549755813888;
parameter    ap_ST_fsm_state41 = 132'd1099511627776;
parameter    ap_ST_fsm_state42 = 132'd2199023255552;
parameter    ap_ST_fsm_state43 = 132'd4398046511104;
parameter    ap_ST_fsm_state44 = 132'd8796093022208;
parameter    ap_ST_fsm_state45 = 132'd17592186044416;
parameter    ap_ST_fsm_state46 = 132'd35184372088832;
parameter    ap_ST_fsm_state47 = 132'd70368744177664;
parameter    ap_ST_fsm_state48 = 132'd140737488355328;
parameter    ap_ST_fsm_state49 = 132'd281474976710656;
parameter    ap_ST_fsm_state50 = 132'd562949953421312;
parameter    ap_ST_fsm_state51 = 132'd1125899906842624;
parameter    ap_ST_fsm_state52 = 132'd2251799813685248;
parameter    ap_ST_fsm_state53 = 132'd4503599627370496;
parameter    ap_ST_fsm_state54 = 132'd9007199254740992;
parameter    ap_ST_fsm_state55 = 132'd18014398509481984;
parameter    ap_ST_fsm_state56 = 132'd36028797018963968;
parameter    ap_ST_fsm_state57 = 132'd72057594037927936;
parameter    ap_ST_fsm_state58 = 132'd144115188075855872;
parameter    ap_ST_fsm_state59 = 132'd288230376151711744;
parameter    ap_ST_fsm_state60 = 132'd576460752303423488;
parameter    ap_ST_fsm_state61 = 132'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 132'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 132'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 132'd9223372036854775808;
parameter    ap_ST_fsm_state65 = 132'd18446744073709551616;
parameter    ap_ST_fsm_state66 = 132'd36893488147419103232;
parameter    ap_ST_fsm_state67 = 132'd73786976294838206464;
parameter    ap_ST_fsm_state68 = 132'd147573952589676412928;
parameter    ap_ST_fsm_state69 = 132'd295147905179352825856;
parameter    ap_ST_fsm_state70 = 132'd590295810358705651712;
parameter    ap_ST_fsm_state71 = 132'd1180591620717411303424;
parameter    ap_ST_fsm_state72 = 132'd2361183241434822606848;
parameter    ap_ST_fsm_state73 = 132'd4722366482869645213696;
parameter    ap_ST_fsm_state74 = 132'd9444732965739290427392;
parameter    ap_ST_fsm_state75 = 132'd18889465931478580854784;
parameter    ap_ST_fsm_state76 = 132'd37778931862957161709568;
parameter    ap_ST_fsm_state77 = 132'd75557863725914323419136;
parameter    ap_ST_fsm_state78 = 132'd151115727451828646838272;
parameter    ap_ST_fsm_state79 = 132'd302231454903657293676544;
parameter    ap_ST_fsm_state80 = 132'd604462909807314587353088;
parameter    ap_ST_fsm_state81 = 132'd1208925819614629174706176;
parameter    ap_ST_fsm_state82 = 132'd2417851639229258349412352;
parameter    ap_ST_fsm_state83 = 132'd4835703278458516698824704;
parameter    ap_ST_fsm_state84 = 132'd9671406556917033397649408;
parameter    ap_ST_fsm_state85 = 132'd19342813113834066795298816;
parameter    ap_ST_fsm_state86 = 132'd38685626227668133590597632;
parameter    ap_ST_fsm_state87 = 132'd77371252455336267181195264;
parameter    ap_ST_fsm_state88 = 132'd154742504910672534362390528;
parameter    ap_ST_fsm_state89 = 132'd309485009821345068724781056;
parameter    ap_ST_fsm_state90 = 132'd618970019642690137449562112;
parameter    ap_ST_fsm_state91 = 132'd1237940039285380274899124224;
parameter    ap_ST_fsm_state92 = 132'd2475880078570760549798248448;
parameter    ap_ST_fsm_state93 = 132'd4951760157141521099596496896;
parameter    ap_ST_fsm_state94 = 132'd9903520314283042199192993792;
parameter    ap_ST_fsm_state95 = 132'd19807040628566084398385987584;
parameter    ap_ST_fsm_state96 = 132'd39614081257132168796771975168;
parameter    ap_ST_fsm_state97 = 132'd79228162514264337593543950336;
parameter    ap_ST_fsm_state98 = 132'd158456325028528675187087900672;
parameter    ap_ST_fsm_state99 = 132'd316912650057057350374175801344;
parameter    ap_ST_fsm_state100 = 132'd633825300114114700748351602688;
parameter    ap_ST_fsm_state101 = 132'd1267650600228229401496703205376;
parameter    ap_ST_fsm_state102 = 132'd2535301200456458802993406410752;
parameter    ap_ST_fsm_state103 = 132'd5070602400912917605986812821504;
parameter    ap_ST_fsm_state104 = 132'd10141204801825835211973625643008;
parameter    ap_ST_fsm_state105 = 132'd20282409603651670423947251286016;
parameter    ap_ST_fsm_state106 = 132'd40564819207303340847894502572032;
parameter    ap_ST_fsm_state107 = 132'd81129638414606681695789005144064;
parameter    ap_ST_fsm_state108 = 132'd162259276829213363391578010288128;
parameter    ap_ST_fsm_state109 = 132'd324518553658426726783156020576256;
parameter    ap_ST_fsm_state110 = 132'd649037107316853453566312041152512;
parameter    ap_ST_fsm_state111 = 132'd1298074214633706907132624082305024;
parameter    ap_ST_fsm_state112 = 132'd2596148429267413814265248164610048;
parameter    ap_ST_fsm_state113 = 132'd5192296858534827628530496329220096;
parameter    ap_ST_fsm_state114 = 132'd10384593717069655257060992658440192;
parameter    ap_ST_fsm_state115 = 132'd20769187434139310514121985316880384;
parameter    ap_ST_fsm_state116 = 132'd41538374868278621028243970633760768;
parameter    ap_ST_fsm_state117 = 132'd83076749736557242056487941267521536;
parameter    ap_ST_fsm_state118 = 132'd166153499473114484112975882535043072;
parameter    ap_ST_fsm_state119 = 132'd332306998946228968225951765070086144;
parameter    ap_ST_fsm_state120 = 132'd664613997892457936451903530140172288;
parameter    ap_ST_fsm_state121 = 132'd1329227995784915872903807060280344576;
parameter    ap_ST_fsm_state122 = 132'd2658455991569831745807614120560689152;
parameter    ap_ST_fsm_state123 = 132'd5316911983139663491615228241121378304;
parameter    ap_ST_fsm_state124 = 132'd10633823966279326983230456482242756608;
parameter    ap_ST_fsm_state125 = 132'd21267647932558653966460912964485513216;
parameter    ap_ST_fsm_state126 = 132'd42535295865117307932921825928971026432;
parameter    ap_ST_fsm_state127 = 132'd85070591730234615865843651857942052864;
parameter    ap_ST_fsm_state128 = 132'd170141183460469231731687303715884105728;
parameter    ap_ST_fsm_state129 = 132'd340282366920938463463374607431768211456;
parameter    ap_ST_fsm_state130 = 132'd680564733841876926926749214863536422912;
parameter    ap_ST_fsm_state131 = 132'd1361129467683753853853498429727072845824;
parameter    ap_ST_fsm_state132 = 132'd2722258935367507707706996859454145691648;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] sigmaX;
output  [31:0] ap_return_0;
output  [31:0] ap_return_1;
output  [31:0] ap_return_2;
output  [31:0] ap_return_3;
output  [31:0] ap_return_4;
output  [31:0] ap_return_5;
output  [31:0] ap_return_6;
output  [31:0] ap_return_7;
output  [31:0] ap_return_8;
output  [31:0] ap_return_9;
output  [31:0] ap_return_10;
output  [31:0] ap_return_11;
output  [31:0] ap_return_12;
output  [31:0] ap_return_13;
output  [31:0] ap_return_14;
output  [31:0] ap_return_15;
output  [31:0] ap_return_16;
output  [31:0] ap_return_17;
output  [31:0] ap_return_18;
output  [31:0] ap_return_19;
output  [31:0] ap_return_20;
output  [31:0] ap_return_21;
output  [31:0] ap_return_22;
output  [31:0] ap_return_23;
output  [31:0] ap_return_24;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [131:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] grp_fu_95_p2;
reg   [31:0] reg_156;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state130;
wire   [31:0] grp_fu_120_p2;
reg   [31:0] reg_163;
wire    ap_CS_fsm_state12;
wire    ap_CS_fsm_state128;
wire   [31:0] grp_fu_90_p2;
reg   [31:0] reg_175;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state20;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state41;
wire    ap_CS_fsm_state45;
wire    ap_CS_fsm_state49;
wire    ap_CS_fsm_state53;
wire    ap_CS_fsm_state57;
wire    ap_CS_fsm_state61;
wire    ap_CS_fsm_state65;
wire    ap_CS_fsm_state69;
wire    ap_CS_fsm_state73;
wire    ap_CS_fsm_state77;
wire    ap_CS_fsm_state81;
wire    ap_CS_fsm_state85;
wire    ap_CS_fsm_state89;
wire    ap_CS_fsm_state93;
wire    ap_CS_fsm_state97;
wire    ap_CS_fsm_state101;
wire    ap_CS_fsm_state105;
wire    ap_CS_fsm_state109;
wire    ap_CS_fsm_state113;
wire    ap_CS_fsm_state117;
wire    ap_CS_fsm_state121;
reg   [31:0] reg_181;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state64;
wire   [31:0] sigmaX_assign_fu_227_p3;
reg   [31:0] sigmaX_assign_reg_2536;
reg   [31:0] temp2_0_1_reg_2542;
wire   [31:0] x_assign_fu_245_p1;
wire    ap_CS_fsm_state17;
reg   [31:0] temp2_0_2_reg_2553;
wire   [31:0] grp_fu_151_p2;
reg   [31:0] kval_0_0_reg_2559;
wire    ap_CS_fsm_state21;
wire   [31:0] x_assign_1_fu_260_p1;
reg   [31:0] kval_0_1_reg_2571;
wire   [31:0] x_assign_2_fu_275_p1;
reg   [31:0] kval_0_2_reg_2582;
wire   [31:0] x_assign_3_fu_290_p1;
reg   [31:0] kval_1_1_reg_2593;
wire   [31:0] x_assign_4_fu_305_p1;
reg   [31:0] kval_1_2_reg_2604;
wire   [31:0] x_assign_5_fu_320_p1;
reg   [31:0] kval_2_2_reg_2615;
wire   [31:0] grp_fu_100_p2;
reg   [31:0] v_assign_0_1_reg_2621;
wire   [31:0] grp_fu_104_p2;
reg   [31:0] v_assign_0_2_reg_2626;
wire   [31:0] grp_fu_108_p2;
reg   [31:0] v_assign_1_1_reg_2631;
wire   [31:0] grp_fu_112_p2;
reg   [31:0] v_assign_1_2_reg_2636;
wire   [31:0] grp_fu_116_p2;
reg   [31:0] v_assign_2_2_reg_2641;
reg   [0:0] tmp_21_reg_2646;
wire    ap_CS_fsm_state131;
wire   [51:0] tmp_24_fu_355_p1;
reg   [51:0] tmp_24_reg_2654;
wire   [0:0] tmp_14_fu_359_p2;
reg   [0:0] tmp_14_reg_2659;
wire   [11:0] F2_fu_365_p2;
reg   [11:0] F2_reg_2665;
wire   [0:0] tmp_15_fu_371_p2;
reg   [0:0] tmp_15_reg_2673;
wire  signed [11:0] sh_amt_fu_389_p3;
reg  signed [11:0] sh_amt_reg_2679;
wire   [0:0] icmp_fu_407_p2;
reg   [0:0] icmp_reg_2685;
wire   [0:0] tmp_26_fu_413_p2;
reg   [0:0] tmp_26_reg_2690;
wire   [5:0] tmp_37_fu_419_p1;
reg   [5:0] tmp_37_reg_2695;
reg   [0:0] tmp_43_reg_2700;
wire   [51:0] tmp_44_fu_453_p1;
reg   [51:0] tmp_44_reg_2708;
wire   [0:0] tmp_22_0_1_fu_457_p2;
reg   [0:0] tmp_22_0_1_reg_2713;
wire   [11:0] F2_0_1_fu_463_p2;
reg   [11:0] F2_0_1_reg_2719;
wire   [0:0] tmp_24_0_1_fu_469_p2;
reg   [0:0] tmp_24_0_1_reg_2727;
wire  signed [11:0] sh_amt_0_1_fu_487_p3;
reg  signed [11:0] sh_amt_0_1_reg_2733;
wire   [0:0] icmp4_fu_505_p2;
reg   [0:0] icmp4_reg_2739;
wire   [0:0] tmp_36_0_1_fu_511_p2;
reg   [0:0] tmp_36_0_1_reg_2744;
wire   [5:0] tmp_49_fu_517_p1;
reg   [5:0] tmp_49_reg_2749;
reg   [0:0] tmp_55_reg_2754;
wire   [51:0] tmp_56_fu_551_p1;
reg   [51:0] tmp_56_reg_2762;
wire   [0:0] tmp_22_0_2_fu_555_p2;
reg   [0:0] tmp_22_0_2_reg_2767;
wire   [11:0] F2_0_2_fu_561_p2;
reg   [11:0] F2_0_2_reg_2773;
wire   [0:0] tmp_24_0_2_fu_567_p2;
reg   [0:0] tmp_24_0_2_reg_2781;
wire  signed [11:0] sh_amt_0_2_fu_585_p3;
reg  signed [11:0] sh_amt_0_2_reg_2787;
wire   [0:0] icmp7_fu_603_p2;
reg   [0:0] icmp7_reg_2793;
wire   [0:0] tmp_36_0_2_fu_609_p2;
reg   [0:0] tmp_36_0_2_reg_2798;
wire   [5:0] tmp_61_fu_615_p1;
reg   [5:0] tmp_61_reg_2803;
reg   [0:0] tmp_67_reg_2808;
wire   [51:0] tmp_68_fu_649_p1;
reg   [51:0] tmp_68_reg_2816;
wire   [0:0] tmp_22_1_1_fu_653_p2;
reg   [0:0] tmp_22_1_1_reg_2821;
wire   [11:0] F2_1_1_fu_659_p2;
reg   [11:0] F2_1_1_reg_2827;
wire   [0:0] tmp_24_1_1_fu_665_p2;
reg   [0:0] tmp_24_1_1_reg_2835;
wire  signed [11:0] sh_amt_1_1_fu_683_p3;
reg  signed [11:0] sh_amt_1_1_reg_2841;
wire   [0:0] icmp1_fu_701_p2;
reg   [0:0] icmp1_reg_2847;
wire   [0:0] tmp_36_1_1_fu_707_p2;
reg   [0:0] tmp_36_1_1_reg_2852;
wire   [5:0] tmp_73_fu_713_p1;
reg   [5:0] tmp_73_reg_2857;
reg   [0:0] tmp_79_reg_2862;
wire   [51:0] tmp_80_fu_747_p1;
reg   [51:0] tmp_80_reg_2870;
wire   [0:0] tmp_22_1_2_fu_751_p2;
reg   [0:0] tmp_22_1_2_reg_2875;
wire   [11:0] F2_1_2_fu_757_p2;
reg   [11:0] F2_1_2_reg_2881;
wire   [0:0] tmp_24_1_2_fu_763_p2;
reg   [0:0] tmp_24_1_2_reg_2889;
wire  signed [11:0] sh_amt_1_2_fu_781_p3;
reg  signed [11:0] sh_amt_1_2_reg_2895;
wire   [0:0] icmp2_fu_799_p2;
reg   [0:0] icmp2_reg_2901;
wire   [0:0] tmp_36_1_2_fu_805_p2;
reg   [0:0] tmp_36_1_2_reg_2906;
wire   [5:0] tmp_85_fu_811_p1;
reg   [5:0] tmp_85_reg_2911;
reg   [0:0] tmp_91_reg_2916;
wire   [51:0] tmp_92_fu_845_p1;
reg   [51:0] tmp_92_reg_2924;
wire   [0:0] tmp_22_2_2_fu_849_p2;
reg   [0:0] tmp_22_2_2_reg_2929;
wire   [11:0] F2_2_2_fu_855_p2;
reg   [11:0] F2_2_2_reg_2935;
wire   [5:0] tmp_97_fu_861_p1;
reg   [5:0] tmp_97_reg_2946;
reg   [31:0] grp_fu_90_p0;
reg   [31:0] grp_fu_90_p1;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state38;
wire    ap_CS_fsm_state42;
wire    ap_CS_fsm_state46;
wire    ap_CS_fsm_state50;
wire    ap_CS_fsm_state54;
wire    ap_CS_fsm_state58;
wire    ap_CS_fsm_state62;
wire    ap_CS_fsm_state66;
wire    ap_CS_fsm_state70;
wire    ap_CS_fsm_state74;
wire    ap_CS_fsm_state78;
wire    ap_CS_fsm_state82;
wire    ap_CS_fsm_state86;
wire    ap_CS_fsm_state90;
wire    ap_CS_fsm_state94;
wire    ap_CS_fsm_state98;
wire    ap_CS_fsm_state102;
wire    ap_CS_fsm_state106;
wire    ap_CS_fsm_state110;
wire    ap_CS_fsm_state114;
wire    ap_CS_fsm_state118;
reg   [31:0] grp_fu_95_p0;
reg   [31:0] grp_fu_95_p1;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state129;
reg   [31:0] grp_fu_120_p0;
reg   [31:0] grp_fu_120_p1;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state14;
wire    ap_CS_fsm_state122;
reg   [31:0] grp_fu_151_p1;
wire   [31:0] sigmaX_to_int_fu_185_p1;
wire   [7:0] tmp_fu_189_p4;
wire   [22:0] tmp_9_fu_199_p1;
wire   [0:0] notrhs_fu_209_p2;
wire   [0:0] notlhs_fu_203_p2;
wire   [0:0] tmp_10_fu_215_p2;
wire   [0:0] tmp_11_fu_145_p2;
wire   [0:0] tmp_12_fu_221_p2;
wire   [31:0] temp_to_int_fu_235_p1;
wire   [31:0] temp_neg_fu_239_p2;
wire   [31:0] temp_to_int_0_1_fu_250_p1;
wire   [31:0] temp_neg_0_1_fu_254_p2;
wire   [31:0] temp_to_int_0_2_fu_265_p1;
wire   [31:0] temp_neg_0_2_fu_269_p2;
wire   [31:0] temp_to_int_1_1_fu_280_p1;
wire   [31:0] temp_neg_1_1_fu_284_p2;
wire   [31:0] temp_to_int_1_2_fu_295_p1;
wire   [31:0] temp_neg_1_2_fu_299_p2;
wire   [31:0] temp_to_int_2_2_fu_310_p1;
wire   [31:0] temp_neg_2_2_fu_314_p2;
wire   [63:0] d_assign_fu_127_p1;
wire   [63:0] ireg_V_fu_325_p1;
wire   [10:0] p_Result_1_fu_341_p4;
wire   [62:0] tmp_19_fu_329_p1;
wire   [11:0] tmp_13_fu_351_p1;
wire   [11:0] tmp_16_fu_377_p2;
wire   [11:0] tmp_17_fu_383_p2;
wire   [6:0] tmp_32_fu_397_p4;
wire   [63:0] d_assign_0_1_fu_130_p1;
wire   [63:0] ireg_V_0_1_fu_423_p1;
wire   [10:0] p_Result_1_0_1_fu_439_p4;
wire   [62:0] tmp_42_fu_427_p1;
wire   [11:0] tmp_20_0_1_fu_449_p1;
wire   [11:0] tmp_25_0_1_fu_475_p2;
wire   [11:0] tmp_26_0_1_fu_481_p2;
wire   [6:0] tmp_46_fu_495_p4;
wire   [63:0] d_assign_0_2_fu_133_p1;
wire   [63:0] ireg_V_0_2_fu_521_p1;
wire   [10:0] p_Result_1_0_2_fu_537_p4;
wire   [62:0] tmp_54_fu_525_p1;
wire   [11:0] tmp_20_0_2_fu_547_p1;
wire   [11:0] tmp_25_0_2_fu_573_p2;
wire   [11:0] tmp_26_0_2_fu_579_p2;
wire   [6:0] tmp_58_fu_593_p4;
wire   [63:0] d_assign_1_1_fu_136_p1;
wire   [63:0] ireg_V_1_1_fu_619_p1;
wire   [10:0] p_Result_1_1_1_fu_635_p4;
wire   [62:0] tmp_66_fu_623_p1;
wire   [11:0] tmp_20_1_1_fu_645_p1;
wire   [11:0] tmp_25_1_1_fu_671_p2;
wire   [11:0] tmp_26_1_1_fu_677_p2;
wire   [6:0] tmp_70_fu_691_p4;
wire   [63:0] d_assign_1_2_fu_139_p1;
wire   [63:0] ireg_V_1_2_fu_717_p1;
wire   [10:0] p_Result_1_1_2_fu_733_p4;
wire   [62:0] tmp_78_fu_721_p1;
wire   [11:0] tmp_20_1_2_fu_743_p1;
wire   [11:0] tmp_25_1_2_fu_769_p2;
wire   [11:0] tmp_26_1_2_fu_775_p2;
wire   [6:0] tmp_82_fu_789_p4;
wire   [63:0] d_assign_2_2_fu_142_p1;
wire   [63:0] ireg_V_2_2_fu_815_p1;
wire   [10:0] p_Result_1_2_2_fu_831_p4;
wire   [62:0] tmp_90_fu_819_p1;
wire   [11:0] tmp_20_2_2_fu_841_p1;
wire    ap_CS_fsm_state132;
wire   [52:0] tmp_1_fu_865_p3;
wire   [53:0] p_Result_7_fu_872_p1;
wire   [53:0] man_V_1_fu_876_p2;
wire   [53:0] man_V_4_fu_882_p3;
wire  signed [31:0] sh_amt_0_cast_fu_889_p1;
wire   [53:0] tmp_22_fu_906_p1;
wire   [53:0] tmp_23_fu_910_p2;
wire   [31:0] tmp_29_fu_897_p1;
wire   [0:0] tmp_20_fu_901_p2;
wire   [31:0] tmp_35_fu_916_p1;
wire   [31:0] storemerge_fu_920_p3;
wire   [11:0] tmp_27_fu_941_p2;
wire   [31:0] tmp_37_0_cast_fu_946_p1;
wire   [0:0] tmp_36_fu_950_p3;
wire   [11:0] tmp_30_fu_969_p2;
wire   [0:0] tmp_31_fu_974_p2;
wire   [5:0] tmp_41_0_cast_op_fu_980_p2;
wire   [5:0] tmp_38_fu_985_p3;
wire   [53:0] tmp_39_fu_993_p1;
wire   [53:0] tmp_40_fu_997_p2;
wire   [53:0] tmp_41_fu_1003_p2;
wire   [0:0] tmp_28_fu_964_p2;
wire   [0:0] tmp_33_fu_1009_p2;
wire   [0:0] r_fu_1015_p2;
wire   [0:0] p_r_i_i_i_fu_1021_p2;
wire   [0:0] qb_fu_958_p3;
wire   [0:0] qb_assign_1_fu_1026_p2;
wire   [31:0] tmp_34_fu_1032_p1;
wire   [31:0] p_Val2_3_fu_933_p3;
wire   [0:0] tmp_18_fu_892_p2;
wire   [0:0] sel_tmp1_fu_1042_p2;
wire   [0:0] sel_tmp2_fu_1047_p2;
wire   [0:0] sel_tmp6_demorgan_fu_1061_p2;
wire   [0:0] sel_tmp6_fu_1066_p2;
wire   [0:0] sel_tmp7_fu_1072_p2;
wire   [31:0] p_Val2_4_fu_1036_p2;
wire   [31:0] sel_tmp3_fu_1053_p3;
wire   [0:0] sel_tmp13_demorgan_fu_1085_p2;
wire   [0:0] sel_tmp_fu_1090_p2;
wire   [0:0] sel_tmp4_fu_1096_p2;
wire   [31:0] tmp_25_fu_927_p2;
wire   [31:0] sel_tmp8_fu_1077_p3;
wire   [52:0] tmp_4_fu_1109_p3;
wire   [53:0] p_Result_7_0_1_fu_1116_p1;
wire   [53:0] man_V_1_0_1_fu_1120_p2;
wire   [53:0] man_V_4_0_1_fu_1126_p3;
wire  signed [31:0] sh_amt_0_1_cast_fu_1133_p1;
wire   [53:0] tmp_32_0_1_fu_1150_p1;
wire   [53:0] tmp_33_0_1_fu_1154_p2;
wire   [31:0] tmp_45_fu_1141_p1;
wire   [0:0] tmp_29_0_1_fu_1145_p2;
wire   [31:0] tmp_47_fu_1160_p1;
wire   [31:0] storemerge_0_1_fu_1164_p3;
wire   [11:0] tmp_37_0_1_fu_1185_p2;
wire   [31:0] tmp_37_0_1_cast_fu_1190_p1;
wire   [0:0] tmp_48_fu_1194_p3;
wire   [11:0] tmp_41_0_1_fu_1213_p2;
wire   [0:0] tmp_42_0_1_fu_1218_p2;
wire   [5:0] tmp_41_0_1_cast_op_fu_1224_p2;
wire   [5:0] tmp_50_fu_1229_p3;
wire   [53:0] tmp_51_fu_1237_p1;
wire   [53:0] tmp_52_fu_1241_p2;
wire   [53:0] tmp_53_fu_1247_p2;
wire   [0:0] tmp_40_0_1_fu_1208_p2;
wire   [0:0] tmp_44_0_1_fu_1253_p2;
wire   [0:0] r_0_1_fu_1259_p2;
wire   [0:0] p_r_i_i_i_0_1_fu_1265_p2;
wire   [0:0] qb_0_1_fu_1202_p3;
wire   [0:0] qb_assign_1_0_1_fu_1270_p2;
wire   [31:0] tmp_46_0_1_fu_1276_p1;
wire   [31:0] p_Val2_3_0_1_fu_1177_p3;
wire   [0:0] tmp_27_0_1_fu_1136_p2;
wire   [0:0] sel_tmp5_fu_1286_p2;
wire   [0:0] sel_tmp9_fu_1291_p2;
wire   [0:0] sel_tmp25_demorgan_fu_1305_p2;
wire   [0:0] sel_tmp11_fu_1310_p2;
wire   [0:0] sel_tmp12_fu_1316_p2;
wire   [31:0] p_Val2_4_0_1_fu_1280_p2;
wire   [31:0] sel_tmp10_fu_1297_p3;
wire   [0:0] sel_tmp32_demorgan_fu_1329_p2;
wire   [0:0] sel_tmp14_fu_1334_p2;
wire   [0:0] sel_tmp15_fu_1340_p2;
wire   [31:0] tmp_35_0_1_fu_1171_p2;
wire   [31:0] sel_tmp13_fu_1321_p3;
wire   [52:0] tmp_5_fu_1353_p3;
wire   [53:0] p_Result_7_0_2_fu_1360_p1;
wire   [53:0] man_V_1_0_2_fu_1364_p2;
wire   [53:0] man_V_4_0_2_fu_1370_p3;
wire  signed [31:0] sh_amt_0_2_cast_fu_1377_p1;
wire   [53:0] tmp_32_0_2_fu_1394_p1;
wire   [53:0] tmp_33_0_2_fu_1398_p2;
wire   [31:0] tmp_57_fu_1385_p1;
wire   [0:0] tmp_29_0_2_fu_1389_p2;
wire   [31:0] tmp_59_fu_1404_p1;
wire   [31:0] storemerge_0_2_fu_1408_p3;
wire   [11:0] tmp_37_0_2_fu_1429_p2;
wire   [31:0] tmp_37_0_2_cast_fu_1434_p1;
wire   [0:0] tmp_60_fu_1438_p3;
wire   [11:0] tmp_41_0_2_fu_1457_p2;
wire   [0:0] tmp_42_0_2_fu_1462_p2;
wire   [5:0] tmp_41_0_2_cast_op_fu_1468_p2;
wire   [5:0] tmp_62_fu_1473_p3;
wire   [53:0] tmp_63_fu_1481_p1;
wire   [53:0] tmp_64_fu_1485_p2;
wire   [53:0] tmp_65_fu_1491_p2;
wire   [0:0] tmp_40_0_2_fu_1452_p2;
wire   [0:0] tmp_44_0_2_fu_1497_p2;
wire   [0:0] r_0_2_fu_1503_p2;
wire   [0:0] p_r_i_i_i_0_2_fu_1509_p2;
wire   [0:0] qb_0_2_fu_1446_p3;
wire   [0:0] qb_assign_1_0_2_fu_1514_p2;
wire   [31:0] tmp_46_0_2_fu_1520_p1;
wire   [31:0] p_Val2_3_0_2_fu_1421_p3;
wire   [0:0] tmp_27_0_2_fu_1380_p2;
wire   [0:0] sel_tmp16_fu_1530_p2;
wire   [0:0] sel_tmp17_fu_1535_p2;
wire   [0:0] sel_tmp44_demorgan_fu_1549_p2;
wire   [0:0] sel_tmp19_fu_1554_p2;
wire   [0:0] sel_tmp20_fu_1560_p2;
wire   [31:0] p_Val2_4_0_2_fu_1524_p2;
wire   [31:0] sel_tmp18_fu_1541_p3;
wire   [0:0] sel_tmp51_demorgan_fu_1573_p2;
wire   [0:0] sel_tmp22_fu_1578_p2;
wire   [0:0] sel_tmp23_fu_1584_p2;
wire   [31:0] tmp_35_0_2_fu_1415_p2;
wire   [31:0] sel_tmp21_fu_1565_p3;
wire   [52:0] tmp_6_fu_1597_p3;
wire   [53:0] p_Result_7_1_1_fu_1604_p1;
wire   [53:0] man_V_1_1_1_fu_1608_p2;
wire   [53:0] man_V_4_1_1_fu_1614_p3;
wire  signed [31:0] sh_amt_1_1_cast_fu_1621_p1;
wire   [53:0] tmp_32_1_1_fu_1638_p1;
wire   [53:0] tmp_33_1_1_fu_1642_p2;
wire   [31:0] tmp_69_fu_1629_p1;
wire   [0:0] tmp_29_1_1_fu_1633_p2;
wire   [31:0] tmp_71_fu_1648_p1;
wire   [31:0] storemerge_1_1_fu_1652_p3;
wire   [11:0] tmp_37_1_1_fu_1673_p2;
wire   [31:0] tmp_37_1_1_cast_fu_1678_p1;
wire   [0:0] tmp_72_fu_1682_p3;
wire   [11:0] tmp_41_1_1_fu_1701_p2;
wire   [0:0] tmp_42_1_1_fu_1706_p2;
wire   [5:0] tmp_41_1_1_cast_op_fu_1712_p2;
wire   [5:0] tmp_74_fu_1717_p3;
wire   [53:0] tmp_75_fu_1725_p1;
wire   [53:0] tmp_76_fu_1729_p2;
wire   [53:0] tmp_77_fu_1735_p2;
wire   [0:0] tmp_40_1_1_fu_1696_p2;
wire   [0:0] tmp_44_1_1_fu_1741_p2;
wire   [0:0] r_1_1_fu_1747_p2;
wire   [0:0] p_r_i_i_i_1_1_fu_1753_p2;
wire   [0:0] qb_1_1_fu_1690_p3;
wire   [0:0] qb_assign_1_1_1_fu_1758_p2;
wire   [31:0] tmp_46_1_1_fu_1764_p1;
wire   [31:0] p_Val2_3_1_1_fu_1665_p3;
wire   [0:0] tmp_27_1_1_fu_1624_p2;
wire   [0:0] sel_tmp24_fu_1774_p2;
wire   [0:0] sel_tmp25_fu_1779_p2;
wire   [0:0] sel_tmp120_demorgan_fu_1793_p2;
wire   [0:0] sel_tmp27_fu_1798_p2;
wire   [0:0] sel_tmp28_fu_1804_p2;
wire   [31:0] p_Val2_4_1_1_fu_1768_p2;
wire   [31:0] sel_tmp26_fu_1785_p3;
wire   [0:0] sel_tmp127_demorgan_fu_1817_p2;
wire   [0:0] sel_tmp30_fu_1822_p2;
wire   [0:0] sel_tmp31_fu_1828_p2;
wire   [31:0] tmp_35_1_1_fu_1659_p2;
wire   [31:0] sel_tmp29_fu_1809_p3;
wire   [52:0] tmp_7_fu_1841_p3;
wire   [53:0] p_Result_7_1_2_fu_1848_p1;
wire   [53:0] man_V_1_1_2_fu_1852_p2;
wire   [53:0] man_V_4_1_2_fu_1858_p3;
wire  signed [31:0] sh_amt_1_2_cast_fu_1865_p1;
wire   [53:0] tmp_32_1_2_fu_1882_p1;
wire   [53:0] tmp_33_1_2_fu_1886_p2;
wire   [31:0] tmp_81_fu_1873_p1;
wire   [0:0] tmp_29_1_2_fu_1877_p2;
wire   [31:0] tmp_83_fu_1892_p1;
wire   [31:0] storemerge_1_2_fu_1896_p3;
wire   [11:0] tmp_37_1_2_fu_1917_p2;
wire   [31:0] tmp_37_1_2_cast_fu_1922_p1;
wire   [0:0] tmp_84_fu_1926_p3;
wire   [11:0] tmp_41_1_2_fu_1945_p2;
wire   [0:0] tmp_42_1_2_fu_1950_p2;
wire   [5:0] tmp_41_1_2_cast_op_fu_1956_p2;
wire   [5:0] tmp_86_fu_1961_p3;
wire   [53:0] tmp_87_fu_1969_p1;
wire   [53:0] tmp_88_fu_1973_p2;
wire   [53:0] tmp_89_fu_1979_p2;
wire   [0:0] tmp_40_1_2_fu_1940_p2;
wire   [0:0] tmp_44_1_2_fu_1985_p2;
wire   [0:0] r_1_2_fu_1991_p2;
wire   [0:0] p_r_i_i_i_1_2_fu_1997_p2;
wire   [0:0] qb_1_2_fu_1934_p3;
wire   [0:0] qb_assign_1_1_2_fu_2002_p2;
wire   [31:0] tmp_46_1_2_fu_2008_p1;
wire   [31:0] p_Val2_3_1_2_fu_1909_p3;
wire   [0:0] tmp_27_1_2_fu_1868_p2;
wire   [0:0] sel_tmp32_fu_2018_p2;
wire   [0:0] sel_tmp33_fu_2023_p2;
wire   [0:0] sel_tmp139_demorgan_fu_2037_p2;
wire   [0:0] sel_tmp35_fu_2042_p2;
wire   [0:0] sel_tmp36_fu_2048_p2;
wire   [31:0] p_Val2_4_1_2_fu_2012_p2;
wire   [31:0] sel_tmp34_fu_2029_p3;
wire   [0:0] sel_tmp146_demorgan_fu_2061_p2;
wire   [0:0] sel_tmp38_fu_2066_p2;
wire   [0:0] sel_tmp39_fu_2072_p2;
wire   [31:0] tmp_35_1_2_fu_1903_p2;
wire   [31:0] sel_tmp37_fu_2053_p3;
wire   [52:0] tmp_8_fu_2085_p3;
wire   [53:0] p_Result_7_2_2_fu_2092_p1;
wire   [53:0] man_V_1_2_2_fu_2096_p2;
wire   [0:0] tmp_24_2_2_fu_2109_p2;
wire   [11:0] tmp_25_2_2_fu_2114_p2;
wire   [11:0] tmp_26_2_2_fu_2119_p2;
wire  signed [11:0] sh_amt_2_2_fu_2124_p3;
wire   [53:0] man_V_4_2_2_fu_2102_p3;
wire   [6:0] tmp_94_fu_2151_p4;
wire  signed [31:0] sh_amt_2_2_cast_fu_2132_p1;
wire   [53:0] tmp_32_2_2_fu_2167_p1;
wire   [53:0] tmp_33_2_2_fu_2171_p2;
wire   [31:0] tmp_93_fu_2141_p1;
wire   [0:0] tmp_29_2_2_fu_2145_p2;
wire   [31:0] tmp_95_fu_2177_p1;
wire   [31:0] storemerge_2_2_fu_2181_p3;
wire   [11:0] tmp_37_2_2_fu_2208_p2;
wire   [31:0] tmp_37_2_2_cast_fu_2213_p1;
wire   [0:0] tmp_36_2_2_fu_2202_p2;
wire   [0:0] tmp_96_fu_2217_p3;
wire   [11:0] tmp_41_2_2_fu_2237_p2;
wire   [0:0] tmp_42_2_2_fu_2242_p2;
wire   [5:0] tmp_41_2_2_cast_op_fu_2248_p2;
wire   [5:0] tmp_98_fu_2253_p3;
wire   [53:0] tmp_99_fu_2261_p1;
wire   [53:0] tmp_100_fu_2265_p2;
wire   [53:0] tmp_101_fu_2271_p2;
wire   [0:0] tmp_40_2_2_fu_2232_p2;
wire   [0:0] tmp_44_2_2_fu_2277_p2;
wire   [0:0] r_2_2_fu_2283_p2;
wire   [0:0] p_r_i_i_i_2_2_fu_2289_p2;
wire   [0:0] qb_2_2_fu_2225_p3;
wire   [0:0] qb_assign_1_2_2_fu_2294_p2;
wire   [31:0] tmp_46_2_2_fu_2300_p1;
wire   [31:0] p_Val2_3_2_2_fu_2194_p3;
wire   [0:0] tmp_27_2_2_fu_2136_p2;
wire   [0:0] sel_tmp40_fu_2310_p2;
wire   [0:0] sel_tmp234_demorgan_fu_2321_p2;
wire   [0:0] sel_tmp42_fu_2326_p2;
wire   [0:0] sel_tmp241_demorgan_fu_2338_p2;
wire   [0:0] icmp3_fu_2161_p2;
wire   [0:0] sel_tmp44_fu_2344_p2;
wire   [0:0] sel_tmp45_fu_2350_p2;
wire   [31:0] tmp_35_2_2_fu_2188_p2;
wire   [31:0] p_Val2_4_2_2_fu_2304_p2;
wire   [0:0] sel_tmp43_fu_2332_p2;
wire   [0:0] sel_tmp41_fu_2315_p2;
wire   [0:0] or_cond_fu_2364_p2;
wire   [31:0] newSel_fu_2356_p3;
wire   [31:0] newSel1_fu_2370_p3;
wire   [31:0] kernel_val_0_V_0_w_fu_1101_p3;
wire   [31:0] kernel_val_0_V_1_w_fu_1345_p3;
wire   [31:0] kernel_val_0_V_2_w_fu_1589_p3;
wire   [31:0] kernel_val_1_V_1_w_fu_1833_p3;
wire   [31:0] kernel_val_1_V_2_w_fu_2077_p3;
wire   [31:0] kernel_val_2_V_2_w_fu_2378_p3;
reg   [131:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 132'd1;
end

Filter2D_Core_fadbkb #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fadbkb_U27(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_90_p0),
    .din1(grp_fu_90_p1),
    .ce(1'b1),
    .dout(grp_fu_90_p2)
);

Filter2D_Core_fmucud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fmucud_U28(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_95_p0),
    .din1(grp_fu_95_p1),
    .ce(1'b1),
    .dout(grp_fu_95_p2)
);

Filter2D_Core_fmucud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fmucud_U29(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kval_0_1_reg_2571),
    .din1(reg_163),
    .ce(1'b1),
    .dout(grp_fu_100_p2)
);

Filter2D_Core_fmucud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fmucud_U30(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kval_0_2_reg_2582),
    .din1(reg_163),
    .ce(1'b1),
    .dout(grp_fu_104_p2)
);

Filter2D_Core_fmucud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fmucud_U31(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kval_1_1_reg_2593),
    .din1(reg_163),
    .ce(1'b1),
    .dout(grp_fu_108_p2)
);

Filter2D_Core_fmucud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fmucud_U32(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kval_1_2_reg_2604),
    .din1(reg_163),
    .ce(1'b1),
    .dout(grp_fu_112_p2)
);

Filter2D_Core_fmucud #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fmucud_U33(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(kval_2_2_reg_2615),
    .din1(reg_163),
    .ce(1'b1),
    .dout(grp_fu_116_p2)
);

Filter2D_Core_fdidEe #(
    .ID( 1 ),
    .NUM_STAGE( 7 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fdidEe_U34(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_120_p0),
    .din1(grp_fu_120_p1),
    .ce(1'b1),
    .dout(grp_fu_120_p2)
);

Filter2D_Core_fpeeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
Filter2D_Core_fpeeOg_U35(
    .din0(reg_156),
    .dout(d_assign_fu_127_p1)
);

Filter2D_Core_fpeeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
Filter2D_Core_fpeeOg_U36(
    .din0(v_assign_0_1_reg_2621),
    .dout(d_assign_0_1_fu_130_p1)
);

Filter2D_Core_fpeeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
Filter2D_Core_fpeeOg_U37(
    .din0(v_assign_0_2_reg_2626),
    .dout(d_assign_0_2_fu_133_p1)
);

Filter2D_Core_fpeeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
Filter2D_Core_fpeeOg_U38(
    .din0(v_assign_1_1_reg_2631),
    .dout(d_assign_1_1_fu_136_p1)
);

Filter2D_Core_fpeeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
Filter2D_Core_fpeeOg_U39(
    .din0(v_assign_1_2_reg_2636),
    .dout(d_assign_1_2_fu_139_p1)
);

Filter2D_Core_fpeeOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
Filter2D_Core_fpeeOg_U40(
    .din0(v_assign_2_2_reg_2641),
    .dout(d_assign_2_2_fu_142_p1)
);

Filter2D_Core_fcmfYi #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
Filter2D_Core_fcmfYi_U41(
    .din0(sigmaX),
    .din1(32'd0),
    .opcode(5'd5),
    .dout(tmp_11_fu_145_p2)
);

Filter2D_Core_fexg8j #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
Filter2D_Core_fexg8j_U42(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd0),
    .din1(grp_fu_151_p1),
    .ce(1'b1),
    .dout(grp_fu_151_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state131)) begin
        F2_0_1_reg_2719 <= F2_0_1_fu_463_p2;
        F2_0_2_reg_2773 <= F2_0_2_fu_561_p2;
        F2_1_1_reg_2827 <= F2_1_1_fu_659_p2;
        F2_1_2_reg_2881 <= F2_1_2_fu_757_p2;
        F2_2_2_reg_2935 <= F2_2_2_fu_855_p2;
        F2_reg_2665 <= F2_fu_365_p2;
        icmp1_reg_2847 <= icmp1_fu_701_p2;
        icmp2_reg_2901 <= icmp2_fu_799_p2;
        icmp4_reg_2739 <= icmp4_fu_505_p2;
        icmp7_reg_2793 <= icmp7_fu_603_p2;
        icmp_reg_2685 <= icmp_fu_407_p2;
        sh_amt_0_1_reg_2733 <= sh_amt_0_1_fu_487_p3;
        sh_amt_0_2_reg_2787 <= sh_amt_0_2_fu_585_p3;
        sh_amt_1_1_reg_2841 <= sh_amt_1_1_fu_683_p3;
        sh_amt_1_2_reg_2895 <= sh_amt_1_2_fu_781_p3;
        sh_amt_reg_2679 <= sh_amt_fu_389_p3;
        tmp_14_reg_2659 <= tmp_14_fu_359_p2;
        tmp_15_reg_2673 <= tmp_15_fu_371_p2;
        tmp_21_reg_2646 <= ireg_V_fu_325_p1[32'd63];
        tmp_22_0_1_reg_2713 <= tmp_22_0_1_fu_457_p2;
        tmp_22_0_2_reg_2767 <= tmp_22_0_2_fu_555_p2;
        tmp_22_1_1_reg_2821 <= tmp_22_1_1_fu_653_p2;
        tmp_22_1_2_reg_2875 <= tmp_22_1_2_fu_751_p2;
        tmp_22_2_2_reg_2929 <= tmp_22_2_2_fu_849_p2;
        tmp_24_0_1_reg_2727 <= tmp_24_0_1_fu_469_p2;
        tmp_24_0_2_reg_2781 <= tmp_24_0_2_fu_567_p2;
        tmp_24_1_1_reg_2835 <= tmp_24_1_1_fu_665_p2;
        tmp_24_1_2_reg_2889 <= tmp_24_1_2_fu_763_p2;
        tmp_24_reg_2654 <= tmp_24_fu_355_p1;
        tmp_26_reg_2690 <= tmp_26_fu_413_p2;
        tmp_36_0_1_reg_2744 <= tmp_36_0_1_fu_511_p2;
        tmp_36_0_2_reg_2798 <= tmp_36_0_2_fu_609_p2;
        tmp_36_1_1_reg_2852 <= tmp_36_1_1_fu_707_p2;
        tmp_36_1_2_reg_2906 <= tmp_36_1_2_fu_805_p2;
        tmp_37_reg_2695 <= tmp_37_fu_419_p1;
        tmp_43_reg_2700 <= ireg_V_0_1_fu_423_p1[32'd63];
        tmp_44_reg_2708 <= tmp_44_fu_453_p1;
        tmp_49_reg_2749 <= tmp_49_fu_517_p1;
        tmp_55_reg_2754 <= ireg_V_0_2_fu_521_p1[32'd63];
        tmp_56_reg_2762 <= tmp_56_fu_551_p1;
        tmp_61_reg_2803 <= tmp_61_fu_615_p1;
        tmp_67_reg_2808 <= ireg_V_1_1_fu_619_p1[32'd63];
        tmp_68_reg_2816 <= tmp_68_fu_649_p1;
        tmp_73_reg_2857 <= tmp_73_fu_713_p1;
        tmp_79_reg_2862 <= ireg_V_1_2_fu_717_p1[32'd63];
        tmp_80_reg_2870 <= tmp_80_fu_747_p1;
        tmp_85_reg_2911 <= tmp_85_fu_811_p1;
        tmp_91_reg_2916 <= ireg_V_2_2_fu_815_p1[32'd63];
        tmp_92_reg_2924 <= tmp_92_fu_845_p1;
        tmp_97_reg_2946 <= tmp_97_fu_861_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state21)) begin
        kval_0_0_reg_2559 <= grp_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        kval_0_1_reg_2571 <= grp_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        kval_0_2_reg_2582 <= grp_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        kval_1_1_reg_2593 <= grp_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        kval_1_2_reg_2604 <= grp_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state69)) begin
        kval_2_2_reg_2615 <= grp_fu_151_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state130) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state3))) begin
        reg_156 <= grp_fu_95_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state128) | (1'b1 == ap_CS_fsm_state12))) begin
        reg_163 <= grp_fu_120_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state121) | (1'b1 == ap_CS_fsm_state117) | (1'b1 == ap_CS_fsm_state113) | (1'b1 == ap_CS_fsm_state109) | (1'b1 == ap_CS_fsm_state105) | (1'b1 == ap_CS_fsm_state101) | (1'b1 == ap_CS_fsm_state97) | (1'b1 == ap_CS_fsm_state93) | (1'b1 == ap_CS_fsm_state89) | (1'b1 == ap_CS_fsm_state85) | (1'b1 == ap_CS_fsm_state81) | (1'b1 == ap_CS_fsm_state77) | (1'b1 == ap_CS_fsm_state73) | (1'b1 == ap_CS_fsm_state69) | (1'b1 == ap_CS_fsm_state65) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state16))) begin
        reg_175 <= grp_fu_90_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state40))) begin
        reg_181 <= grp_fu_90_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        sigmaX_assign_reg_2536 <= sigmaX_assign_fu_227_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state16)) begin
        temp2_0_1_reg_2542 <= grp_fu_120_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        temp2_0_2_reg_2553 <= grp_fu_120_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state130)) begin
        v_assign_0_1_reg_2621 <= grp_fu_100_p2;
        v_assign_0_2_reg_2626 <= grp_fu_104_p2;
        v_assign_1_1_reg_2631 <= grp_fu_108_p2;
        v_assign_1_2_reg_2636 <= grp_fu_112_p2;
        v_assign_2_2_reg_2641 <= grp_fu_116_p2;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state132) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state132)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_fu_120_p0 = 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state122) | (1'b1 == ap_CS_fsm_state10))) begin
        grp_fu_120_p0 = 32'd1065353216;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_fu_120_p0 = 32'd1082130432;
    end else begin
        grp_fu_120_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state122)) begin
        grp_fu_120_p1 = reg_175;
    end else if (((1'b1 == ap_CS_fsm_state14) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state6))) begin
        grp_fu_120_p1 = reg_156;
    end else begin
        grp_fu_120_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state65)) begin
        grp_fu_151_p1 = x_assign_5_fu_320_p1;
    end else if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_151_p1 = x_assign_4_fu_305_p1;
    end else if ((1'b1 == ap_CS_fsm_state41)) begin
        grp_fu_151_p1 = x_assign_3_fu_290_p1;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_151_p1 = x_assign_2_fu_275_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_151_p1 = x_assign_1_fu_260_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_151_p1 = x_assign_fu_245_p1;
    end else begin
        grp_fu_151_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state61)) begin
        grp_fu_90_p0 = temp2_0_2_reg_2553;
    end else if (((1'b1 == ap_CS_fsm_state41) | (1'b1 == ap_CS_fsm_state37))) begin
        grp_fu_90_p0 = temp2_0_1_reg_2542;
    end else if (((1'b1 == ap_CS_fsm_state118) | (1'b1 == ap_CS_fsm_state114) | (1'b1 == ap_CS_fsm_state110) | (1'b1 == ap_CS_fsm_state106) | (1'b1 == ap_CS_fsm_state102) | (1'b1 == ap_CS_fsm_state98) | (1'b1 == ap_CS_fsm_state94) | (1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state70) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state26))) begin
        grp_fu_90_p0 = reg_175;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_90_p0 = kval_0_0_reg_2559;
    end else if (((1'b1 == ap_CS_fsm_state13) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state17))) begin
        grp_fu_90_p0 = reg_163;
    end else begin
        grp_fu_90_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state70)) begin
        grp_fu_90_p1 = kval_2_2_reg_2615;
    end else if (((1'b1 == ap_CS_fsm_state90) | (1'b1 == ap_CS_fsm_state74) | (1'b1 == ap_CS_fsm_state66) | (1'b1 == ap_CS_fsm_state50))) begin
        grp_fu_90_p1 = kval_1_2_reg_2604;
    end else if (((1'b1 == ap_CS_fsm_state94) | (1'b1 == ap_CS_fsm_state86) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state46))) begin
        grp_fu_90_p1 = kval_1_1_reg_2593;
    end else if (((1'b1 == ap_CS_fsm_state118) | (1'b1 == ap_CS_fsm_state102) | (1'b1 == ap_CS_fsm_state38))) begin
        grp_fu_90_p1 = kval_0_0_reg_2559;
    end else if (((1'b1 == ap_CS_fsm_state110) | (1'b1 == ap_CS_fsm_state78) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state30))) begin
        grp_fu_90_p1 = kval_0_2_reg_2582;
    end else if (((1'b1 == ap_CS_fsm_state114) | (1'b1 == ap_CS_fsm_state106) | (1'b1 == ap_CS_fsm_state98) | (1'b1 == ap_CS_fsm_state82) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state26))) begin
        grp_fu_90_p1 = kval_0_1_reg_2571;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_90_p1 = 32'd0;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state41))) begin
        grp_fu_90_p1 = temp2_0_2_reg_2553;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state37))) begin
        grp_fu_90_p1 = temp2_0_1_reg_2542;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_fu_90_p1 = reg_163;
    end else begin
        grp_fu_90_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        grp_fu_95_p0 = kval_0_0_reg_2559;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_95_p0 = reg_156;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_95_p0 = sigmaX_assign_reg_2536;
    end else begin
        grp_fu_95_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state129)) begin
        grp_fu_95_p1 = reg_163;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        grp_fu_95_p1 = sigmaX_assign_reg_2536;
    end else if ((1'b1 == ap_CS_fsm_state2)) begin
        grp_fu_95_p1 = 32'd1073741824;
    end else begin
        grp_fu_95_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            ap_NS_fsm = ap_ST_fsm_state55;
        end
        ap_ST_fsm_state55 : begin
            ap_NS_fsm = ap_ST_fsm_state56;
        end
        ap_ST_fsm_state56 : begin
            ap_NS_fsm = ap_ST_fsm_state57;
        end
        ap_ST_fsm_state57 : begin
            ap_NS_fsm = ap_ST_fsm_state58;
        end
        ap_ST_fsm_state58 : begin
            ap_NS_fsm = ap_ST_fsm_state59;
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state60;
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            ap_NS_fsm = ap_ST_fsm_state65;
        end
        ap_ST_fsm_state65 : begin
            ap_NS_fsm = ap_ST_fsm_state66;
        end
        ap_ST_fsm_state66 : begin
            ap_NS_fsm = ap_ST_fsm_state67;
        end
        ap_ST_fsm_state67 : begin
            ap_NS_fsm = ap_ST_fsm_state68;
        end
        ap_ST_fsm_state68 : begin
            ap_NS_fsm = ap_ST_fsm_state69;
        end
        ap_ST_fsm_state69 : begin
            ap_NS_fsm = ap_ST_fsm_state70;
        end
        ap_ST_fsm_state70 : begin
            ap_NS_fsm = ap_ST_fsm_state71;
        end
        ap_ST_fsm_state71 : begin
            ap_NS_fsm = ap_ST_fsm_state72;
        end
        ap_ST_fsm_state72 : begin
            ap_NS_fsm = ap_ST_fsm_state73;
        end
        ap_ST_fsm_state73 : begin
            ap_NS_fsm = ap_ST_fsm_state74;
        end
        ap_ST_fsm_state74 : begin
            ap_NS_fsm = ap_ST_fsm_state75;
        end
        ap_ST_fsm_state75 : begin
            ap_NS_fsm = ap_ST_fsm_state76;
        end
        ap_ST_fsm_state76 : begin
            ap_NS_fsm = ap_ST_fsm_state77;
        end
        ap_ST_fsm_state77 : begin
            ap_NS_fsm = ap_ST_fsm_state78;
        end
        ap_ST_fsm_state78 : begin
            ap_NS_fsm = ap_ST_fsm_state79;
        end
        ap_ST_fsm_state79 : begin
            ap_NS_fsm = ap_ST_fsm_state80;
        end
        ap_ST_fsm_state80 : begin
            ap_NS_fsm = ap_ST_fsm_state81;
        end
        ap_ST_fsm_state81 : begin
            ap_NS_fsm = ap_ST_fsm_state82;
        end
        ap_ST_fsm_state82 : begin
            ap_NS_fsm = ap_ST_fsm_state83;
        end
        ap_ST_fsm_state83 : begin
            ap_NS_fsm = ap_ST_fsm_state84;
        end
        ap_ST_fsm_state84 : begin
            ap_NS_fsm = ap_ST_fsm_state85;
        end
        ap_ST_fsm_state85 : begin
            ap_NS_fsm = ap_ST_fsm_state86;
        end
        ap_ST_fsm_state86 : begin
            ap_NS_fsm = ap_ST_fsm_state87;
        end
        ap_ST_fsm_state87 : begin
            ap_NS_fsm = ap_ST_fsm_state88;
        end
        ap_ST_fsm_state88 : begin
            ap_NS_fsm = ap_ST_fsm_state89;
        end
        ap_ST_fsm_state89 : begin
            ap_NS_fsm = ap_ST_fsm_state90;
        end
        ap_ST_fsm_state90 : begin
            ap_NS_fsm = ap_ST_fsm_state91;
        end
        ap_ST_fsm_state91 : begin
            ap_NS_fsm = ap_ST_fsm_state92;
        end
        ap_ST_fsm_state92 : begin
            ap_NS_fsm = ap_ST_fsm_state93;
        end
        ap_ST_fsm_state93 : begin
            ap_NS_fsm = ap_ST_fsm_state94;
        end
        ap_ST_fsm_state94 : begin
            ap_NS_fsm = ap_ST_fsm_state95;
        end
        ap_ST_fsm_state95 : begin
            ap_NS_fsm = ap_ST_fsm_state96;
        end
        ap_ST_fsm_state96 : begin
            ap_NS_fsm = ap_ST_fsm_state97;
        end
        ap_ST_fsm_state97 : begin
            ap_NS_fsm = ap_ST_fsm_state98;
        end
        ap_ST_fsm_state98 : begin
            ap_NS_fsm = ap_ST_fsm_state99;
        end
        ap_ST_fsm_state99 : begin
            ap_NS_fsm = ap_ST_fsm_state100;
        end
        ap_ST_fsm_state100 : begin
            ap_NS_fsm = ap_ST_fsm_state101;
        end
        ap_ST_fsm_state101 : begin
            ap_NS_fsm = ap_ST_fsm_state102;
        end
        ap_ST_fsm_state102 : begin
            ap_NS_fsm = ap_ST_fsm_state103;
        end
        ap_ST_fsm_state103 : begin
            ap_NS_fsm = ap_ST_fsm_state104;
        end
        ap_ST_fsm_state104 : begin
            ap_NS_fsm = ap_ST_fsm_state105;
        end
        ap_ST_fsm_state105 : begin
            ap_NS_fsm = ap_ST_fsm_state106;
        end
        ap_ST_fsm_state106 : begin
            ap_NS_fsm = ap_ST_fsm_state107;
        end
        ap_ST_fsm_state107 : begin
            ap_NS_fsm = ap_ST_fsm_state108;
        end
        ap_ST_fsm_state108 : begin
            ap_NS_fsm = ap_ST_fsm_state109;
        end
        ap_ST_fsm_state109 : begin
            ap_NS_fsm = ap_ST_fsm_state110;
        end
        ap_ST_fsm_state110 : begin
            ap_NS_fsm = ap_ST_fsm_state111;
        end
        ap_ST_fsm_state111 : begin
            ap_NS_fsm = ap_ST_fsm_state112;
        end
        ap_ST_fsm_state112 : begin
            ap_NS_fsm = ap_ST_fsm_state113;
        end
        ap_ST_fsm_state113 : begin
            ap_NS_fsm = ap_ST_fsm_state114;
        end
        ap_ST_fsm_state114 : begin
            ap_NS_fsm = ap_ST_fsm_state115;
        end
        ap_ST_fsm_state115 : begin
            ap_NS_fsm = ap_ST_fsm_state116;
        end
        ap_ST_fsm_state116 : begin
            ap_NS_fsm = ap_ST_fsm_state117;
        end
        ap_ST_fsm_state117 : begin
            ap_NS_fsm = ap_ST_fsm_state118;
        end
        ap_ST_fsm_state118 : begin
            ap_NS_fsm = ap_ST_fsm_state119;
        end
        ap_ST_fsm_state119 : begin
            ap_NS_fsm = ap_ST_fsm_state120;
        end
        ap_ST_fsm_state120 : begin
            ap_NS_fsm = ap_ST_fsm_state121;
        end
        ap_ST_fsm_state121 : begin
            ap_NS_fsm = ap_ST_fsm_state122;
        end
        ap_ST_fsm_state122 : begin
            ap_NS_fsm = ap_ST_fsm_state123;
        end
        ap_ST_fsm_state123 : begin
            ap_NS_fsm = ap_ST_fsm_state124;
        end
        ap_ST_fsm_state124 : begin
            ap_NS_fsm = ap_ST_fsm_state125;
        end
        ap_ST_fsm_state125 : begin
            ap_NS_fsm = ap_ST_fsm_state126;
        end
        ap_ST_fsm_state126 : begin
            ap_NS_fsm = ap_ST_fsm_state127;
        end
        ap_ST_fsm_state127 : begin
            ap_NS_fsm = ap_ST_fsm_state128;
        end
        ap_ST_fsm_state128 : begin
            ap_NS_fsm = ap_ST_fsm_state129;
        end
        ap_ST_fsm_state129 : begin
            ap_NS_fsm = ap_ST_fsm_state130;
        end
        ap_ST_fsm_state130 : begin
            ap_NS_fsm = ap_ST_fsm_state131;
        end
        ap_ST_fsm_state131 : begin
            ap_NS_fsm = ap_ST_fsm_state132;
        end
        ap_ST_fsm_state132 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_0_1_fu_463_p2 = (12'd1075 - tmp_20_0_1_fu_449_p1);

assign F2_0_2_fu_561_p2 = (12'd1075 - tmp_20_0_2_fu_547_p1);

assign F2_1_1_fu_659_p2 = (12'd1075 - tmp_20_1_1_fu_645_p1);

assign F2_1_2_fu_757_p2 = (12'd1075 - tmp_20_1_2_fu_743_p1);

assign F2_2_2_fu_855_p2 = (12'd1075 - tmp_20_2_2_fu_841_p1);

assign F2_fu_365_p2 = (12'd1075 - tmp_13_fu_351_p1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state101 = ap_CS_fsm[32'd100];

assign ap_CS_fsm_state102 = ap_CS_fsm[32'd101];

assign ap_CS_fsm_state105 = ap_CS_fsm[32'd104];

assign ap_CS_fsm_state106 = ap_CS_fsm[32'd105];

assign ap_CS_fsm_state109 = ap_CS_fsm[32'd108];

assign ap_CS_fsm_state110 = ap_CS_fsm[32'd109];

assign ap_CS_fsm_state113 = ap_CS_fsm[32'd112];

assign ap_CS_fsm_state114 = ap_CS_fsm[32'd113];

assign ap_CS_fsm_state117 = ap_CS_fsm[32'd116];

assign ap_CS_fsm_state118 = ap_CS_fsm[32'd117];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state121 = ap_CS_fsm[32'd120];

assign ap_CS_fsm_state122 = ap_CS_fsm[32'd121];

assign ap_CS_fsm_state128 = ap_CS_fsm[32'd127];

assign ap_CS_fsm_state129 = ap_CS_fsm[32'd128];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state130 = ap_CS_fsm[32'd129];

assign ap_CS_fsm_state131 = ap_CS_fsm[32'd130];

assign ap_CS_fsm_state132 = ap_CS_fsm[32'd131];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state41 = ap_CS_fsm[32'd40];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd41];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state65 = ap_CS_fsm[32'd64];

assign ap_CS_fsm_state66 = ap_CS_fsm[32'd65];

assign ap_CS_fsm_state69 = ap_CS_fsm[32'd68];

assign ap_CS_fsm_state70 = ap_CS_fsm[32'd69];

assign ap_CS_fsm_state73 = ap_CS_fsm[32'd72];

assign ap_CS_fsm_state74 = ap_CS_fsm[32'd73];

assign ap_CS_fsm_state77 = ap_CS_fsm[32'd76];

assign ap_CS_fsm_state78 = ap_CS_fsm[32'd77];

assign ap_CS_fsm_state81 = ap_CS_fsm[32'd80];

assign ap_CS_fsm_state82 = ap_CS_fsm[32'd81];

assign ap_CS_fsm_state85 = ap_CS_fsm[32'd84];

assign ap_CS_fsm_state86 = ap_CS_fsm[32'd85];

assign ap_CS_fsm_state89 = ap_CS_fsm[32'd88];

assign ap_CS_fsm_state90 = ap_CS_fsm[32'd89];

assign ap_CS_fsm_state93 = ap_CS_fsm[32'd92];

assign ap_CS_fsm_state94 = ap_CS_fsm[32'd93];

assign ap_CS_fsm_state97 = ap_CS_fsm[32'd96];

assign ap_CS_fsm_state98 = ap_CS_fsm[32'd97];

assign ap_return_0 = kernel_val_0_V_0_w_fu_1101_p3;

assign ap_return_1 = kernel_val_0_V_1_w_fu_1345_p3;

assign ap_return_10 = kernel_val_0_V_2_w_fu_1589_p3;

assign ap_return_11 = kernel_val_1_V_2_w_fu_2077_p3;

assign ap_return_12 = kernel_val_2_V_2_w_fu_2378_p3;

assign ap_return_13 = kernel_val_1_V_2_w_fu_2077_p3;

assign ap_return_14 = kernel_val_0_V_2_w_fu_1589_p3;

assign ap_return_15 = kernel_val_0_V_1_w_fu_1345_p3;

assign ap_return_16 = kernel_val_1_V_1_w_fu_1833_p3;

assign ap_return_17 = kernel_val_1_V_2_w_fu_2077_p3;

assign ap_return_18 = kernel_val_1_V_1_w_fu_1833_p3;

assign ap_return_19 = kernel_val_0_V_1_w_fu_1345_p3;

assign ap_return_2 = kernel_val_0_V_2_w_fu_1589_p3;

assign ap_return_20 = kernel_val_0_V_0_w_fu_1101_p3;

assign ap_return_21 = kernel_val_0_V_1_w_fu_1345_p3;

assign ap_return_22 = kernel_val_0_V_2_w_fu_1589_p3;

assign ap_return_23 = kernel_val_0_V_1_w_fu_1345_p3;

assign ap_return_24 = kernel_val_0_V_0_w_fu_1101_p3;

assign ap_return_3 = kernel_val_0_V_1_w_fu_1345_p3;

assign ap_return_4 = kernel_val_0_V_0_w_fu_1101_p3;

assign ap_return_5 = kernel_val_0_V_1_w_fu_1345_p3;

assign ap_return_6 = kernel_val_1_V_1_w_fu_1833_p3;

assign ap_return_7 = kernel_val_1_V_2_w_fu_2077_p3;

assign ap_return_8 = kernel_val_1_V_1_w_fu_1833_p3;

assign ap_return_9 = kernel_val_0_V_1_w_fu_1345_p3;

assign icmp1_fu_701_p2 = ((tmp_70_fu_691_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp2_fu_799_p2 = ((tmp_82_fu_789_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp3_fu_2161_p2 = ((tmp_94_fu_2151_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp4_fu_505_p2 = ((tmp_46_fu_495_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp7_fu_603_p2 = ((tmp_58_fu_593_p4 == 7'd0) ? 1'b1 : 1'b0);

assign icmp_fu_407_p2 = ((tmp_32_fu_397_p4 == 7'd0) ? 1'b1 : 1'b0);

assign ireg_V_0_1_fu_423_p1 = d_assign_0_1_fu_130_p1;

assign ireg_V_0_2_fu_521_p1 = d_assign_0_2_fu_133_p1;

assign ireg_V_1_1_fu_619_p1 = d_assign_1_1_fu_136_p1;

assign ireg_V_1_2_fu_717_p1 = d_assign_1_2_fu_139_p1;

assign ireg_V_2_2_fu_815_p1 = d_assign_2_2_fu_142_p1;

assign ireg_V_fu_325_p1 = d_assign_fu_127_p1;

assign kernel_val_0_V_0_w_fu_1101_p3 = ((sel_tmp4_fu_1096_p2[0:0] === 1'b1) ? tmp_25_fu_927_p2 : sel_tmp8_fu_1077_p3);

assign kernel_val_0_V_1_w_fu_1345_p3 = ((sel_tmp15_fu_1340_p2[0:0] === 1'b1) ? tmp_35_0_1_fu_1171_p2 : sel_tmp13_fu_1321_p3);

assign kernel_val_0_V_2_w_fu_1589_p3 = ((sel_tmp23_fu_1584_p2[0:0] === 1'b1) ? tmp_35_0_2_fu_1415_p2 : sel_tmp21_fu_1565_p3);

assign kernel_val_1_V_1_w_fu_1833_p3 = ((sel_tmp31_fu_1828_p2[0:0] === 1'b1) ? tmp_35_1_1_fu_1659_p2 : sel_tmp29_fu_1809_p3);

assign kernel_val_1_V_2_w_fu_2077_p3 = ((sel_tmp39_fu_2072_p2[0:0] === 1'b1) ? tmp_35_1_2_fu_1903_p2 : sel_tmp37_fu_2053_p3);

assign kernel_val_2_V_2_w_fu_2378_p3 = ((or_cond_fu_2364_p2[0:0] === 1'b1) ? newSel_fu_2356_p3 : newSel1_fu_2370_p3);

assign man_V_1_0_1_fu_1120_p2 = (54'd0 - p_Result_7_0_1_fu_1116_p1);

assign man_V_1_0_2_fu_1364_p2 = (54'd0 - p_Result_7_0_2_fu_1360_p1);

assign man_V_1_1_1_fu_1608_p2 = (54'd0 - p_Result_7_1_1_fu_1604_p1);

assign man_V_1_1_2_fu_1852_p2 = (54'd0 - p_Result_7_1_2_fu_1848_p1);

assign man_V_1_2_2_fu_2096_p2 = (54'd0 - p_Result_7_2_2_fu_2092_p1);

assign man_V_1_fu_876_p2 = (54'd0 - p_Result_7_fu_872_p1);

assign man_V_4_0_1_fu_1126_p3 = ((tmp_43_reg_2700[0:0] === 1'b1) ? man_V_1_0_1_fu_1120_p2 : p_Result_7_0_1_fu_1116_p1);

assign man_V_4_0_2_fu_1370_p3 = ((tmp_55_reg_2754[0:0] === 1'b1) ? man_V_1_0_2_fu_1364_p2 : p_Result_7_0_2_fu_1360_p1);

assign man_V_4_1_1_fu_1614_p3 = ((tmp_67_reg_2808[0:0] === 1'b1) ? man_V_1_1_1_fu_1608_p2 : p_Result_7_1_1_fu_1604_p1);

assign man_V_4_1_2_fu_1858_p3 = ((tmp_79_reg_2862[0:0] === 1'b1) ? man_V_1_1_2_fu_1852_p2 : p_Result_7_1_2_fu_1848_p1);

assign man_V_4_2_2_fu_2102_p3 = ((tmp_91_reg_2916[0:0] === 1'b1) ? man_V_1_2_2_fu_2096_p2 : p_Result_7_2_2_fu_2092_p1);

assign man_V_4_fu_882_p3 = ((tmp_21_reg_2646[0:0] === 1'b1) ? man_V_1_fu_876_p2 : p_Result_7_fu_872_p1);

assign newSel1_fu_2370_p3 = ((sel_tmp41_fu_2315_p2[0:0] === 1'b1) ? tmp_93_fu_2141_p1 : 32'd0);

assign newSel_fu_2356_p3 = ((sel_tmp45_fu_2350_p2[0:0] === 1'b1) ? tmp_35_2_2_fu_2188_p2 : p_Val2_4_2_2_fu_2304_p2);

assign notlhs_fu_203_p2 = ((tmp_fu_189_p4 != 8'd255) ? 1'b1 : 1'b0);

assign notrhs_fu_209_p2 = ((tmp_9_fu_199_p1 == 23'd0) ? 1'b1 : 1'b0);

assign or_cond_fu_2364_p2 = (sel_tmp45_fu_2350_p2 | sel_tmp43_fu_2332_p2);

assign p_Result_1_0_1_fu_439_p4 = {{ireg_V_0_1_fu_423_p1[62:52]}};

assign p_Result_1_0_2_fu_537_p4 = {{ireg_V_0_2_fu_521_p1[62:52]}};

assign p_Result_1_1_1_fu_635_p4 = {{ireg_V_1_1_fu_619_p1[62:52]}};

assign p_Result_1_1_2_fu_733_p4 = {{ireg_V_1_2_fu_717_p1[62:52]}};

assign p_Result_1_2_2_fu_831_p4 = {{ireg_V_2_2_fu_815_p1[62:52]}};

assign p_Result_1_fu_341_p4 = {{ireg_V_fu_325_p1[62:52]}};

assign p_Result_7_0_1_fu_1116_p1 = tmp_4_fu_1109_p3;

assign p_Result_7_0_2_fu_1360_p1 = tmp_5_fu_1353_p3;

assign p_Result_7_1_1_fu_1604_p1 = tmp_6_fu_1597_p3;

assign p_Result_7_1_2_fu_1848_p1 = tmp_7_fu_1841_p3;

assign p_Result_7_2_2_fu_2092_p1 = tmp_8_fu_2085_p3;

assign p_Result_7_fu_872_p1 = tmp_1_fu_865_p3;

assign p_Val2_3_0_1_fu_1177_p3 = ((tmp_29_0_1_fu_1145_p2[0:0] === 1'b1) ? tmp_47_fu_1160_p1 : storemerge_0_1_fu_1164_p3);

assign p_Val2_3_0_2_fu_1421_p3 = ((tmp_29_0_2_fu_1389_p2[0:0] === 1'b1) ? tmp_59_fu_1404_p1 : storemerge_0_2_fu_1408_p3);

assign p_Val2_3_1_1_fu_1665_p3 = ((tmp_29_1_1_fu_1633_p2[0:0] === 1'b1) ? tmp_71_fu_1648_p1 : storemerge_1_1_fu_1652_p3);

assign p_Val2_3_1_2_fu_1909_p3 = ((tmp_29_1_2_fu_1877_p2[0:0] === 1'b1) ? tmp_83_fu_1892_p1 : storemerge_1_2_fu_1896_p3);

assign p_Val2_3_2_2_fu_2194_p3 = ((tmp_29_2_2_fu_2145_p2[0:0] === 1'b1) ? tmp_95_fu_2177_p1 : storemerge_2_2_fu_2181_p3);

assign p_Val2_3_fu_933_p3 = ((tmp_20_fu_901_p2[0:0] === 1'b1) ? tmp_35_fu_916_p1 : storemerge_fu_920_p3);

assign p_Val2_4_0_1_fu_1280_p2 = (tmp_46_0_1_fu_1276_p1 + p_Val2_3_0_1_fu_1177_p3);

assign p_Val2_4_0_2_fu_1524_p2 = (tmp_46_0_2_fu_1520_p1 + p_Val2_3_0_2_fu_1421_p3);

assign p_Val2_4_1_1_fu_1768_p2 = (tmp_46_1_1_fu_1764_p1 + p_Val2_3_1_1_fu_1665_p3);

assign p_Val2_4_1_2_fu_2012_p2 = (tmp_46_1_2_fu_2008_p1 + p_Val2_3_1_2_fu_1909_p3);

assign p_Val2_4_2_2_fu_2304_p2 = (tmp_46_2_2_fu_2300_p1 + p_Val2_3_2_2_fu_2194_p3);

assign p_Val2_4_fu_1036_p2 = (tmp_34_fu_1032_p1 + p_Val2_3_fu_933_p3);

assign p_r_i_i_i_0_1_fu_1265_p2 = (tmp_43_reg_2700 | r_0_1_fu_1259_p2);

assign p_r_i_i_i_0_2_fu_1509_p2 = (tmp_55_reg_2754 | r_0_2_fu_1503_p2);

assign p_r_i_i_i_1_1_fu_1753_p2 = (tmp_67_reg_2808 | r_1_1_fu_1747_p2);

assign p_r_i_i_i_1_2_fu_1997_p2 = (tmp_79_reg_2862 | r_1_2_fu_1991_p2);

assign p_r_i_i_i_2_2_fu_2289_p2 = (tmp_91_reg_2916 | r_2_2_fu_2283_p2);

assign p_r_i_i_i_fu_1021_p2 = (tmp_21_reg_2646 | r_fu_1015_p2);

assign qb_0_1_fu_1202_p3 = ((tmp_36_0_1_reg_2744[0:0] === 1'b1) ? tmp_43_reg_2700 : tmp_48_fu_1194_p3);

assign qb_0_2_fu_1446_p3 = ((tmp_36_0_2_reg_2798[0:0] === 1'b1) ? tmp_55_reg_2754 : tmp_60_fu_1438_p3);

assign qb_1_1_fu_1690_p3 = ((tmp_36_1_1_reg_2852[0:0] === 1'b1) ? tmp_67_reg_2808 : tmp_72_fu_1682_p3);

assign qb_1_2_fu_1934_p3 = ((tmp_36_1_2_reg_2906[0:0] === 1'b1) ? tmp_79_reg_2862 : tmp_84_fu_1926_p3);

assign qb_2_2_fu_2225_p3 = ((tmp_36_2_2_fu_2202_p2[0:0] === 1'b1) ? tmp_91_reg_2916 : tmp_96_fu_2217_p3);

assign qb_assign_1_0_1_fu_1270_p2 = (qb_0_1_fu_1202_p3 & p_r_i_i_i_0_1_fu_1265_p2);

assign qb_assign_1_0_2_fu_1514_p2 = (qb_0_2_fu_1446_p3 & p_r_i_i_i_0_2_fu_1509_p2);

assign qb_assign_1_1_1_fu_1758_p2 = (qb_1_1_fu_1690_p3 & p_r_i_i_i_1_1_fu_1753_p2);

assign qb_assign_1_1_2_fu_2002_p2 = (qb_1_2_fu_1934_p3 & p_r_i_i_i_1_2_fu_1997_p2);

assign qb_assign_1_2_2_fu_2294_p2 = (qb_2_2_fu_2225_p3 & p_r_i_i_i_2_2_fu_2289_p2);

assign qb_assign_1_fu_1026_p2 = (qb_fu_958_p3 & p_r_i_i_i_fu_1021_p2);

assign qb_fu_958_p3 = ((tmp_26_reg_2690[0:0] === 1'b1) ? tmp_21_reg_2646 : tmp_36_fu_950_p3);

assign r_0_1_fu_1259_p2 = (tmp_44_0_1_fu_1253_p2 & tmp_40_0_1_fu_1208_p2);

assign r_0_2_fu_1503_p2 = (tmp_44_0_2_fu_1497_p2 & tmp_40_0_2_fu_1452_p2);

assign r_1_1_fu_1747_p2 = (tmp_44_1_1_fu_1741_p2 & tmp_40_1_1_fu_1696_p2);

assign r_1_2_fu_1991_p2 = (tmp_44_1_2_fu_1985_p2 & tmp_40_1_2_fu_1940_p2);

assign r_2_2_fu_2283_p2 = (tmp_44_2_2_fu_2277_p2 & tmp_40_2_2_fu_2232_p2);

assign r_fu_1015_p2 = (tmp_33_fu_1009_p2 & tmp_28_fu_964_p2);

assign sel_tmp10_fu_1297_p3 = ((sel_tmp9_fu_1291_p2[0:0] === 1'b1) ? tmp_45_fu_1141_p1 : 32'd0);

assign sel_tmp11_fu_1310_p2 = (sel_tmp25_demorgan_fu_1305_p2 ^ 1'd1);

assign sel_tmp120_demorgan_fu_1793_p2 = (tmp_27_1_1_fu_1624_p2 | tmp_22_1_1_reg_2821);

assign sel_tmp127_demorgan_fu_1817_p2 = (tmp_24_1_1_reg_2835 | sel_tmp120_demorgan_fu_1793_p2);

assign sel_tmp12_fu_1316_p2 = (tmp_24_0_1_reg_2727 & sel_tmp11_fu_1310_p2);

assign sel_tmp139_demorgan_fu_2037_p2 = (tmp_27_1_2_fu_1868_p2 | tmp_22_1_2_reg_2875);

assign sel_tmp13_demorgan_fu_1085_p2 = (tmp_15_reg_2673 | sel_tmp6_demorgan_fu_1061_p2);

assign sel_tmp13_fu_1321_p3 = ((sel_tmp12_fu_1316_p2[0:0] === 1'b1) ? p_Val2_4_0_1_fu_1280_p2 : sel_tmp10_fu_1297_p3);

assign sel_tmp146_demorgan_fu_2061_p2 = (tmp_24_1_2_reg_2889 | sel_tmp139_demorgan_fu_2037_p2);

assign sel_tmp14_fu_1334_p2 = (sel_tmp32_demorgan_fu_1329_p2 ^ 1'd1);

assign sel_tmp15_fu_1340_p2 = (sel_tmp14_fu_1334_p2 & icmp4_reg_2739);

assign sel_tmp16_fu_1530_p2 = (tmp_22_0_2_reg_2767 ^ 1'd1);

assign sel_tmp17_fu_1535_p2 = (tmp_27_0_2_fu_1380_p2 & sel_tmp16_fu_1530_p2);

assign sel_tmp18_fu_1541_p3 = ((sel_tmp17_fu_1535_p2[0:0] === 1'b1) ? tmp_57_fu_1385_p1 : 32'd0);

assign sel_tmp19_fu_1554_p2 = (sel_tmp44_demorgan_fu_1549_p2 ^ 1'd1);

assign sel_tmp1_fu_1042_p2 = (tmp_14_reg_2659 ^ 1'd1);

assign sel_tmp20_fu_1560_p2 = (tmp_24_0_2_reg_2781 & sel_tmp19_fu_1554_p2);

assign sel_tmp21_fu_1565_p3 = ((sel_tmp20_fu_1560_p2[0:0] === 1'b1) ? p_Val2_4_0_2_fu_1524_p2 : sel_tmp18_fu_1541_p3);

assign sel_tmp22_fu_1578_p2 = (sel_tmp51_demorgan_fu_1573_p2 ^ 1'd1);

assign sel_tmp234_demorgan_fu_2321_p2 = (tmp_27_2_2_fu_2136_p2 | tmp_22_2_2_reg_2929);

assign sel_tmp23_fu_1584_p2 = (sel_tmp22_fu_1578_p2 & icmp7_reg_2793);

assign sel_tmp241_demorgan_fu_2338_p2 = (tmp_24_2_2_fu_2109_p2 | sel_tmp234_demorgan_fu_2321_p2);

assign sel_tmp24_fu_1774_p2 = (tmp_22_1_1_reg_2821 ^ 1'd1);

assign sel_tmp25_demorgan_fu_1305_p2 = (tmp_27_0_1_fu_1136_p2 | tmp_22_0_1_reg_2713);

assign sel_tmp25_fu_1779_p2 = (tmp_27_1_1_fu_1624_p2 & sel_tmp24_fu_1774_p2);

assign sel_tmp26_fu_1785_p3 = ((sel_tmp25_fu_1779_p2[0:0] === 1'b1) ? tmp_69_fu_1629_p1 : 32'd0);

assign sel_tmp27_fu_1798_p2 = (sel_tmp120_demorgan_fu_1793_p2 ^ 1'd1);

assign sel_tmp28_fu_1804_p2 = (tmp_24_1_1_reg_2835 & sel_tmp27_fu_1798_p2);

assign sel_tmp29_fu_1809_p3 = ((sel_tmp28_fu_1804_p2[0:0] === 1'b1) ? p_Val2_4_1_1_fu_1768_p2 : sel_tmp26_fu_1785_p3);

assign sel_tmp2_fu_1047_p2 = (tmp_18_fu_892_p2 & sel_tmp1_fu_1042_p2);

assign sel_tmp30_fu_1822_p2 = (sel_tmp127_demorgan_fu_1817_p2 ^ 1'd1);

assign sel_tmp31_fu_1828_p2 = (sel_tmp30_fu_1822_p2 & icmp1_reg_2847);

assign sel_tmp32_demorgan_fu_1329_p2 = (tmp_24_0_1_reg_2727 | sel_tmp25_demorgan_fu_1305_p2);

assign sel_tmp32_fu_2018_p2 = (tmp_22_1_2_reg_2875 ^ 1'd1);

assign sel_tmp33_fu_2023_p2 = (tmp_27_1_2_fu_1868_p2 & sel_tmp32_fu_2018_p2);

assign sel_tmp34_fu_2029_p3 = ((sel_tmp33_fu_2023_p2[0:0] === 1'b1) ? tmp_81_fu_1873_p1 : 32'd0);

assign sel_tmp35_fu_2042_p2 = (sel_tmp139_demorgan_fu_2037_p2 ^ 1'd1);

assign sel_tmp36_fu_2048_p2 = (tmp_24_1_2_reg_2889 & sel_tmp35_fu_2042_p2);

assign sel_tmp37_fu_2053_p3 = ((sel_tmp36_fu_2048_p2[0:0] === 1'b1) ? p_Val2_4_1_2_fu_2012_p2 : sel_tmp34_fu_2029_p3);

assign sel_tmp38_fu_2066_p2 = (sel_tmp146_demorgan_fu_2061_p2 ^ 1'd1);

assign sel_tmp39_fu_2072_p2 = (sel_tmp38_fu_2066_p2 & icmp2_reg_2901);

assign sel_tmp3_fu_1053_p3 = ((sel_tmp2_fu_1047_p2[0:0] === 1'b1) ? tmp_29_fu_897_p1 : 32'd0);

assign sel_tmp40_fu_2310_p2 = (tmp_22_2_2_reg_2929 ^ 1'd1);

assign sel_tmp41_fu_2315_p2 = (tmp_27_2_2_fu_2136_p2 & sel_tmp40_fu_2310_p2);

assign sel_tmp42_fu_2326_p2 = (sel_tmp234_demorgan_fu_2321_p2 ^ 1'd1);

assign sel_tmp43_fu_2332_p2 = (tmp_24_2_2_fu_2109_p2 & sel_tmp42_fu_2326_p2);

assign sel_tmp44_demorgan_fu_1549_p2 = (tmp_27_0_2_fu_1380_p2 | tmp_22_0_2_reg_2767);

assign sel_tmp44_fu_2344_p2 = (sel_tmp241_demorgan_fu_2338_p2 ^ 1'd1);

assign sel_tmp45_fu_2350_p2 = (sel_tmp44_fu_2344_p2 & icmp3_fu_2161_p2);

assign sel_tmp4_fu_1096_p2 = (sel_tmp_fu_1090_p2 & icmp_reg_2685);

assign sel_tmp51_demorgan_fu_1573_p2 = (tmp_24_0_2_reg_2781 | sel_tmp44_demorgan_fu_1549_p2);

assign sel_tmp5_fu_1286_p2 = (tmp_22_0_1_reg_2713 ^ 1'd1);

assign sel_tmp6_demorgan_fu_1061_p2 = (tmp_18_fu_892_p2 | tmp_14_reg_2659);

assign sel_tmp6_fu_1066_p2 = (sel_tmp6_demorgan_fu_1061_p2 ^ 1'd1);

assign sel_tmp7_fu_1072_p2 = (tmp_15_reg_2673 & sel_tmp6_fu_1066_p2);

assign sel_tmp8_fu_1077_p3 = ((sel_tmp7_fu_1072_p2[0:0] === 1'b1) ? p_Val2_4_fu_1036_p2 : sel_tmp3_fu_1053_p3);

assign sel_tmp9_fu_1291_p2 = (tmp_27_0_1_fu_1136_p2 & sel_tmp5_fu_1286_p2);

assign sel_tmp_fu_1090_p2 = (sel_tmp13_demorgan_fu_1085_p2 ^ 1'd1);

assign sh_amt_0_1_cast_fu_1133_p1 = sh_amt_0_1_reg_2733;

assign sh_amt_0_1_fu_487_p3 = ((tmp_24_0_1_fu_469_p2[0:0] === 1'b1) ? tmp_25_0_1_fu_475_p2 : tmp_26_0_1_fu_481_p2);

assign sh_amt_0_2_cast_fu_1377_p1 = sh_amt_0_2_reg_2787;

assign sh_amt_0_2_fu_585_p3 = ((tmp_24_0_2_fu_567_p2[0:0] === 1'b1) ? tmp_25_0_2_fu_573_p2 : tmp_26_0_2_fu_579_p2);

assign sh_amt_0_cast_fu_889_p1 = sh_amt_reg_2679;

assign sh_amt_1_1_cast_fu_1621_p1 = sh_amt_1_1_reg_2841;

assign sh_amt_1_1_fu_683_p3 = ((tmp_24_1_1_fu_665_p2[0:0] === 1'b1) ? tmp_25_1_1_fu_671_p2 : tmp_26_1_1_fu_677_p2);

assign sh_amt_1_2_cast_fu_1865_p1 = sh_amt_1_2_reg_2895;

assign sh_amt_1_2_fu_781_p3 = ((tmp_24_1_2_fu_763_p2[0:0] === 1'b1) ? tmp_25_1_2_fu_769_p2 : tmp_26_1_2_fu_775_p2);

assign sh_amt_2_2_cast_fu_2132_p1 = sh_amt_2_2_fu_2124_p3;

assign sh_amt_2_2_fu_2124_p3 = ((tmp_24_2_2_fu_2109_p2[0:0] === 1'b1) ? tmp_25_2_2_fu_2114_p2 : tmp_26_2_2_fu_2119_p2);

assign sh_amt_fu_389_p3 = ((tmp_15_fu_371_p2[0:0] === 1'b1) ? tmp_16_fu_377_p2 : tmp_17_fu_383_p2);

assign sigmaX_assign_fu_227_p3 = ((tmp_12_fu_221_p2[0:0] === 1'b1) ? 32'd1066192077 : sigmaX);

assign sigmaX_to_int_fu_185_p1 = sigmaX;

assign storemerge_0_1_fu_1164_p3 = ((tmp_43_reg_2700[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign storemerge_0_2_fu_1408_p3 = ((tmp_55_reg_2754[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign storemerge_1_1_fu_1652_p3 = ((tmp_67_reg_2808[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign storemerge_1_2_fu_1896_p3 = ((tmp_79_reg_2862[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign storemerge_2_2_fu_2181_p3 = ((tmp_91_reg_2916[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign storemerge_fu_920_p3 = ((tmp_21_reg_2646[0:0] === 1'b1) ? 32'd4294967295 : 32'd0);

assign temp_neg_0_1_fu_254_p2 = (temp_to_int_0_1_fu_250_p1 ^ 32'd2147483648);

assign temp_neg_0_2_fu_269_p2 = (temp_to_int_0_2_fu_265_p1 ^ 32'd2147483648);

assign temp_neg_1_1_fu_284_p2 = (temp_to_int_1_1_fu_280_p1 ^ 32'd2147483648);

assign temp_neg_1_2_fu_299_p2 = (temp_to_int_1_2_fu_295_p1 ^ 32'd2147483648);

assign temp_neg_2_2_fu_314_p2 = (temp_to_int_2_2_fu_310_p1 ^ 32'd2147483648);

assign temp_neg_fu_239_p2 = (temp_to_int_fu_235_p1 ^ 32'd2147483648);

assign temp_to_int_0_1_fu_250_p1 = reg_175;

assign temp_to_int_0_2_fu_265_p1 = reg_175;

assign temp_to_int_1_1_fu_280_p1 = reg_181;

assign temp_to_int_1_2_fu_295_p1 = reg_181;

assign temp_to_int_2_2_fu_310_p1 = reg_181;

assign temp_to_int_fu_235_p1 = reg_175;

assign tmp_100_fu_2265_p2 = 54'd18014398509481983 >> tmp_99_fu_2261_p1;

assign tmp_101_fu_2271_p2 = (tmp_100_fu_2265_p2 & man_V_4_2_2_fu_2102_p3);

assign tmp_10_fu_215_p2 = (notrhs_fu_209_p2 | notlhs_fu_203_p2);

assign tmp_12_fu_221_p2 = (tmp_11_fu_145_p2 & tmp_10_fu_215_p2);

assign tmp_13_fu_351_p1 = p_Result_1_fu_341_p4;

assign tmp_14_fu_359_p2 = ((tmp_19_fu_329_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_15_fu_371_p2 = (($signed(F2_fu_365_p2) > $signed(12'd22)) ? 1'b1 : 1'b0);

assign tmp_16_fu_377_p2 = ($signed(12'd4074) + $signed(F2_fu_365_p2));

assign tmp_17_fu_383_p2 = (12'd22 - F2_fu_365_p2);

assign tmp_18_fu_892_p2 = ((F2_reg_2665 == 12'd22) ? 1'b1 : 1'b0);

assign tmp_19_fu_329_p1 = ireg_V_fu_325_p1[62:0];

assign tmp_1_fu_865_p3 = {{1'd1}, {tmp_24_reg_2654}};

assign tmp_20_0_1_fu_449_p1 = p_Result_1_0_1_fu_439_p4;

assign tmp_20_0_2_fu_547_p1 = p_Result_1_0_2_fu_537_p4;

assign tmp_20_1_1_fu_645_p1 = p_Result_1_1_1_fu_635_p4;

assign tmp_20_1_2_fu_743_p1 = p_Result_1_1_2_fu_733_p4;

assign tmp_20_2_2_fu_841_p1 = p_Result_1_2_2_fu_831_p4;

assign tmp_20_fu_901_p2 = ((sh_amt_reg_2679 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_22_0_1_fu_457_p2 = ((tmp_42_fu_427_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_22_0_2_fu_555_p2 = ((tmp_54_fu_525_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_22_1_1_fu_653_p2 = ((tmp_66_fu_623_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_22_1_2_fu_751_p2 = ((tmp_78_fu_721_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_22_2_2_fu_849_p2 = ((tmp_90_fu_819_p1 == 63'd0) ? 1'b1 : 1'b0);

assign tmp_22_fu_906_p1 = $unsigned(sh_amt_0_cast_fu_889_p1);

assign tmp_23_fu_910_p2 = $signed(man_V_4_fu_882_p3) >>> tmp_22_fu_906_p1;

assign tmp_24_0_1_fu_469_p2 = (($signed(F2_0_1_fu_463_p2) > $signed(12'd22)) ? 1'b1 : 1'b0);

assign tmp_24_0_2_fu_567_p2 = (($signed(F2_0_2_fu_561_p2) > $signed(12'd22)) ? 1'b1 : 1'b0);

assign tmp_24_1_1_fu_665_p2 = (($signed(F2_1_1_fu_659_p2) > $signed(12'd22)) ? 1'b1 : 1'b0);

assign tmp_24_1_2_fu_763_p2 = (($signed(F2_1_2_fu_757_p2) > $signed(12'd22)) ? 1'b1 : 1'b0);

assign tmp_24_2_2_fu_2109_p2 = (($signed(F2_2_2_reg_2935) > $signed(12'd22)) ? 1'b1 : 1'b0);

assign tmp_24_fu_355_p1 = ireg_V_fu_325_p1[51:0];

assign tmp_25_0_1_fu_475_p2 = ($signed(12'd4074) + $signed(F2_0_1_fu_463_p2));

assign tmp_25_0_2_fu_573_p2 = ($signed(12'd4074) + $signed(F2_0_2_fu_561_p2));

assign tmp_25_1_1_fu_671_p2 = ($signed(12'd4074) + $signed(F2_1_1_fu_659_p2));

assign tmp_25_1_2_fu_769_p2 = ($signed(12'd4074) + $signed(F2_1_2_fu_757_p2));

assign tmp_25_2_2_fu_2114_p2 = ($signed(12'd4074) + $signed(F2_2_2_reg_2935));

assign tmp_25_fu_927_p2 = tmp_29_fu_897_p1 << sh_amt_0_cast_fu_889_p1;

assign tmp_26_0_1_fu_481_p2 = (12'd22 - F2_0_1_fu_463_p2);

assign tmp_26_0_2_fu_579_p2 = (12'd22 - F2_0_2_fu_561_p2);

assign tmp_26_1_1_fu_677_p2 = (12'd22 - F2_1_1_fu_659_p2);

assign tmp_26_1_2_fu_775_p2 = (12'd22 - F2_1_2_fu_757_p2);

assign tmp_26_2_2_fu_2119_p2 = (12'd22 - F2_2_2_reg_2935);

assign tmp_26_fu_413_p2 = (($signed(tmp_16_fu_377_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_27_0_1_fu_1136_p2 = ((F2_0_1_reg_2719 == 12'd22) ? 1'b1 : 1'b0);

assign tmp_27_0_2_fu_1380_p2 = ((F2_0_2_reg_2773 == 12'd22) ? 1'b1 : 1'b0);

assign tmp_27_1_1_fu_1624_p2 = ((F2_1_1_reg_2827 == 12'd22) ? 1'b1 : 1'b0);

assign tmp_27_1_2_fu_1868_p2 = ((F2_1_2_reg_2881 == 12'd22) ? 1'b1 : 1'b0);

assign tmp_27_2_2_fu_2136_p2 = ((F2_2_2_reg_2935 == 12'd22) ? 1'b1 : 1'b0);

assign tmp_27_fu_941_p2 = ($signed(12'd4073) + $signed(F2_reg_2665));

assign tmp_28_fu_964_p2 = (($signed(F2_reg_2665) > $signed(12'd23)) ? 1'b1 : 1'b0);

assign tmp_29_0_1_fu_1145_p2 = ((sh_amt_0_1_reg_2733 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_29_0_2_fu_1389_p2 = ((sh_amt_0_2_reg_2787 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_29_1_1_fu_1633_p2 = ((sh_amt_1_1_reg_2841 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_29_1_2_fu_1877_p2 = ((sh_amt_1_2_reg_2895 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_29_2_2_fu_2145_p2 = ((sh_amt_2_2_fu_2124_p3 < 12'd54) ? 1'b1 : 1'b0);

assign tmp_29_fu_897_p1 = man_V_4_fu_882_p3[31:0];

assign tmp_30_fu_969_p2 = ($signed(12'd4072) + $signed(F2_reg_2665));

assign tmp_31_fu_974_p2 = (($signed(tmp_30_fu_969_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign tmp_32_0_1_fu_1150_p1 = $unsigned(sh_amt_0_1_cast_fu_1133_p1);

assign tmp_32_0_2_fu_1394_p1 = $unsigned(sh_amt_0_2_cast_fu_1377_p1);

assign tmp_32_1_1_fu_1638_p1 = $unsigned(sh_amt_1_1_cast_fu_1621_p1);

assign tmp_32_1_2_fu_1882_p1 = $unsigned(sh_amt_1_2_cast_fu_1865_p1);

assign tmp_32_2_2_fu_2167_p1 = $unsigned(sh_amt_2_2_cast_fu_2132_p1);

assign tmp_32_fu_397_p4 = {{sh_amt_fu_389_p3[11:5]}};

assign tmp_33_0_1_fu_1154_p2 = $signed(man_V_4_0_1_fu_1126_p3) >>> tmp_32_0_1_fu_1150_p1;

assign tmp_33_0_2_fu_1398_p2 = $signed(man_V_4_0_2_fu_1370_p3) >>> tmp_32_0_2_fu_1394_p1;

assign tmp_33_1_1_fu_1642_p2 = $signed(man_V_4_1_1_fu_1614_p3) >>> tmp_32_1_1_fu_1638_p1;

assign tmp_33_1_2_fu_1886_p2 = $signed(man_V_4_1_2_fu_1858_p3) >>> tmp_32_1_2_fu_1882_p1;

assign tmp_33_2_2_fu_2171_p2 = $signed(man_V_4_2_2_fu_2102_p3) >>> tmp_32_2_2_fu_2167_p1;

assign tmp_33_fu_1009_p2 = ((tmp_41_fu_1003_p2 != 54'd0) ? 1'b1 : 1'b0);

assign tmp_34_fu_1032_p1 = qb_assign_1_fu_1026_p2;

assign tmp_35_0_1_fu_1171_p2 = tmp_45_fu_1141_p1 << sh_amt_0_1_cast_fu_1133_p1;

assign tmp_35_0_2_fu_1415_p2 = tmp_57_fu_1385_p1 << sh_amt_0_2_cast_fu_1377_p1;

assign tmp_35_1_1_fu_1659_p2 = tmp_69_fu_1629_p1 << sh_amt_1_1_cast_fu_1621_p1;

assign tmp_35_1_2_fu_1903_p2 = tmp_81_fu_1873_p1 << sh_amt_1_2_cast_fu_1865_p1;

assign tmp_35_2_2_fu_2188_p2 = tmp_93_fu_2141_p1 << sh_amt_2_2_cast_fu_2132_p1;

assign tmp_35_fu_916_p1 = tmp_23_fu_910_p2[31:0];

assign tmp_36_0_1_fu_511_p2 = (($signed(tmp_25_0_1_fu_475_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_36_0_2_fu_609_p2 = (($signed(tmp_25_0_2_fu_573_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_36_1_1_fu_707_p2 = (($signed(tmp_25_1_1_fu_671_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_36_1_2_fu_805_p2 = (($signed(tmp_25_1_2_fu_769_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_36_2_2_fu_2202_p2 = (($signed(tmp_25_2_2_fu_2114_p2) > $signed(12'd54)) ? 1'b1 : 1'b0);

assign tmp_36_fu_950_p3 = man_V_4_fu_882_p3[tmp_37_0_cast_fu_946_p1];

assign tmp_37_0_1_cast_fu_1190_p1 = tmp_37_0_1_fu_1185_p2;

assign tmp_37_0_1_fu_1185_p2 = ($signed(12'd4073) + $signed(F2_0_1_reg_2719));

assign tmp_37_0_2_cast_fu_1434_p1 = tmp_37_0_2_fu_1429_p2;

assign tmp_37_0_2_fu_1429_p2 = ($signed(12'd4073) + $signed(F2_0_2_reg_2773));

assign tmp_37_0_cast_fu_946_p1 = tmp_27_fu_941_p2;

assign tmp_37_1_1_cast_fu_1678_p1 = tmp_37_1_1_fu_1673_p2;

assign tmp_37_1_1_fu_1673_p2 = ($signed(12'd4073) + $signed(F2_1_1_reg_2827));

assign tmp_37_1_2_cast_fu_1922_p1 = tmp_37_1_2_fu_1917_p2;

assign tmp_37_1_2_fu_1917_p2 = ($signed(12'd4073) + $signed(F2_1_2_reg_2881));

assign tmp_37_2_2_cast_fu_2213_p1 = tmp_37_2_2_fu_2208_p2;

assign tmp_37_2_2_fu_2208_p2 = ($signed(12'd4073) + $signed(F2_2_2_reg_2935));

assign tmp_37_fu_419_p1 = F2_fu_365_p2[5:0];

assign tmp_38_fu_985_p3 = ((tmp_31_fu_974_p2[0:0] === 1'b1) ? 6'd0 : tmp_41_0_cast_op_fu_980_p2);

assign tmp_39_fu_993_p1 = tmp_38_fu_985_p3;

assign tmp_40_0_1_fu_1208_p2 = (($signed(F2_0_1_reg_2719) > $signed(12'd23)) ? 1'b1 : 1'b0);

assign tmp_40_0_2_fu_1452_p2 = (($signed(F2_0_2_reg_2773) > $signed(12'd23)) ? 1'b1 : 1'b0);

assign tmp_40_1_1_fu_1696_p2 = (($signed(F2_1_1_reg_2827) > $signed(12'd23)) ? 1'b1 : 1'b0);

assign tmp_40_1_2_fu_1940_p2 = (($signed(F2_1_2_reg_2881) > $signed(12'd23)) ? 1'b1 : 1'b0);

assign tmp_40_2_2_fu_2232_p2 = (($signed(F2_2_2_reg_2935) > $signed(12'd23)) ? 1'b1 : 1'b0);

assign tmp_40_fu_997_p2 = 54'd18014398509481983 >> tmp_39_fu_993_p1;

assign tmp_41_0_1_cast_op_fu_1224_p2 = (6'd13 - tmp_49_reg_2749);

assign tmp_41_0_1_fu_1213_p2 = ($signed(12'd4072) + $signed(F2_0_1_reg_2719));

assign tmp_41_0_2_cast_op_fu_1468_p2 = (6'd13 - tmp_61_reg_2803);

assign tmp_41_0_2_fu_1457_p2 = ($signed(12'd4072) + $signed(F2_0_2_reg_2773));

assign tmp_41_0_cast_op_fu_980_p2 = (6'd13 - tmp_37_reg_2695);

assign tmp_41_1_1_cast_op_fu_1712_p2 = (6'd13 - tmp_73_reg_2857);

assign tmp_41_1_1_fu_1701_p2 = ($signed(12'd4072) + $signed(F2_1_1_reg_2827));

assign tmp_41_1_2_cast_op_fu_1956_p2 = (6'd13 - tmp_85_reg_2911);

assign tmp_41_1_2_fu_1945_p2 = ($signed(12'd4072) + $signed(F2_1_2_reg_2881));

assign tmp_41_2_2_cast_op_fu_2248_p2 = (6'd13 - tmp_97_reg_2946);

assign tmp_41_2_2_fu_2237_p2 = ($signed(12'd4072) + $signed(F2_2_2_reg_2935));

assign tmp_41_fu_1003_p2 = (tmp_40_fu_997_p2 & man_V_4_fu_882_p3);

assign tmp_42_0_1_fu_1218_p2 = (($signed(tmp_41_0_1_fu_1213_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign tmp_42_0_2_fu_1462_p2 = (($signed(tmp_41_0_2_fu_1457_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign tmp_42_1_1_fu_1706_p2 = (($signed(tmp_41_1_1_fu_1701_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign tmp_42_1_2_fu_1950_p2 = (($signed(tmp_41_1_2_fu_1945_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign tmp_42_2_2_fu_2242_p2 = (($signed(tmp_41_2_2_fu_2237_p2) > $signed(12'd53)) ? 1'b1 : 1'b0);

assign tmp_42_fu_427_p1 = ireg_V_0_1_fu_423_p1[62:0];

assign tmp_44_0_1_fu_1253_p2 = ((tmp_53_fu_1247_p2 != 54'd0) ? 1'b1 : 1'b0);

assign tmp_44_0_2_fu_1497_p2 = ((tmp_65_fu_1491_p2 != 54'd0) ? 1'b1 : 1'b0);

assign tmp_44_1_1_fu_1741_p2 = ((tmp_77_fu_1735_p2 != 54'd0) ? 1'b1 : 1'b0);

assign tmp_44_1_2_fu_1985_p2 = ((tmp_89_fu_1979_p2 != 54'd0) ? 1'b1 : 1'b0);

assign tmp_44_2_2_fu_2277_p2 = ((tmp_101_fu_2271_p2 != 54'd0) ? 1'b1 : 1'b0);

assign tmp_44_fu_453_p1 = ireg_V_0_1_fu_423_p1[51:0];

assign tmp_45_fu_1141_p1 = man_V_4_0_1_fu_1126_p3[31:0];

assign tmp_46_0_1_fu_1276_p1 = qb_assign_1_0_1_fu_1270_p2;

assign tmp_46_0_2_fu_1520_p1 = qb_assign_1_0_2_fu_1514_p2;

assign tmp_46_1_1_fu_1764_p1 = qb_assign_1_1_1_fu_1758_p2;

assign tmp_46_1_2_fu_2008_p1 = qb_assign_1_1_2_fu_2002_p2;

assign tmp_46_2_2_fu_2300_p1 = qb_assign_1_2_2_fu_2294_p2;

assign tmp_46_fu_495_p4 = {{sh_amt_0_1_fu_487_p3[11:5]}};

assign tmp_47_fu_1160_p1 = tmp_33_0_1_fu_1154_p2[31:0];

assign tmp_48_fu_1194_p3 = man_V_4_0_1_fu_1126_p3[tmp_37_0_1_cast_fu_1190_p1];

assign tmp_49_fu_517_p1 = F2_0_1_fu_463_p2[5:0];

assign tmp_4_fu_1109_p3 = {{1'd1}, {tmp_44_reg_2708}};

assign tmp_50_fu_1229_p3 = ((tmp_42_0_1_fu_1218_p2[0:0] === 1'b1) ? 6'd0 : tmp_41_0_1_cast_op_fu_1224_p2);

assign tmp_51_fu_1237_p1 = tmp_50_fu_1229_p3;

assign tmp_52_fu_1241_p2 = 54'd18014398509481983 >> tmp_51_fu_1237_p1;

assign tmp_53_fu_1247_p2 = (tmp_52_fu_1241_p2 & man_V_4_0_1_fu_1126_p3);

assign tmp_54_fu_525_p1 = ireg_V_0_2_fu_521_p1[62:0];

assign tmp_56_fu_551_p1 = ireg_V_0_2_fu_521_p1[51:0];

assign tmp_57_fu_1385_p1 = man_V_4_0_2_fu_1370_p3[31:0];

assign tmp_58_fu_593_p4 = {{sh_amt_0_2_fu_585_p3[11:5]}};

assign tmp_59_fu_1404_p1 = tmp_33_0_2_fu_1398_p2[31:0];

assign tmp_5_fu_1353_p3 = {{1'd1}, {tmp_56_reg_2762}};

assign tmp_60_fu_1438_p3 = man_V_4_0_2_fu_1370_p3[tmp_37_0_2_cast_fu_1434_p1];

assign tmp_61_fu_615_p1 = F2_0_2_fu_561_p2[5:0];

assign tmp_62_fu_1473_p3 = ((tmp_42_0_2_fu_1462_p2[0:0] === 1'b1) ? 6'd0 : tmp_41_0_2_cast_op_fu_1468_p2);

assign tmp_63_fu_1481_p1 = tmp_62_fu_1473_p3;

assign tmp_64_fu_1485_p2 = 54'd18014398509481983 >> tmp_63_fu_1481_p1;

assign tmp_65_fu_1491_p2 = (tmp_64_fu_1485_p2 & man_V_4_0_2_fu_1370_p3);

assign tmp_66_fu_623_p1 = ireg_V_1_1_fu_619_p1[62:0];

assign tmp_68_fu_649_p1 = ireg_V_1_1_fu_619_p1[51:0];

assign tmp_69_fu_1629_p1 = man_V_4_1_1_fu_1614_p3[31:0];

assign tmp_6_fu_1597_p3 = {{1'd1}, {tmp_68_reg_2816}};

assign tmp_70_fu_691_p4 = {{sh_amt_1_1_fu_683_p3[11:5]}};

assign tmp_71_fu_1648_p1 = tmp_33_1_1_fu_1642_p2[31:0];

assign tmp_72_fu_1682_p3 = man_V_4_1_1_fu_1614_p3[tmp_37_1_1_cast_fu_1678_p1];

assign tmp_73_fu_713_p1 = F2_1_1_fu_659_p2[5:0];

assign tmp_74_fu_1717_p3 = ((tmp_42_1_1_fu_1706_p2[0:0] === 1'b1) ? 6'd0 : tmp_41_1_1_cast_op_fu_1712_p2);

assign tmp_75_fu_1725_p1 = tmp_74_fu_1717_p3;

assign tmp_76_fu_1729_p2 = 54'd18014398509481983 >> tmp_75_fu_1725_p1;

assign tmp_77_fu_1735_p2 = (tmp_76_fu_1729_p2 & man_V_4_1_1_fu_1614_p3);

assign tmp_78_fu_721_p1 = ireg_V_1_2_fu_717_p1[62:0];

assign tmp_7_fu_1841_p3 = {{1'd1}, {tmp_80_reg_2870}};

assign tmp_80_fu_747_p1 = ireg_V_1_2_fu_717_p1[51:0];

assign tmp_81_fu_1873_p1 = man_V_4_1_2_fu_1858_p3[31:0];

assign tmp_82_fu_789_p4 = {{sh_amt_1_2_fu_781_p3[11:5]}};

assign tmp_83_fu_1892_p1 = tmp_33_1_2_fu_1886_p2[31:0];

assign tmp_84_fu_1926_p3 = man_V_4_1_2_fu_1858_p3[tmp_37_1_2_cast_fu_1922_p1];

assign tmp_85_fu_811_p1 = F2_1_2_fu_757_p2[5:0];

assign tmp_86_fu_1961_p3 = ((tmp_42_1_2_fu_1950_p2[0:0] === 1'b1) ? 6'd0 : tmp_41_1_2_cast_op_fu_1956_p2);

assign tmp_87_fu_1969_p1 = tmp_86_fu_1961_p3;

assign tmp_88_fu_1973_p2 = 54'd18014398509481983 >> tmp_87_fu_1969_p1;

assign tmp_89_fu_1979_p2 = (tmp_88_fu_1973_p2 & man_V_4_1_2_fu_1858_p3);

assign tmp_8_fu_2085_p3 = {{1'd1}, {tmp_92_reg_2924}};

assign tmp_90_fu_819_p1 = ireg_V_2_2_fu_815_p1[62:0];

assign tmp_92_fu_845_p1 = ireg_V_2_2_fu_815_p1[51:0];

assign tmp_93_fu_2141_p1 = man_V_4_2_2_fu_2102_p3[31:0];

assign tmp_94_fu_2151_p4 = {{sh_amt_2_2_fu_2124_p3[11:5]}};

assign tmp_95_fu_2177_p1 = tmp_33_2_2_fu_2171_p2[31:0];

assign tmp_96_fu_2217_p3 = man_V_4_2_2_fu_2102_p3[tmp_37_2_2_cast_fu_2213_p1];

assign tmp_97_fu_861_p1 = F2_2_2_fu_855_p2[5:0];

assign tmp_98_fu_2253_p3 = ((tmp_42_2_2_fu_2242_p2[0:0] === 1'b1) ? 6'd0 : tmp_41_2_2_cast_op_fu_2248_p2);

assign tmp_99_fu_2261_p1 = tmp_98_fu_2253_p3;

assign tmp_9_fu_199_p1 = sigmaX_to_int_fu_185_p1[22:0];

assign tmp_fu_189_p4 = {{sigmaX_to_int_fu_185_p1[30:23]}};

assign x_assign_1_fu_260_p1 = temp_neg_0_1_fu_254_p2;

assign x_assign_2_fu_275_p1 = temp_neg_0_2_fu_269_p2;

assign x_assign_3_fu_290_p1 = temp_neg_1_1_fu_284_p2;

assign x_assign_4_fu_305_p1 = temp_neg_1_2_fu_299_p2;

assign x_assign_5_fu_320_p1 = temp_neg_2_2_fu_314_p2;

assign x_assign_fu_245_p1 = temp_neg_fu_239_p2;

endmodule //getGaussianKernel
