// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "imgproc.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic imgproc::ap_const_logic_1 = sc_dt::Log_1;
const sc_lv<8> imgproc::ap_const_lv8_0 = "00000000";
const sc_lv<1> imgproc::ap_const_lv1_0 = "0";
const sc_lv<32> imgproc::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_logic imgproc::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<2> imgproc::ap_const_lv2_0 = "00";
const sc_lv<2> imgproc::ap_const_lv2_1 = "1";
const bool imgproc::ap_const_boolean_1 = true;
const sc_lv<16> imgproc::ap_const_lv16_0 = "0000000000000000";
const sc_lv<16> imgproc::ap_const_lv16_1 = "1";

imgproc::imgproc(sc_module_name name) : sc_module(name), mVcdFile(0) {
    arr0_val_U = new imgproc_arr0_val("arr0_val_U");
    arr0_val_U->clk(ap_clk);
    arr0_val_U->reset(ap_rst_n_inv);
    arr0_val_U->i_address0(Block_Mat_exit2022_p_U0_arr0_val_address0);
    arr0_val_U->i_ce0(Block_Mat_exit2022_p_U0_arr0_val_ce0);
    arr0_val_U->i_we0(Block_Mat_exit2022_p_U0_arr0_val_we0);
    arr0_val_U->i_d0(Block_Mat_exit2022_p_U0_arr0_val_d0);
    arr0_val_U->i_q0(arr0_val_i_q0);
    arr0_val_U->i_address1(ap_var_for_const0);
    arr0_val_U->i_ce1(ap_var_for_const1);
    arr0_val_U->i_q1(arr0_val_i_q1);
    arr0_val_U->t_address0(Resize_U0_src_val_address0);
    arr0_val_U->t_ce0(Resize_U0_src_val_ce0);
    arr0_val_U->t_we0(ap_var_for_const1);
    arr0_val_U->t_d0(ap_var_for_const2);
    arr0_val_U->t_q0(arr0_val_t_q0);
    arr0_val_U->t_address1(Resize_U0_src_val_address1);
    arr0_val_U->t_ce1(Resize_U0_src_val_ce1);
    arr0_val_U->t_q1(arr0_val_t_q1);
    arr0_val_U->i_ce(ap_var_for_const3);
    arr0_val_U->t_ce(ap_var_for_const3);
    arr0_val_U->i_full_n(arr0_val_i_full_n);
    arr0_val_U->i_write(ap_channel_done_arr0_val);
    arr0_val_U->t_empty_n(arr0_val_t_empty_n);
    arr0_val_U->t_read(Resize_U0_ap_ready);
    arr1_val_U = new imgproc_arr1_val("arr1_val_U");
    arr1_val_U->clk(ap_clk);
    arr1_val_U->reset(ap_rst_n_inv);
    arr1_val_U->i_address0(Resize_U0_dst_val_address0);
    arr1_val_U->i_ce0(Resize_U0_dst_val_ce0);
    arr1_val_U->i_we0(Resize_U0_dst_val_we0);
    arr1_val_U->i_d0(Resize_U0_dst_val_d0);
    arr1_val_U->i_q0(arr1_val_i_q0);
    arr1_val_U->t_address0(Array2D2Mat_U0_arr_val_address0);
    arr1_val_U->t_ce0(Array2D2Mat_U0_arr_val_ce0);
    arr1_val_U->t_we0(ap_var_for_const1);
    arr1_val_U->t_d0(ap_var_for_const2);
    arr1_val_U->t_q0(arr1_val_t_q0);
    arr1_val_U->i_ce(ap_var_for_const3);
    arr1_val_U->t_ce(ap_var_for_const3);
    arr1_val_U->i_full_n(arr1_val_i_full_n);
    arr1_val_U->i_write(Resize_U0_ap_done);
    arr1_val_U->t_empty_n(arr1_val_t_empty_n);
    arr1_val_U->t_read(Array2D2Mat_U0_ap_ready);
    Block_Mat_exit20_pro_U0 = new Block_Mat_exit20_pro("Block_Mat_exit20_pro_U0");
    Block_Mat_exit20_pro_U0->ap_clk(ap_clk);
    Block_Mat_exit20_pro_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit20_pro_U0->ap_start(Block_Mat_exit20_pro_U0_ap_start);
    Block_Mat_exit20_pro_U0->ap_done(Block_Mat_exit20_pro_U0_ap_done);
    Block_Mat_exit20_pro_U0->ap_continue(Block_Mat_exit20_pro_U0_ap_continue);
    Block_Mat_exit20_pro_U0->ap_idle(Block_Mat_exit20_pro_U0_ap_idle);
    Block_Mat_exit20_pro_U0->ap_ready(Block_Mat_exit20_pro_U0_ap_ready);
    Block_Mat_exit20_pro_U0->rows0(rows0);
    Block_Mat_exit20_pro_U0->cols0(cols0);
    Block_Mat_exit20_pro_U0->mat0_rows_V_out_din(Block_Mat_exit20_pro_U0_mat0_rows_V_out_din);
    Block_Mat_exit20_pro_U0->mat0_rows_V_out_full_n(mat0_rows_V_c_full_n);
    Block_Mat_exit20_pro_U0->mat0_rows_V_out_write(Block_Mat_exit20_pro_U0_mat0_rows_V_out_write);
    Block_Mat_exit20_pro_U0->mat0_cols_V_out_din(Block_Mat_exit20_pro_U0_mat0_cols_V_out_din);
    Block_Mat_exit20_pro_U0->mat0_cols_V_out_full_n(mat0_cols_V_c_full_n);
    Block_Mat_exit20_pro_U0->mat0_cols_V_out_write(Block_Mat_exit20_pro_U0_mat0_cols_V_out_write);
    AXIvideo2Mat_U0 = new AXIvideo2Mat("AXIvideo2Mat_U0");
    AXIvideo2Mat_U0->ap_clk(ap_clk);
    AXIvideo2Mat_U0->ap_rst(ap_rst_n_inv);
    AXIvideo2Mat_U0->ap_start(AXIvideo2Mat_U0_ap_start);
    AXIvideo2Mat_U0->start_full_n(start_for_Block_Mat_exit2022_p_U0_full_n);
    AXIvideo2Mat_U0->ap_done(AXIvideo2Mat_U0_ap_done);
    AXIvideo2Mat_U0->ap_continue(AXIvideo2Mat_U0_ap_continue);
    AXIvideo2Mat_U0->ap_idle(AXIvideo2Mat_U0_ap_idle);
    AXIvideo2Mat_U0->ap_ready(AXIvideo2Mat_U0_ap_ready);
    AXIvideo2Mat_U0->start_out(AXIvideo2Mat_U0_start_out);
    AXIvideo2Mat_U0->start_write(AXIvideo2Mat_U0_start_write);
    AXIvideo2Mat_U0->S_AXIS_TDATA(S_AXIS_TDATA);
    AXIvideo2Mat_U0->S_AXIS_TVALID(S_AXIS_TVALID);
    AXIvideo2Mat_U0->S_AXIS_TREADY(AXIvideo2Mat_U0_S_AXIS_TREADY);
    AXIvideo2Mat_U0->S_AXIS_TKEEP(S_AXIS_TKEEP);
    AXIvideo2Mat_U0->S_AXIS_TSTRB(S_AXIS_TSTRB);
    AXIvideo2Mat_U0->S_AXIS_TUSER(S_AXIS_TUSER);
    AXIvideo2Mat_U0->S_AXIS_TLAST(S_AXIS_TLAST);
    AXIvideo2Mat_U0->S_AXIS_TID(S_AXIS_TID);
    AXIvideo2Mat_U0->S_AXIS_TDEST(S_AXIS_TDEST);
    AXIvideo2Mat_U0->img_rows_V_dout(mat0_rows_V_c_dout);
    AXIvideo2Mat_U0->img_rows_V_empty_n(mat0_rows_V_c_empty_n);
    AXIvideo2Mat_U0->img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read);
    AXIvideo2Mat_U0->img_cols_V_dout(mat0_cols_V_c_dout);
    AXIvideo2Mat_U0->img_cols_V_empty_n(mat0_cols_V_c_empty_n);
    AXIvideo2Mat_U0->img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read);
    AXIvideo2Mat_U0->img_data_stream_V_din(AXIvideo2Mat_U0_img_data_stream_V_din);
    AXIvideo2Mat_U0->img_data_stream_V_full_n(mat0_data_stream_0_s_full_n);
    AXIvideo2Mat_U0->img_data_stream_V_write(AXIvideo2Mat_U0_img_data_stream_V_write);
    AXIvideo2Mat_U0->img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    AXIvideo2Mat_U0->img_rows_V_out_full_n(mat0_rows_V_c41_full_n);
    AXIvideo2Mat_U0->img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    AXIvideo2Mat_U0->img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    AXIvideo2Mat_U0->img_cols_V_out_full_n(mat0_cols_V_c42_full_n);
    AXIvideo2Mat_U0->img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    Block_Mat_exit2022_p_U0 = new Block_Mat_exit2022_p("Block_Mat_exit2022_p_U0");
    Block_Mat_exit2022_p_U0->ap_clk(ap_clk);
    Block_Mat_exit2022_p_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit2022_p_U0->ap_start(Block_Mat_exit2022_p_U0_ap_start);
    Block_Mat_exit2022_p_U0->ap_done(Block_Mat_exit2022_p_U0_ap_done);
    Block_Mat_exit2022_p_U0->ap_continue(Block_Mat_exit2022_p_U0_ap_continue);
    Block_Mat_exit2022_p_U0->ap_idle(Block_Mat_exit2022_p_U0_ap_idle);
    Block_Mat_exit2022_p_U0->ap_ready(Block_Mat_exit2022_p_U0_ap_ready);
    Block_Mat_exit2022_p_U0->mat0_rows_V_dout(mat0_rows_V_c41_dout);
    Block_Mat_exit2022_p_U0->mat0_rows_V_empty_n(mat0_rows_V_c41_empty_n);
    Block_Mat_exit2022_p_U0->mat0_rows_V_read(Block_Mat_exit2022_p_U0_mat0_rows_V_read);
    Block_Mat_exit2022_p_U0->mat0_cols_V_dout(mat0_cols_V_c42_dout);
    Block_Mat_exit2022_p_U0->mat0_cols_V_empty_n(mat0_cols_V_c42_empty_n);
    Block_Mat_exit2022_p_U0->mat0_cols_V_read(Block_Mat_exit2022_p_U0_mat0_cols_V_read);
    Block_Mat_exit2022_p_U0->mat0_data_stream_0_V_dout(mat0_data_stream_0_s_dout);
    Block_Mat_exit2022_p_U0->mat0_data_stream_0_V_empty_n(mat0_data_stream_0_s_empty_n);
    Block_Mat_exit2022_p_U0->mat0_data_stream_0_V_read(Block_Mat_exit2022_p_U0_mat0_data_stream_0_V_read);
    Block_Mat_exit2022_p_U0->arr0_val_address0(Block_Mat_exit2022_p_U0_arr0_val_address0);
    Block_Mat_exit2022_p_U0->arr0_val_ce0(Block_Mat_exit2022_p_U0_arr0_val_ce0);
    Block_Mat_exit2022_p_U0->arr0_val_we0(Block_Mat_exit2022_p_U0_arr0_val_we0);
    Block_Mat_exit2022_p_U0->arr0_val_d0(Block_Mat_exit2022_p_U0_arr0_val_d0);
    Block_Mat_exit2022_p_U0->arr0_rows_out_din(Block_Mat_exit2022_p_U0_arr0_rows_out_din);
    Block_Mat_exit2022_p_U0->arr0_rows_out_full_n(arr0_rows_c_full_n);
    Block_Mat_exit2022_p_U0->arr0_rows_out_write(Block_Mat_exit2022_p_U0_arr0_rows_out_write);
    Block_Mat_exit2022_p_U0->arr0_cols_out_din(Block_Mat_exit2022_p_U0_arr0_cols_out_din);
    Block_Mat_exit2022_p_U0->arr0_cols_out_full_n(arr0_cols_c_full_n);
    Block_Mat_exit2022_p_U0->arr0_cols_out_write(Block_Mat_exit2022_p_U0_arr0_cols_out_write);
    Block_Mat_exit2022_p_U0->ap_return_0(Block_Mat_exit2022_p_U0_ap_return_0);
    Block_Mat_exit2022_p_U0->ap_return_1(Block_Mat_exit2022_p_U0_ap_return_1);
    Resize_U0 = new Resize("Resize_U0");
    Resize_U0->ap_clk(ap_clk);
    Resize_U0->ap_rst(ap_rst_n_inv);
    Resize_U0->ap_start(Resize_U0_ap_start);
    Resize_U0->start_full_n(start_for_Block_Mat_exit2027_p_U0_full_n);
    Resize_U0->ap_done(Resize_U0_ap_done);
    Resize_U0->ap_continue(Resize_U0_ap_continue);
    Resize_U0->ap_idle(Resize_U0_ap_idle);
    Resize_U0->ap_ready(Resize_U0_ap_ready);
    Resize_U0->start_out(Resize_U0_start_out);
    Resize_U0->start_write(Resize_U0_start_write);
    Resize_U0->src_val_address0(Resize_U0_src_val_address0);
    Resize_U0->src_val_ce0(Resize_U0_src_val_ce0);
    Resize_U0->src_val_q0(arr0_val_t_q0);
    Resize_U0->src_val_address1(Resize_U0_src_val_address1);
    Resize_U0->src_val_ce1(Resize_U0_src_val_ce1);
    Resize_U0->src_val_q1(arr0_val_t_q1);
    Resize_U0->src_rows_dout(arr0_rows_c_dout);
    Resize_U0->src_rows_empty_n(arr0_rows_c_empty_n);
    Resize_U0->src_rows_read(Resize_U0_src_rows_read);
    Resize_U0->src_cols_dout(arr0_cols_c_dout);
    Resize_U0->src_cols_empty_n(arr0_cols_c_empty_n);
    Resize_U0->src_cols_read(Resize_U0_src_cols_read);
    Resize_U0->dst_val_address0(Resize_U0_dst_val_address0);
    Resize_U0->dst_val_ce0(Resize_U0_dst_val_ce0);
    Resize_U0->dst_val_we0(Resize_U0_dst_val_we0);
    Resize_U0->dst_val_d0(Resize_U0_dst_val_d0);
    Resize_U0->scale(tmp_4_loc_channel_dout);
    Resize_U0->method(tmp_5_loc_channel_dout);
    Resize_U0->dst_rows_din(Resize_U0_dst_rows_din);
    Resize_U0->dst_rows_full_n(arr1_rows_c_full_n);
    Resize_U0->dst_rows_write(Resize_U0_dst_rows_write);
    Resize_U0->dst_cols_din(Resize_U0_dst_cols_din);
    Resize_U0->dst_cols_full_n(arr1_cols_c_full_n);
    Resize_U0->dst_cols_write(Resize_U0_dst_cols_write);
    Block_Mat_exit2027_p_U0 = new Block_Mat_exit2027_p("Block_Mat_exit2027_p_U0");
    Block_Mat_exit2027_p_U0->ap_clk(ap_clk);
    Block_Mat_exit2027_p_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit2027_p_U0->ap_start(Block_Mat_exit2027_p_U0_ap_start);
    Block_Mat_exit2027_p_U0->ap_done(Block_Mat_exit2027_p_U0_ap_done);
    Block_Mat_exit2027_p_U0->ap_continue(Block_Mat_exit2027_p_U0_ap_continue);
    Block_Mat_exit2027_p_U0->ap_idle(Block_Mat_exit2027_p_U0_ap_idle);
    Block_Mat_exit2027_p_U0->ap_ready(Block_Mat_exit2027_p_U0_ap_ready);
    Block_Mat_exit2027_p_U0->arr1_rows_dout(arr1_rows_c_dout);
    Block_Mat_exit2027_p_U0->arr1_rows_empty_n(arr1_rows_c_empty_n);
    Block_Mat_exit2027_p_U0->arr1_rows_read(Block_Mat_exit2027_p_U0_arr1_rows_read);
    Block_Mat_exit2027_p_U0->rows1(Block_Mat_exit2027_p_U0_rows1);
    Block_Mat_exit2027_p_U0->rows1_ap_vld(Block_Mat_exit2027_p_U0_rows1_ap_vld);
    Block_Mat_exit2027_p_U0->arr1_rows_out_din(Block_Mat_exit2027_p_U0_arr1_rows_out_din);
    Block_Mat_exit2027_p_U0->arr1_rows_out_full_n(arr1_rows_c43_full_n);
    Block_Mat_exit2027_p_U0->arr1_rows_out_write(Block_Mat_exit2027_p_U0_arr1_rows_out_write);
    Block_Mat_exit2027_p_U0->ap_return(Block_Mat_exit2027_p_U0_ap_return);
    Block_Mat_exit2030_p_U0 = new Block_Mat_exit2030_p("Block_Mat_exit2030_p_U0");
    Block_Mat_exit2030_p_U0->ap_clk(ap_clk);
    Block_Mat_exit2030_p_U0->ap_rst(ap_rst_n_inv);
    Block_Mat_exit2030_p_U0->ap_start(Block_Mat_exit2030_p_U0_ap_start);
    Block_Mat_exit2030_p_U0->ap_done(Block_Mat_exit2030_p_U0_ap_done);
    Block_Mat_exit2030_p_U0->ap_continue(Block_Mat_exit2030_p_U0_ap_continue);
    Block_Mat_exit2030_p_U0->ap_idle(Block_Mat_exit2030_p_U0_ap_idle);
    Block_Mat_exit2030_p_U0->ap_ready(Block_Mat_exit2030_p_U0_ap_ready);
    Block_Mat_exit2030_p_U0->arr1_cols_dout(arr1_cols_c_dout);
    Block_Mat_exit2030_p_U0->arr1_cols_empty_n(arr1_cols_c_empty_n);
    Block_Mat_exit2030_p_U0->arr1_cols_read(Block_Mat_exit2030_p_U0_arr1_cols_read);
    Block_Mat_exit2030_p_U0->cols1(Block_Mat_exit2030_p_U0_cols1);
    Block_Mat_exit2030_p_U0->cols1_ap_vld(Block_Mat_exit2030_p_U0_cols1_ap_vld);
    Block_Mat_exit2030_p_U0->p_read(val_assign_loc_chann_dout);
    Block_Mat_exit2030_p_U0->arr1_cols_out_din(Block_Mat_exit2030_p_U0_arr1_cols_out_din);
    Block_Mat_exit2030_p_U0->arr1_cols_out_full_n(arr1_cols_c44_full_n);
    Block_Mat_exit2030_p_U0->arr1_cols_out_write(Block_Mat_exit2030_p_U0_arr1_cols_out_write);
    Block_Mat_exit2030_p_U0->ap_return_0(Block_Mat_exit2030_p_U0_ap_return_0);
    Block_Mat_exit2030_p_U0->ap_return_1(Block_Mat_exit2030_p_U0_ap_return_1);
    Array2D2Mat_U0 = new Array2D2Mat("Array2D2Mat_U0");
    Array2D2Mat_U0->ap_clk(ap_clk);
    Array2D2Mat_U0->ap_rst(ap_rst_n_inv);
    Array2D2Mat_U0->ap_start(Array2D2Mat_U0_ap_start);
    Array2D2Mat_U0->start_full_n(start_for_Mat2AXIvideo_U0_full_n);
    Array2D2Mat_U0->ap_done(Array2D2Mat_U0_ap_done);
    Array2D2Mat_U0->ap_continue(Array2D2Mat_U0_ap_continue);
    Array2D2Mat_U0->ap_idle(Array2D2Mat_U0_ap_idle);
    Array2D2Mat_U0->ap_ready(Array2D2Mat_U0_ap_ready);
    Array2D2Mat_U0->start_out(Array2D2Mat_U0_start_out);
    Array2D2Mat_U0->start_write(Array2D2Mat_U0_start_write);
    Array2D2Mat_U0->arr_val_address0(Array2D2Mat_U0_arr_val_address0);
    Array2D2Mat_U0->arr_val_ce0(Array2D2Mat_U0_arr_val_ce0);
    Array2D2Mat_U0->arr_val_q0(arr1_val_t_q0);
    Array2D2Mat_U0->arr_rows_dout(arr1_rows_c43_dout);
    Array2D2Mat_U0->arr_rows_empty_n(arr1_rows_c43_empty_n);
    Array2D2Mat_U0->arr_rows_read(Array2D2Mat_U0_arr_rows_read);
    Array2D2Mat_U0->arr_cols_dout(arr1_cols_c44_dout);
    Array2D2Mat_U0->arr_cols_empty_n(arr1_cols_c44_empty_n);
    Array2D2Mat_U0->arr_cols_read(Array2D2Mat_U0_arr_cols_read);
    Array2D2Mat_U0->param_val_0_V_read(param1_val_0_V_dout);
    Array2D2Mat_U0->param_val_1_V_read(param1_val_1_V_dout);
    Array2D2Mat_U0->mat_data_stream_V_din(Array2D2Mat_U0_mat_data_stream_V_din);
    Array2D2Mat_U0->mat_data_stream_V_full_n(mat1_data_stream_0_s_full_n);
    Array2D2Mat_U0->mat_data_stream_V_write(Array2D2Mat_U0_mat_data_stream_V_write);
    Array2D2Mat_U0->mat_rows_V_din(Array2D2Mat_U0_mat_rows_V_din);
    Array2D2Mat_U0->mat_rows_V_full_n(mat1_rows_V_c_full_n);
    Array2D2Mat_U0->mat_rows_V_write(Array2D2Mat_U0_mat_rows_V_write);
    Array2D2Mat_U0->mat_cols_V_din(Array2D2Mat_U0_mat_cols_V_din);
    Array2D2Mat_U0->mat_cols_V_full_n(mat1_cols_V_c_full_n);
    Array2D2Mat_U0->mat_cols_V_write(Array2D2Mat_U0_mat_cols_V_write);
    Mat2AXIvideo_U0 = new Mat2AXIvideo("Mat2AXIvideo_U0");
    Mat2AXIvideo_U0->ap_clk(ap_clk);
    Mat2AXIvideo_U0->ap_rst(ap_rst_n_inv);
    Mat2AXIvideo_U0->ap_start(Mat2AXIvideo_U0_ap_start);
    Mat2AXIvideo_U0->ap_done(Mat2AXIvideo_U0_ap_done);
    Mat2AXIvideo_U0->ap_continue(Mat2AXIvideo_U0_ap_continue);
    Mat2AXIvideo_U0->ap_idle(Mat2AXIvideo_U0_ap_idle);
    Mat2AXIvideo_U0->ap_ready(Mat2AXIvideo_U0_ap_ready);
    Mat2AXIvideo_U0->img_rows_V_dout(mat1_rows_V_c_dout);
    Mat2AXIvideo_U0->img_rows_V_empty_n(mat1_rows_V_c_empty_n);
    Mat2AXIvideo_U0->img_rows_V_read(Mat2AXIvideo_U0_img_rows_V_read);
    Mat2AXIvideo_U0->img_cols_V_dout(mat1_cols_V_c_dout);
    Mat2AXIvideo_U0->img_cols_V_empty_n(mat1_cols_V_c_empty_n);
    Mat2AXIvideo_U0->img_cols_V_read(Mat2AXIvideo_U0_img_cols_V_read);
    Mat2AXIvideo_U0->img_data_stream_V_dout(mat1_data_stream_0_s_dout);
    Mat2AXIvideo_U0->img_data_stream_V_empty_n(mat1_data_stream_0_s_empty_n);
    Mat2AXIvideo_U0->img_data_stream_V_read(Mat2AXIvideo_U0_img_data_stream_V_read);
    Mat2AXIvideo_U0->M_AXIS_TDATA(Mat2AXIvideo_U0_M_AXIS_TDATA);
    Mat2AXIvideo_U0->M_AXIS_TVALID(Mat2AXIvideo_U0_M_AXIS_TVALID);
    Mat2AXIvideo_U0->M_AXIS_TREADY(M_AXIS_TREADY);
    Mat2AXIvideo_U0->M_AXIS_TKEEP(Mat2AXIvideo_U0_M_AXIS_TKEEP);
    Mat2AXIvideo_U0->M_AXIS_TSTRB(Mat2AXIvideo_U0_M_AXIS_TSTRB);
    Mat2AXIvideo_U0->M_AXIS_TUSER(Mat2AXIvideo_U0_M_AXIS_TUSER);
    Mat2AXIvideo_U0->M_AXIS_TLAST(Mat2AXIvideo_U0_M_AXIS_TLAST);
    Mat2AXIvideo_U0->M_AXIS_TID(Mat2AXIvideo_U0_M_AXIS_TID);
    Mat2AXIvideo_U0->M_AXIS_TDEST(Mat2AXIvideo_U0_M_AXIS_TDEST);
    mat0_rows_V_c_U = new fifo_w32_d2_A("mat0_rows_V_c_U");
    mat0_rows_V_c_U->clk(ap_clk);
    mat0_rows_V_c_U->reset(ap_rst_n_inv);
    mat0_rows_V_c_U->if_read_ce(ap_var_for_const3);
    mat0_rows_V_c_U->if_write_ce(ap_var_for_const3);
    mat0_rows_V_c_U->if_din(Block_Mat_exit20_pro_U0_mat0_rows_V_out_din);
    mat0_rows_V_c_U->if_full_n(mat0_rows_V_c_full_n);
    mat0_rows_V_c_U->if_write(Block_Mat_exit20_pro_U0_mat0_rows_V_out_write);
    mat0_rows_V_c_U->if_dout(mat0_rows_V_c_dout);
    mat0_rows_V_c_U->if_empty_n(mat0_rows_V_c_empty_n);
    mat0_rows_V_c_U->if_read(AXIvideo2Mat_U0_img_rows_V_read);
    mat0_cols_V_c_U = new fifo_w32_d2_A("mat0_cols_V_c_U");
    mat0_cols_V_c_U->clk(ap_clk);
    mat0_cols_V_c_U->reset(ap_rst_n_inv);
    mat0_cols_V_c_U->if_read_ce(ap_var_for_const3);
    mat0_cols_V_c_U->if_write_ce(ap_var_for_const3);
    mat0_cols_V_c_U->if_din(Block_Mat_exit20_pro_U0_mat0_cols_V_out_din);
    mat0_cols_V_c_U->if_full_n(mat0_cols_V_c_full_n);
    mat0_cols_V_c_U->if_write(Block_Mat_exit20_pro_U0_mat0_cols_V_out_write);
    mat0_cols_V_c_U->if_dout(mat0_cols_V_c_dout);
    mat0_cols_V_c_U->if_empty_n(mat0_cols_V_c_empty_n);
    mat0_cols_V_c_U->if_read(AXIvideo2Mat_U0_img_cols_V_read);
    mat0_data_stream_0_s_U = new fifo_w8_d2_A("mat0_data_stream_0_s_U");
    mat0_data_stream_0_s_U->clk(ap_clk);
    mat0_data_stream_0_s_U->reset(ap_rst_n_inv);
    mat0_data_stream_0_s_U->if_read_ce(ap_var_for_const3);
    mat0_data_stream_0_s_U->if_write_ce(ap_var_for_const3);
    mat0_data_stream_0_s_U->if_din(AXIvideo2Mat_U0_img_data_stream_V_din);
    mat0_data_stream_0_s_U->if_full_n(mat0_data_stream_0_s_full_n);
    mat0_data_stream_0_s_U->if_write(AXIvideo2Mat_U0_img_data_stream_V_write);
    mat0_data_stream_0_s_U->if_dout(mat0_data_stream_0_s_dout);
    mat0_data_stream_0_s_U->if_empty_n(mat0_data_stream_0_s_empty_n);
    mat0_data_stream_0_s_U->if_read(Block_Mat_exit2022_p_U0_mat0_data_stream_0_V_read);
    mat0_rows_V_c41_U = new fifo_w32_d2_A("mat0_rows_V_c41_U");
    mat0_rows_V_c41_U->clk(ap_clk);
    mat0_rows_V_c41_U->reset(ap_rst_n_inv);
    mat0_rows_V_c41_U->if_read_ce(ap_var_for_const3);
    mat0_rows_V_c41_U->if_write_ce(ap_var_for_const3);
    mat0_rows_V_c41_U->if_din(AXIvideo2Mat_U0_img_rows_V_out_din);
    mat0_rows_V_c41_U->if_full_n(mat0_rows_V_c41_full_n);
    mat0_rows_V_c41_U->if_write(AXIvideo2Mat_U0_img_rows_V_out_write);
    mat0_rows_V_c41_U->if_dout(mat0_rows_V_c41_dout);
    mat0_rows_V_c41_U->if_empty_n(mat0_rows_V_c41_empty_n);
    mat0_rows_V_c41_U->if_read(Block_Mat_exit2022_p_U0_mat0_rows_V_read);
    mat0_cols_V_c42_U = new fifo_w32_d2_A("mat0_cols_V_c42_U");
    mat0_cols_V_c42_U->clk(ap_clk);
    mat0_cols_V_c42_U->reset(ap_rst_n_inv);
    mat0_cols_V_c42_U->if_read_ce(ap_var_for_const3);
    mat0_cols_V_c42_U->if_write_ce(ap_var_for_const3);
    mat0_cols_V_c42_U->if_din(AXIvideo2Mat_U0_img_cols_V_out_din);
    mat0_cols_V_c42_U->if_full_n(mat0_cols_V_c42_full_n);
    mat0_cols_V_c42_U->if_write(AXIvideo2Mat_U0_img_cols_V_out_write);
    mat0_cols_V_c42_U->if_dout(mat0_cols_V_c42_dout);
    mat0_cols_V_c42_U->if_empty_n(mat0_cols_V_c42_empty_n);
    mat0_cols_V_c42_U->if_read(Block_Mat_exit2022_p_U0_mat0_cols_V_read);
    arr0_rows_c_U = new fifo_w32_d2_A("arr0_rows_c_U");
    arr0_rows_c_U->clk(ap_clk);
    arr0_rows_c_U->reset(ap_rst_n_inv);
    arr0_rows_c_U->if_read_ce(ap_var_for_const3);
    arr0_rows_c_U->if_write_ce(ap_var_for_const3);
    arr0_rows_c_U->if_din(Block_Mat_exit2022_p_U0_arr0_rows_out_din);
    arr0_rows_c_U->if_full_n(arr0_rows_c_full_n);
    arr0_rows_c_U->if_write(Block_Mat_exit2022_p_U0_arr0_rows_out_write);
    arr0_rows_c_U->if_dout(arr0_rows_c_dout);
    arr0_rows_c_U->if_empty_n(arr0_rows_c_empty_n);
    arr0_rows_c_U->if_read(Resize_U0_src_rows_read);
    arr0_cols_c_U = new fifo_w32_d2_A("arr0_cols_c_U");
    arr0_cols_c_U->clk(ap_clk);
    arr0_cols_c_U->reset(ap_rst_n_inv);
    arr0_cols_c_U->if_read_ce(ap_var_for_const3);
    arr0_cols_c_U->if_write_ce(ap_var_for_const3);
    arr0_cols_c_U->if_din(Block_Mat_exit2022_p_U0_arr0_cols_out_din);
    arr0_cols_c_U->if_full_n(arr0_cols_c_full_n);
    arr0_cols_c_U->if_write(Block_Mat_exit2022_p_U0_arr0_cols_out_write);
    arr0_cols_c_U->if_dout(arr0_cols_c_dout);
    arr0_cols_c_U->if_empty_n(arr0_cols_c_empty_n);
    arr0_cols_c_U->if_read(Resize_U0_src_cols_read);
    tmp_4_loc_channel_U = new fifo_w32_d2_A("tmp_4_loc_channel_U");
    tmp_4_loc_channel_U->clk(ap_clk);
    tmp_4_loc_channel_U->reset(ap_rst_n_inv);
    tmp_4_loc_channel_U->if_read_ce(ap_var_for_const3);
    tmp_4_loc_channel_U->if_write_ce(ap_var_for_const3);
    tmp_4_loc_channel_U->if_din(Block_Mat_exit2022_p_U0_ap_return_0);
    tmp_4_loc_channel_U->if_full_n(tmp_4_loc_channel_full_n);
    tmp_4_loc_channel_U->if_write(ap_channel_done_tmp_4_loc_channel);
    tmp_4_loc_channel_U->if_dout(tmp_4_loc_channel_dout);
    tmp_4_loc_channel_U->if_empty_n(tmp_4_loc_channel_empty_n);
    tmp_4_loc_channel_U->if_read(Resize_U0_ap_ready);
    tmp_5_loc_channel_U = new fifo_w2_d2_A("tmp_5_loc_channel_U");
    tmp_5_loc_channel_U->clk(ap_clk);
    tmp_5_loc_channel_U->reset(ap_rst_n_inv);
    tmp_5_loc_channel_U->if_read_ce(ap_var_for_const3);
    tmp_5_loc_channel_U->if_write_ce(ap_var_for_const3);
    tmp_5_loc_channel_U->if_din(Block_Mat_exit2022_p_U0_ap_return_1);
    tmp_5_loc_channel_U->if_full_n(tmp_5_loc_channel_full_n);
    tmp_5_loc_channel_U->if_write(ap_channel_done_tmp_5_loc_channel);
    tmp_5_loc_channel_U->if_dout(tmp_5_loc_channel_dout);
    tmp_5_loc_channel_U->if_empty_n(tmp_5_loc_channel_empty_n);
    tmp_5_loc_channel_U->if_read(Resize_U0_ap_ready);
    arr1_rows_c_U = new fifo_w32_d2_A("arr1_rows_c_U");
    arr1_rows_c_U->clk(ap_clk);
    arr1_rows_c_U->reset(ap_rst_n_inv);
    arr1_rows_c_U->if_read_ce(ap_var_for_const3);
    arr1_rows_c_U->if_write_ce(ap_var_for_const3);
    arr1_rows_c_U->if_din(Resize_U0_dst_rows_din);
    arr1_rows_c_U->if_full_n(arr1_rows_c_full_n);
    arr1_rows_c_U->if_write(Resize_U0_dst_rows_write);
    arr1_rows_c_U->if_dout(arr1_rows_c_dout);
    arr1_rows_c_U->if_empty_n(arr1_rows_c_empty_n);
    arr1_rows_c_U->if_read(Block_Mat_exit2027_p_U0_arr1_rows_read);
    arr1_cols_c_U = new fifo_w32_d3_A("arr1_cols_c_U");
    arr1_cols_c_U->clk(ap_clk);
    arr1_cols_c_U->reset(ap_rst_n_inv);
    arr1_cols_c_U->if_read_ce(ap_var_for_const3);
    arr1_cols_c_U->if_write_ce(ap_var_for_const3);
    arr1_cols_c_U->if_din(Resize_U0_dst_cols_din);
    arr1_cols_c_U->if_full_n(arr1_cols_c_full_n);
    arr1_cols_c_U->if_write(Resize_U0_dst_cols_write);
    arr1_cols_c_U->if_dout(arr1_cols_c_dout);
    arr1_cols_c_U->if_empty_n(arr1_cols_c_empty_n);
    arr1_cols_c_U->if_read(Block_Mat_exit2030_p_U0_arr1_cols_read);
    arr1_rows_c43_U = new fifo_w32_d3_A("arr1_rows_c43_U");
    arr1_rows_c43_U->clk(ap_clk);
    arr1_rows_c43_U->reset(ap_rst_n_inv);
    arr1_rows_c43_U->if_read_ce(ap_var_for_const3);
    arr1_rows_c43_U->if_write_ce(ap_var_for_const3);
    arr1_rows_c43_U->if_din(Block_Mat_exit2027_p_U0_arr1_rows_out_din);
    arr1_rows_c43_U->if_full_n(arr1_rows_c43_full_n);
    arr1_rows_c43_U->if_write(Block_Mat_exit2027_p_U0_arr1_rows_out_write);
    arr1_rows_c43_U->if_dout(arr1_rows_c43_dout);
    arr1_rows_c43_U->if_empty_n(arr1_rows_c43_empty_n);
    arr1_rows_c43_U->if_read(Array2D2Mat_U0_arr_rows_read);
    val_assign_loc_chann_U = new fifo_w32_d2_A("val_assign_loc_chann_U");
    val_assign_loc_chann_U->clk(ap_clk);
    val_assign_loc_chann_U->reset(ap_rst_n_inv);
    val_assign_loc_chann_U->if_read_ce(ap_var_for_const3);
    val_assign_loc_chann_U->if_write_ce(ap_var_for_const3);
    val_assign_loc_chann_U->if_din(Block_Mat_exit2027_p_U0_ap_return);
    val_assign_loc_chann_U->if_full_n(val_assign_loc_chann_full_n);
    val_assign_loc_chann_U->if_write(ap_channel_done_val_assign_loc_chann);
    val_assign_loc_chann_U->if_dout(val_assign_loc_chann_dout);
    val_assign_loc_chann_U->if_empty_n(val_assign_loc_chann_empty_n);
    val_assign_loc_chann_U->if_read(Block_Mat_exit2030_p_U0_ap_ready);
    arr1_cols_c44_U = new fifo_w32_d2_A("arr1_cols_c44_U");
    arr1_cols_c44_U->clk(ap_clk);
    arr1_cols_c44_U->reset(ap_rst_n_inv);
    arr1_cols_c44_U->if_read_ce(ap_var_for_const3);
    arr1_cols_c44_U->if_write_ce(ap_var_for_const3);
    arr1_cols_c44_U->if_din(Block_Mat_exit2030_p_U0_arr1_cols_out_din);
    arr1_cols_c44_U->if_full_n(arr1_cols_c44_full_n);
    arr1_cols_c44_U->if_write(Block_Mat_exit2030_p_U0_arr1_cols_out_write);
    arr1_cols_c44_U->if_dout(arr1_cols_c44_dout);
    arr1_cols_c44_U->if_empty_n(arr1_cols_c44_empty_n);
    arr1_cols_c44_U->if_read(Array2D2Mat_U0_arr_cols_read);
    param1_val_0_V_U = new fifo_w32_d2_A("param1_val_0_V_U");
    param1_val_0_V_U->clk(ap_clk);
    param1_val_0_V_U->reset(ap_rst_n_inv);
    param1_val_0_V_U->if_read_ce(ap_var_for_const3);
    param1_val_0_V_U->if_write_ce(ap_var_for_const3);
    param1_val_0_V_U->if_din(Block_Mat_exit2030_p_U0_ap_return_0);
    param1_val_0_V_U->if_full_n(param1_val_0_V_full_n);
    param1_val_0_V_U->if_write(ap_channel_done_param1_val_0_V);
    param1_val_0_V_U->if_dout(param1_val_0_V_dout);
    param1_val_0_V_U->if_empty_n(param1_val_0_V_empty_n);
    param1_val_0_V_U->if_read(Array2D2Mat_U0_ap_ready);
    param1_val_1_V_U = new fifo_w32_d2_A("param1_val_1_V_U");
    param1_val_1_V_U->clk(ap_clk);
    param1_val_1_V_U->reset(ap_rst_n_inv);
    param1_val_1_V_U->if_read_ce(ap_var_for_const3);
    param1_val_1_V_U->if_write_ce(ap_var_for_const3);
    param1_val_1_V_U->if_din(Block_Mat_exit2030_p_U0_ap_return_1);
    param1_val_1_V_U->if_full_n(param1_val_1_V_full_n);
    param1_val_1_V_U->if_write(ap_channel_done_param1_val_1_V);
    param1_val_1_V_U->if_dout(param1_val_1_V_dout);
    param1_val_1_V_U->if_empty_n(param1_val_1_V_empty_n);
    param1_val_1_V_U->if_read(Array2D2Mat_U0_ap_ready);
    mat1_data_stream_0_s_U = new fifo_w8_d2_A("mat1_data_stream_0_s_U");
    mat1_data_stream_0_s_U->clk(ap_clk);
    mat1_data_stream_0_s_U->reset(ap_rst_n_inv);
    mat1_data_stream_0_s_U->if_read_ce(ap_var_for_const3);
    mat1_data_stream_0_s_U->if_write_ce(ap_var_for_const3);
    mat1_data_stream_0_s_U->if_din(Array2D2Mat_U0_mat_data_stream_V_din);
    mat1_data_stream_0_s_U->if_full_n(mat1_data_stream_0_s_full_n);
    mat1_data_stream_0_s_U->if_write(Array2D2Mat_U0_mat_data_stream_V_write);
    mat1_data_stream_0_s_U->if_dout(mat1_data_stream_0_s_dout);
    mat1_data_stream_0_s_U->if_empty_n(mat1_data_stream_0_s_empty_n);
    mat1_data_stream_0_s_U->if_read(Mat2AXIvideo_U0_img_data_stream_V_read);
    mat1_rows_V_c_U = new fifo_w32_d2_A("mat1_rows_V_c_U");
    mat1_rows_V_c_U->clk(ap_clk);
    mat1_rows_V_c_U->reset(ap_rst_n_inv);
    mat1_rows_V_c_U->if_read_ce(ap_var_for_const3);
    mat1_rows_V_c_U->if_write_ce(ap_var_for_const3);
    mat1_rows_V_c_U->if_din(Array2D2Mat_U0_mat_rows_V_din);
    mat1_rows_V_c_U->if_full_n(mat1_rows_V_c_full_n);
    mat1_rows_V_c_U->if_write(Array2D2Mat_U0_mat_rows_V_write);
    mat1_rows_V_c_U->if_dout(mat1_rows_V_c_dout);
    mat1_rows_V_c_U->if_empty_n(mat1_rows_V_c_empty_n);
    mat1_rows_V_c_U->if_read(Mat2AXIvideo_U0_img_rows_V_read);
    mat1_cols_V_c_U = new fifo_w32_d2_A("mat1_cols_V_c_U");
    mat1_cols_V_c_U->clk(ap_clk);
    mat1_cols_V_c_U->reset(ap_rst_n_inv);
    mat1_cols_V_c_U->if_read_ce(ap_var_for_const3);
    mat1_cols_V_c_U->if_write_ce(ap_var_for_const3);
    mat1_cols_V_c_U->if_din(Array2D2Mat_U0_mat_cols_V_din);
    mat1_cols_V_c_U->if_full_n(mat1_cols_V_c_full_n);
    mat1_cols_V_c_U->if_write(Array2D2Mat_U0_mat_cols_V_write);
    mat1_cols_V_c_U->if_dout(mat1_cols_V_c_dout);
    mat1_cols_V_c_U->if_empty_n(mat1_cols_V_c_empty_n);
    mat1_cols_V_c_U->if_read(Mat2AXIvideo_U0_img_cols_V_read);
    start_for_Block_Mhbi_U = new start_for_Block_Mhbi("start_for_Block_Mhbi_U");
    start_for_Block_Mhbi_U->clk(ap_clk);
    start_for_Block_Mhbi_U->reset(ap_rst_n_inv);
    start_for_Block_Mhbi_U->if_read_ce(ap_var_for_const3);
    start_for_Block_Mhbi_U->if_write_ce(ap_var_for_const3);
    start_for_Block_Mhbi_U->if_din(start_for_Block_Mat_exit2022_p_U0_din);
    start_for_Block_Mhbi_U->if_full_n(start_for_Block_Mat_exit2022_p_U0_full_n);
    start_for_Block_Mhbi_U->if_write(AXIvideo2Mat_U0_start_write);
    start_for_Block_Mhbi_U->if_dout(start_for_Block_Mat_exit2022_p_U0_dout);
    start_for_Block_Mhbi_U->if_empty_n(start_for_Block_Mat_exit2022_p_U0_empty_n);
    start_for_Block_Mhbi_U->if_read(Block_Mat_exit2022_p_U0_ap_ready);
    start_for_Block_Mibs_U = new start_for_Block_Mibs("start_for_Block_Mibs_U");
    start_for_Block_Mibs_U->clk(ap_clk);
    start_for_Block_Mibs_U->reset(ap_rst_n_inv);
    start_for_Block_Mibs_U->if_read_ce(ap_var_for_const3);
    start_for_Block_Mibs_U->if_write_ce(ap_var_for_const3);
    start_for_Block_Mibs_U->if_din(start_for_Block_Mat_exit2027_p_U0_din);
    start_for_Block_Mibs_U->if_full_n(start_for_Block_Mat_exit2027_p_U0_full_n);
    start_for_Block_Mibs_U->if_write(Resize_U0_start_write);
    start_for_Block_Mibs_U->if_dout(start_for_Block_Mat_exit2027_p_U0_dout);
    start_for_Block_Mibs_U->if_empty_n(start_for_Block_Mat_exit2027_p_U0_empty_n);
    start_for_Block_Mibs_U->if_read(Block_Mat_exit2027_p_U0_ap_ready);
    start_for_Mat2AXIjbC_U = new start_for_Mat2AXIjbC("start_for_Mat2AXIjbC_U");
    start_for_Mat2AXIjbC_U->clk(ap_clk);
    start_for_Mat2AXIjbC_U->reset(ap_rst_n_inv);
    start_for_Mat2AXIjbC_U->if_read_ce(ap_var_for_const3);
    start_for_Mat2AXIjbC_U->if_write_ce(ap_var_for_const3);
    start_for_Mat2AXIjbC_U->if_din(start_for_Mat2AXIvideo_U0_din);
    start_for_Mat2AXIjbC_U->if_full_n(start_for_Mat2AXIvideo_U0_full_n);
    start_for_Mat2AXIjbC_U->if_write(Array2D2Mat_U0_start_write);
    start_for_Mat2AXIjbC_U->if_dout(start_for_Mat2AXIvideo_U0_dout);
    start_for_Mat2AXIjbC_U->if_empty_n(start_for_Mat2AXIvideo_U0_empty_n);
    start_for_Mat2AXIjbC_U->if_read(Mat2AXIvideo_U0_ap_ready);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_continue);

    SC_METHOD(thread_AXIvideo2Mat_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_Array2D2Mat_U0_ap_continue);

    SC_METHOD(thread_Array2D2Mat_U0_ap_start);
    sensitive << ( arr1_val_t_empty_n );
    sensitive << ( param1_val_0_V_empty_n );
    sensitive << ( param1_val_1_V_empty_n );

    SC_METHOD(thread_Block_Mat_exit2022_p_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_tmp_5_loc_channel );
    sensitive << ( ap_sync_channel_write_tmp_4_loc_channel );
    sensitive << ( ap_sync_channel_write_arr0_val );

    SC_METHOD(thread_Block_Mat_exit2022_p_U0_ap_start);
    sensitive << ( start_for_Block_Mat_exit2022_p_U0_empty_n );

    SC_METHOD(thread_Block_Mat_exit2022_p_U0_arr0_val_full_n);
    sensitive << ( arr0_val_i_full_n );

    SC_METHOD(thread_Block_Mat_exit2022_p_U0_start_full_n);

    SC_METHOD(thread_Block_Mat_exit2022_p_U0_start_write);

    SC_METHOD(thread_Block_Mat_exit2027_p_U0_ap_continue);
    sensitive << ( ap_sync_channel_write_val_assign_loc_chann );
    sensitive << ( ap_sync_continue );

    SC_METHOD(thread_Block_Mat_exit2027_p_U0_ap_start);
    sensitive << ( start_for_Block_Mat_exit2027_p_U0_empty_n );

    SC_METHOD(thread_Block_Mat_exit2027_p_U0_start_full_n);

    SC_METHOD(thread_Block_Mat_exit2027_p_U0_start_write);

    SC_METHOD(thread_Block_Mat_exit2030_p_U0_ap_continue);
    sensitive << ( ap_sync_continue );
    sensitive << ( ap_sync_channel_write_param1_val_1_V );
    sensitive << ( ap_sync_channel_write_param1_val_0_V );

    SC_METHOD(thread_Block_Mat_exit2030_p_U0_ap_start);
    sensitive << ( val_assign_loc_chann_empty_n );

    SC_METHOD(thread_Block_Mat_exit2030_p_U0_start_full_n);

    SC_METHOD(thread_Block_Mat_exit2030_p_U0_start_write);

    SC_METHOD(thread_Block_Mat_exit20_pro_U0_ap_continue);

    SC_METHOD(thread_Block_Mat_exit20_pro_U0_ap_start);
    sensitive << ( ap_start );
    sensitive << ( ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready );

    SC_METHOD(thread_Block_Mat_exit20_pro_U0_start_full_n);

    SC_METHOD(thread_Block_Mat_exit20_pro_U0_start_write);

    SC_METHOD(thread_M_AXIS_TDATA);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TDATA );

    SC_METHOD(thread_M_AXIS_TDEST);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TDEST );

    SC_METHOD(thread_M_AXIS_TID);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TID );

    SC_METHOD(thread_M_AXIS_TKEEP);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TKEEP );

    SC_METHOD(thread_M_AXIS_TLAST);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TLAST );

    SC_METHOD(thread_M_AXIS_TSTRB);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TSTRB );

    SC_METHOD(thread_M_AXIS_TUSER);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TUSER );

    SC_METHOD(thread_M_AXIS_TVALID);
    sensitive << ( Mat2AXIvideo_U0_M_AXIS_TVALID );

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_continue);
    sensitive << ( ap_sync_done );

    SC_METHOD(thread_Mat2AXIvideo_U0_ap_start);
    sensitive << ( start_for_Mat2AXIvideo_U0_empty_n );

    SC_METHOD(thread_Mat2AXIvideo_U0_start_full_n);

    SC_METHOD(thread_Mat2AXIvideo_U0_start_write);

    SC_METHOD(thread_Resize_U0_ap_continue);
    sensitive << ( arr1_val_i_full_n );

    SC_METHOD(thread_Resize_U0_ap_start);
    sensitive << ( arr0_val_t_empty_n );
    sensitive << ( tmp_4_loc_channel_empty_n );
    sensitive << ( tmp_5_loc_channel_empty_n );

    SC_METHOD(thread_Resize_U0_dst_val_full_n);
    sensitive << ( arr1_val_i_full_n );

    SC_METHOD(thread_S_AXIS_TREADY);
    sensitive << ( AXIvideo2Mat_U0_S_AXIS_TREADY );

    SC_METHOD(thread_ap_channel_done_arr0_val);
    sensitive << ( Block_Mat_exit2022_p_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_arr0_val );

    SC_METHOD(thread_ap_channel_done_arr1_val);
    sensitive << ( Resize_U0_ap_done );

    SC_METHOD(thread_ap_channel_done_param1_val_0_V);
    sensitive << ( Block_Mat_exit2030_p_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_param1_val_0_V );

    SC_METHOD(thread_ap_channel_done_param1_val_1_V);
    sensitive << ( Block_Mat_exit2030_p_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_param1_val_1_V );

    SC_METHOD(thread_ap_channel_done_tmp_4_loc_channel);
    sensitive << ( Block_Mat_exit2022_p_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_4_loc_channel );

    SC_METHOD(thread_ap_channel_done_tmp_5_loc_channel);
    sensitive << ( Block_Mat_exit2022_p_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_tmp_5_loc_channel );

    SC_METHOD(thread_ap_channel_done_val_assign_loc_chann);
    sensitive << ( Block_Mat_exit2027_p_U0_ap_done );
    sensitive << ( ap_sync_reg_channel_write_val_assign_loc_chann );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sync_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Block_Mat_exit20_pro_U0_ap_idle );
    sensitive << ( AXIvideo2Mat_U0_ap_idle );
    sensitive << ( Block_Mat_exit2022_p_U0_ap_idle );
    sensitive << ( Resize_U0_ap_idle );
    sensitive << ( Block_Mat_exit2027_p_U0_ap_idle );
    sensitive << ( Block_Mat_exit2030_p_U0_ap_idle );
    sensitive << ( Array2D2Mat_U0_ap_idle );
    sensitive << ( Mat2AXIvideo_U0_ap_idle );
    sensitive << ( arr0_val_t_empty_n );
    sensitive << ( arr1_val_t_empty_n );
    sensitive << ( tmp_4_loc_channel_empty_n );
    sensitive << ( tmp_5_loc_channel_empty_n );
    sensitive << ( val_assign_loc_chann_empty_n );
    sensitive << ( param1_val_0_V_empty_n );
    sensitive << ( param1_val_1_V_empty_n );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sync_ready );

    SC_METHOD(thread_ap_rst_n_inv);
    sensitive << ( ap_rst_n );

    SC_METHOD(thread_ap_sync_AXIvideo2Mat_U0_ap_ready);
    sensitive << ( AXIvideo2Mat_U0_ap_ready );
    sensitive << ( ap_sync_reg_AXIvideo2Mat_U0_ap_ready );

    SC_METHOD(thread_ap_sync_Block_Mat_exit20_pro_U0_ap_ready);
    sensitive << ( Block_Mat_exit20_pro_U0_ap_ready );
    sensitive << ( ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready );

    SC_METHOD(thread_ap_sync_channel_write_arr0_val);
    sensitive << ( ap_channel_done_arr0_val );
    sensitive << ( Block_Mat_exit2022_p_U0_arr0_val_full_n );
    sensitive << ( ap_sync_reg_channel_write_arr0_val );

    SC_METHOD(thread_ap_sync_channel_write_param1_val_0_V);
    sensitive << ( ap_channel_done_param1_val_0_V );
    sensitive << ( param1_val_0_V_full_n );
    sensitive << ( ap_sync_reg_channel_write_param1_val_0_V );

    SC_METHOD(thread_ap_sync_channel_write_param1_val_1_V);
    sensitive << ( ap_channel_done_param1_val_1_V );
    sensitive << ( param1_val_1_V_full_n );
    sensitive << ( ap_sync_reg_channel_write_param1_val_1_V );

    SC_METHOD(thread_ap_sync_channel_write_tmp_4_loc_channel);
    sensitive << ( ap_channel_done_tmp_4_loc_channel );
    sensitive << ( tmp_4_loc_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_4_loc_channel );

    SC_METHOD(thread_ap_sync_channel_write_tmp_5_loc_channel);
    sensitive << ( ap_channel_done_tmp_5_loc_channel );
    sensitive << ( tmp_5_loc_channel_full_n );
    sensitive << ( ap_sync_reg_channel_write_tmp_5_loc_channel );

    SC_METHOD(thread_ap_sync_channel_write_val_assign_loc_chann);
    sensitive << ( ap_channel_done_val_assign_loc_chann );
    sensitive << ( val_assign_loc_chann_full_n );
    sensitive << ( ap_sync_reg_channel_write_val_assign_loc_chann );

    SC_METHOD(thread_ap_sync_continue);
    sensitive << ( ap_sync_done );

    SC_METHOD(thread_ap_sync_done);
    sensitive << ( Block_Mat_exit2027_p_U0_ap_done );
    sensitive << ( Block_Mat_exit2030_p_U0_ap_done );
    sensitive << ( Mat2AXIvideo_U0_ap_done );

    SC_METHOD(thread_ap_sync_ready);
    sensitive << ( ap_sync_AXIvideo2Mat_U0_ap_ready );
    sensitive << ( ap_sync_Block_Mat_exit20_pro_U0_ap_ready );

    SC_METHOD(thread_arr0_val_t_d1);

    SC_METHOD(thread_arr0_val_t_we1);

    SC_METHOD(thread_cols1);
    sensitive << ( Block_Mat_exit2030_p_U0_cols1 );

    SC_METHOD(thread_rows1);
    sensitive << ( Block_Mat_exit2027_p_U0_rows1 );

    SC_METHOD(thread_start_for_Block_Mat_exit2022_p_U0_din);

    SC_METHOD(thread_start_for_Block_Mat_exit2027_p_U0_din);

    SC_METHOD(thread_start_for_Mat2AXIvideo_U0_din);

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const3);

    SC_THREAD(thread_ap_var_for_const2);

    SC_THREAD(thread_ap_var_for_const1);

    SC_THREAD(thread_ap_var_for_const0);

    ap_sync_reg_channel_write_tmp_5_loc_channel = SC_LOGIC_0;
    ap_sync_reg_channel_write_tmp_4_loc_channel = SC_LOGIC_0;
    ap_sync_reg_channel_write_arr0_val = SC_LOGIC_0;
    ap_sync_reg_channel_write_val_assign_loc_chann = SC_LOGIC_0;
    ap_sync_reg_channel_write_param1_val_1_V = SC_LOGIC_0;
    ap_sync_reg_channel_write_param1_val_0_V = SC_LOGIC_0;
    ap_sync_reg_AXIvideo2Mat_U0_ap_ready = SC_LOGIC_0;
    AXIvideo2Mat_U0_ap_ready_count = "00";
    ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready = SC_LOGIC_0;
    Block_Mat_exit20_pro_U0_ap_ready_count = "00";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "imgproc_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst_n, "(port)ap_rst_n");
    sc_trace(mVcdFile, S_AXIS_TDATA, "(port)S_AXIS_TDATA");
    sc_trace(mVcdFile, S_AXIS_TKEEP, "(port)S_AXIS_TKEEP");
    sc_trace(mVcdFile, S_AXIS_TSTRB, "(port)S_AXIS_TSTRB");
    sc_trace(mVcdFile, S_AXIS_TUSER, "(port)S_AXIS_TUSER");
    sc_trace(mVcdFile, S_AXIS_TLAST, "(port)S_AXIS_TLAST");
    sc_trace(mVcdFile, S_AXIS_TID, "(port)S_AXIS_TID");
    sc_trace(mVcdFile, S_AXIS_TDEST, "(port)S_AXIS_TDEST");
    sc_trace(mVcdFile, M_AXIS_TDATA, "(port)M_AXIS_TDATA");
    sc_trace(mVcdFile, M_AXIS_TKEEP, "(port)M_AXIS_TKEEP");
    sc_trace(mVcdFile, M_AXIS_TSTRB, "(port)M_AXIS_TSTRB");
    sc_trace(mVcdFile, M_AXIS_TUSER, "(port)M_AXIS_TUSER");
    sc_trace(mVcdFile, M_AXIS_TLAST, "(port)M_AXIS_TLAST");
    sc_trace(mVcdFile, M_AXIS_TID, "(port)M_AXIS_TID");
    sc_trace(mVcdFile, M_AXIS_TDEST, "(port)M_AXIS_TDEST");
    sc_trace(mVcdFile, rows0, "(port)rows0");
    sc_trace(mVcdFile, cols0, "(port)cols0");
    sc_trace(mVcdFile, rows1, "(port)rows1");
    sc_trace(mVcdFile, cols1, "(port)cols1");
    sc_trace(mVcdFile, S_AXIS_TVALID, "(port)S_AXIS_TVALID");
    sc_trace(mVcdFile, S_AXIS_TREADY, "(port)S_AXIS_TREADY");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, M_AXIS_TVALID, "(port)M_AXIS_TVALID");
    sc_trace(mVcdFile, M_AXIS_TREADY, "(port)M_AXIS_TREADY");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_rst_n_inv, "ap_rst_n_inv");
    sc_trace(mVcdFile, arr0_val_i_q0, "arr0_val_i_q0");
    sc_trace(mVcdFile, arr0_val_i_q1, "arr0_val_i_q1");
    sc_trace(mVcdFile, arr0_val_t_q0, "arr0_val_t_q0");
    sc_trace(mVcdFile, arr0_val_t_q1, "arr0_val_t_q1");
    sc_trace(mVcdFile, arr1_val_i_q0, "arr1_val_i_q0");
    sc_trace(mVcdFile, arr1_val_t_q0, "arr1_val_t_q0");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_ap_start, "Block_Mat_exit20_pro_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_ap_done, "Block_Mat_exit20_pro_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_ap_continue, "Block_Mat_exit20_pro_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_ap_idle, "Block_Mat_exit20_pro_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_ap_ready, "Block_Mat_exit20_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_mat0_rows_V_out_din, "Block_Mat_exit20_pro_U0_mat0_rows_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_mat0_rows_V_out_write, "Block_Mat_exit20_pro_U0_mat0_rows_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_mat0_cols_V_out_din, "Block_Mat_exit20_pro_U0_mat0_cols_V_out_din");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_mat0_cols_V_out_write, "Block_Mat_exit20_pro_U0_mat0_cols_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_start, "AXIvideo2Mat_U0_ap_start");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_done, "AXIvideo2Mat_U0_ap_done");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_continue, "AXIvideo2Mat_U0_ap_continue");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_idle, "AXIvideo2Mat_U0_ap_idle");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready, "AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_out, "AXIvideo2Mat_U0_start_out");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_start_write, "AXIvideo2Mat_U0_start_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_S_AXIS_TREADY, "AXIvideo2Mat_U0_S_AXIS_TREADY");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_read, "AXIvideo2Mat_U0_img_rows_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_read, "AXIvideo2Mat_U0_img_cols_V_read");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_V_din, "AXIvideo2Mat_U0_img_data_stream_V_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_data_stream_V_write, "AXIvideo2Mat_U0_img_data_stream_V_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_din, "AXIvideo2Mat_U0_img_rows_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_rows_V_out_write, "AXIvideo2Mat_U0_img_rows_V_out_write");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_din, "AXIvideo2Mat_U0_img_cols_V_out_din");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_img_cols_V_out_write, "AXIvideo2Mat_U0_img_cols_V_out_write");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_ap_start, "Block_Mat_exit2022_p_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_ap_done, "Block_Mat_exit2022_p_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_ap_continue, "Block_Mat_exit2022_p_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_ap_idle, "Block_Mat_exit2022_p_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_ap_ready, "Block_Mat_exit2022_p_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_mat0_rows_V_read, "Block_Mat_exit2022_p_U0_mat0_rows_V_read");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_mat0_cols_V_read, "Block_Mat_exit2022_p_U0_mat0_cols_V_read");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_mat0_data_stream_0_V_read, "Block_Mat_exit2022_p_U0_mat0_data_stream_0_V_read");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_val_address0, "Block_Mat_exit2022_p_U0_arr0_val_address0");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_val_ce0, "Block_Mat_exit2022_p_U0_arr0_val_ce0");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_val_we0, "Block_Mat_exit2022_p_U0_arr0_val_we0");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_val_d0, "Block_Mat_exit2022_p_U0_arr0_val_d0");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_rows_out_din, "Block_Mat_exit2022_p_U0_arr0_rows_out_din");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_rows_out_write, "Block_Mat_exit2022_p_U0_arr0_rows_out_write");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_cols_out_din, "Block_Mat_exit2022_p_U0_arr0_cols_out_din");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_cols_out_write, "Block_Mat_exit2022_p_U0_arr0_cols_out_write");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_ap_return_0, "Block_Mat_exit2022_p_U0_ap_return_0");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_ap_return_1, "Block_Mat_exit2022_p_U0_ap_return_1");
    sc_trace(mVcdFile, ap_channel_done_tmp_5_loc_channel, "ap_channel_done_tmp_5_loc_channel");
    sc_trace(mVcdFile, tmp_5_loc_channel_full_n, "tmp_5_loc_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_5_loc_channel, "ap_sync_reg_channel_write_tmp_5_loc_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_5_loc_channel, "ap_sync_channel_write_tmp_5_loc_channel");
    sc_trace(mVcdFile, ap_channel_done_tmp_4_loc_channel, "ap_channel_done_tmp_4_loc_channel");
    sc_trace(mVcdFile, tmp_4_loc_channel_full_n, "tmp_4_loc_channel_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_tmp_4_loc_channel, "ap_sync_reg_channel_write_tmp_4_loc_channel");
    sc_trace(mVcdFile, ap_sync_channel_write_tmp_4_loc_channel, "ap_sync_channel_write_tmp_4_loc_channel");
    sc_trace(mVcdFile, ap_channel_done_arr0_val, "ap_channel_done_arr0_val");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_arr0_val_full_n, "Block_Mat_exit2022_p_U0_arr0_val_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_arr0_val, "ap_sync_reg_channel_write_arr0_val");
    sc_trace(mVcdFile, ap_sync_channel_write_arr0_val, "ap_sync_channel_write_arr0_val");
    sc_trace(mVcdFile, Resize_U0_ap_start, "Resize_U0_ap_start");
    sc_trace(mVcdFile, Resize_U0_ap_done, "Resize_U0_ap_done");
    sc_trace(mVcdFile, Resize_U0_ap_continue, "Resize_U0_ap_continue");
    sc_trace(mVcdFile, Resize_U0_ap_idle, "Resize_U0_ap_idle");
    sc_trace(mVcdFile, Resize_U0_ap_ready, "Resize_U0_ap_ready");
    sc_trace(mVcdFile, Resize_U0_start_out, "Resize_U0_start_out");
    sc_trace(mVcdFile, Resize_U0_start_write, "Resize_U0_start_write");
    sc_trace(mVcdFile, Resize_U0_src_val_address0, "Resize_U0_src_val_address0");
    sc_trace(mVcdFile, Resize_U0_src_val_ce0, "Resize_U0_src_val_ce0");
    sc_trace(mVcdFile, Resize_U0_src_val_address1, "Resize_U0_src_val_address1");
    sc_trace(mVcdFile, Resize_U0_src_val_ce1, "Resize_U0_src_val_ce1");
    sc_trace(mVcdFile, Resize_U0_src_rows_read, "Resize_U0_src_rows_read");
    sc_trace(mVcdFile, Resize_U0_src_cols_read, "Resize_U0_src_cols_read");
    sc_trace(mVcdFile, Resize_U0_dst_val_address0, "Resize_U0_dst_val_address0");
    sc_trace(mVcdFile, Resize_U0_dst_val_ce0, "Resize_U0_dst_val_ce0");
    sc_trace(mVcdFile, Resize_U0_dst_val_we0, "Resize_U0_dst_val_we0");
    sc_trace(mVcdFile, Resize_U0_dst_val_d0, "Resize_U0_dst_val_d0");
    sc_trace(mVcdFile, Resize_U0_dst_rows_din, "Resize_U0_dst_rows_din");
    sc_trace(mVcdFile, Resize_U0_dst_rows_write, "Resize_U0_dst_rows_write");
    sc_trace(mVcdFile, Resize_U0_dst_cols_din, "Resize_U0_dst_cols_din");
    sc_trace(mVcdFile, Resize_U0_dst_cols_write, "Resize_U0_dst_cols_write");
    sc_trace(mVcdFile, ap_channel_done_arr1_val, "ap_channel_done_arr1_val");
    sc_trace(mVcdFile, Resize_U0_dst_val_full_n, "Resize_U0_dst_val_full_n");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_ap_start, "Block_Mat_exit2027_p_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_ap_done, "Block_Mat_exit2027_p_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_ap_continue, "Block_Mat_exit2027_p_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_ap_idle, "Block_Mat_exit2027_p_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_ap_ready, "Block_Mat_exit2027_p_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_arr1_rows_read, "Block_Mat_exit2027_p_U0_arr1_rows_read");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_rows1, "Block_Mat_exit2027_p_U0_rows1");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_rows1_ap_vld, "Block_Mat_exit2027_p_U0_rows1_ap_vld");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_arr1_rows_out_din, "Block_Mat_exit2027_p_U0_arr1_rows_out_din");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_arr1_rows_out_write, "Block_Mat_exit2027_p_U0_arr1_rows_out_write");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_ap_return, "Block_Mat_exit2027_p_U0_ap_return");
    sc_trace(mVcdFile, ap_channel_done_val_assign_loc_chann, "ap_channel_done_val_assign_loc_chann");
    sc_trace(mVcdFile, val_assign_loc_chann_full_n, "val_assign_loc_chann_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_val_assign_loc_chann, "ap_sync_reg_channel_write_val_assign_loc_chann");
    sc_trace(mVcdFile, ap_sync_channel_write_val_assign_loc_chann, "ap_sync_channel_write_val_assign_loc_chann");
    sc_trace(mVcdFile, ap_sync_continue, "ap_sync_continue");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_ap_start, "Block_Mat_exit2030_p_U0_ap_start");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_ap_done, "Block_Mat_exit2030_p_U0_ap_done");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_ap_continue, "Block_Mat_exit2030_p_U0_ap_continue");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_ap_idle, "Block_Mat_exit2030_p_U0_ap_idle");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_ap_ready, "Block_Mat_exit2030_p_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_arr1_cols_read, "Block_Mat_exit2030_p_U0_arr1_cols_read");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_cols1, "Block_Mat_exit2030_p_U0_cols1");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_cols1_ap_vld, "Block_Mat_exit2030_p_U0_cols1_ap_vld");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_arr1_cols_out_din, "Block_Mat_exit2030_p_U0_arr1_cols_out_din");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_arr1_cols_out_write, "Block_Mat_exit2030_p_U0_arr1_cols_out_write");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_ap_return_0, "Block_Mat_exit2030_p_U0_ap_return_0");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_ap_return_1, "Block_Mat_exit2030_p_U0_ap_return_1");
    sc_trace(mVcdFile, ap_channel_done_param1_val_1_V, "ap_channel_done_param1_val_1_V");
    sc_trace(mVcdFile, param1_val_1_V_full_n, "param1_val_1_V_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_param1_val_1_V, "ap_sync_reg_channel_write_param1_val_1_V");
    sc_trace(mVcdFile, ap_sync_channel_write_param1_val_1_V, "ap_sync_channel_write_param1_val_1_V");
    sc_trace(mVcdFile, ap_channel_done_param1_val_0_V, "ap_channel_done_param1_val_0_V");
    sc_trace(mVcdFile, param1_val_0_V_full_n, "param1_val_0_V_full_n");
    sc_trace(mVcdFile, ap_sync_reg_channel_write_param1_val_0_V, "ap_sync_reg_channel_write_param1_val_0_V");
    sc_trace(mVcdFile, ap_sync_channel_write_param1_val_0_V, "ap_sync_channel_write_param1_val_0_V");
    sc_trace(mVcdFile, Array2D2Mat_U0_ap_start, "Array2D2Mat_U0_ap_start");
    sc_trace(mVcdFile, Array2D2Mat_U0_ap_done, "Array2D2Mat_U0_ap_done");
    sc_trace(mVcdFile, Array2D2Mat_U0_ap_continue, "Array2D2Mat_U0_ap_continue");
    sc_trace(mVcdFile, Array2D2Mat_U0_ap_idle, "Array2D2Mat_U0_ap_idle");
    sc_trace(mVcdFile, Array2D2Mat_U0_ap_ready, "Array2D2Mat_U0_ap_ready");
    sc_trace(mVcdFile, Array2D2Mat_U0_start_out, "Array2D2Mat_U0_start_out");
    sc_trace(mVcdFile, Array2D2Mat_U0_start_write, "Array2D2Mat_U0_start_write");
    sc_trace(mVcdFile, Array2D2Mat_U0_arr_val_address0, "Array2D2Mat_U0_arr_val_address0");
    sc_trace(mVcdFile, Array2D2Mat_U0_arr_val_ce0, "Array2D2Mat_U0_arr_val_ce0");
    sc_trace(mVcdFile, Array2D2Mat_U0_arr_rows_read, "Array2D2Mat_U0_arr_rows_read");
    sc_trace(mVcdFile, Array2D2Mat_U0_arr_cols_read, "Array2D2Mat_U0_arr_cols_read");
    sc_trace(mVcdFile, Array2D2Mat_U0_mat_data_stream_V_din, "Array2D2Mat_U0_mat_data_stream_V_din");
    sc_trace(mVcdFile, Array2D2Mat_U0_mat_data_stream_V_write, "Array2D2Mat_U0_mat_data_stream_V_write");
    sc_trace(mVcdFile, Array2D2Mat_U0_mat_rows_V_din, "Array2D2Mat_U0_mat_rows_V_din");
    sc_trace(mVcdFile, Array2D2Mat_U0_mat_rows_V_write, "Array2D2Mat_U0_mat_rows_V_write");
    sc_trace(mVcdFile, Array2D2Mat_U0_mat_cols_V_din, "Array2D2Mat_U0_mat_cols_V_din");
    sc_trace(mVcdFile, Array2D2Mat_U0_mat_cols_V_write, "Array2D2Mat_U0_mat_cols_V_write");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_start, "Mat2AXIvideo_U0_ap_start");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_done, "Mat2AXIvideo_U0_ap_done");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_continue, "Mat2AXIvideo_U0_ap_continue");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_idle, "Mat2AXIvideo_U0_ap_idle");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_ap_ready, "Mat2AXIvideo_U0_ap_ready");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_rows_V_read, "Mat2AXIvideo_U0_img_rows_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_cols_V_read, "Mat2AXIvideo_U0_img_cols_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_img_data_stream_V_read, "Mat2AXIvideo_U0_img_data_stream_V_read");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TDATA, "Mat2AXIvideo_U0_M_AXIS_TDATA");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TVALID, "Mat2AXIvideo_U0_M_AXIS_TVALID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TKEEP, "Mat2AXIvideo_U0_M_AXIS_TKEEP");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TSTRB, "Mat2AXIvideo_U0_M_AXIS_TSTRB");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TUSER, "Mat2AXIvideo_U0_M_AXIS_TUSER");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TLAST, "Mat2AXIvideo_U0_M_AXIS_TLAST");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TID, "Mat2AXIvideo_U0_M_AXIS_TID");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_M_AXIS_TDEST, "Mat2AXIvideo_U0_M_AXIS_TDEST");
    sc_trace(mVcdFile, arr0_val_i_full_n, "arr0_val_i_full_n");
    sc_trace(mVcdFile, arr0_val_t_empty_n, "arr0_val_t_empty_n");
    sc_trace(mVcdFile, arr0_val_t_d1, "arr0_val_t_d1");
    sc_trace(mVcdFile, arr0_val_t_we1, "arr0_val_t_we1");
    sc_trace(mVcdFile, arr1_val_i_full_n, "arr1_val_i_full_n");
    sc_trace(mVcdFile, arr1_val_t_empty_n, "arr1_val_t_empty_n");
    sc_trace(mVcdFile, mat0_rows_V_c_full_n, "mat0_rows_V_c_full_n");
    sc_trace(mVcdFile, mat0_rows_V_c_dout, "mat0_rows_V_c_dout");
    sc_trace(mVcdFile, mat0_rows_V_c_empty_n, "mat0_rows_V_c_empty_n");
    sc_trace(mVcdFile, mat0_cols_V_c_full_n, "mat0_cols_V_c_full_n");
    sc_trace(mVcdFile, mat0_cols_V_c_dout, "mat0_cols_V_c_dout");
    sc_trace(mVcdFile, mat0_cols_V_c_empty_n, "mat0_cols_V_c_empty_n");
    sc_trace(mVcdFile, mat0_data_stream_0_s_full_n, "mat0_data_stream_0_s_full_n");
    sc_trace(mVcdFile, mat0_data_stream_0_s_dout, "mat0_data_stream_0_s_dout");
    sc_trace(mVcdFile, mat0_data_stream_0_s_empty_n, "mat0_data_stream_0_s_empty_n");
    sc_trace(mVcdFile, mat0_rows_V_c41_full_n, "mat0_rows_V_c41_full_n");
    sc_trace(mVcdFile, mat0_rows_V_c41_dout, "mat0_rows_V_c41_dout");
    sc_trace(mVcdFile, mat0_rows_V_c41_empty_n, "mat0_rows_V_c41_empty_n");
    sc_trace(mVcdFile, mat0_cols_V_c42_full_n, "mat0_cols_V_c42_full_n");
    sc_trace(mVcdFile, mat0_cols_V_c42_dout, "mat0_cols_V_c42_dout");
    sc_trace(mVcdFile, mat0_cols_V_c42_empty_n, "mat0_cols_V_c42_empty_n");
    sc_trace(mVcdFile, arr0_rows_c_full_n, "arr0_rows_c_full_n");
    sc_trace(mVcdFile, arr0_rows_c_dout, "arr0_rows_c_dout");
    sc_trace(mVcdFile, arr0_rows_c_empty_n, "arr0_rows_c_empty_n");
    sc_trace(mVcdFile, arr0_cols_c_full_n, "arr0_cols_c_full_n");
    sc_trace(mVcdFile, arr0_cols_c_dout, "arr0_cols_c_dout");
    sc_trace(mVcdFile, arr0_cols_c_empty_n, "arr0_cols_c_empty_n");
    sc_trace(mVcdFile, tmp_4_loc_channel_dout, "tmp_4_loc_channel_dout");
    sc_trace(mVcdFile, tmp_4_loc_channel_empty_n, "tmp_4_loc_channel_empty_n");
    sc_trace(mVcdFile, tmp_5_loc_channel_dout, "tmp_5_loc_channel_dout");
    sc_trace(mVcdFile, tmp_5_loc_channel_empty_n, "tmp_5_loc_channel_empty_n");
    sc_trace(mVcdFile, arr1_rows_c_full_n, "arr1_rows_c_full_n");
    sc_trace(mVcdFile, arr1_rows_c_dout, "arr1_rows_c_dout");
    sc_trace(mVcdFile, arr1_rows_c_empty_n, "arr1_rows_c_empty_n");
    sc_trace(mVcdFile, arr1_cols_c_full_n, "arr1_cols_c_full_n");
    sc_trace(mVcdFile, arr1_cols_c_dout, "arr1_cols_c_dout");
    sc_trace(mVcdFile, arr1_cols_c_empty_n, "arr1_cols_c_empty_n");
    sc_trace(mVcdFile, arr1_rows_c43_full_n, "arr1_rows_c43_full_n");
    sc_trace(mVcdFile, arr1_rows_c43_dout, "arr1_rows_c43_dout");
    sc_trace(mVcdFile, arr1_rows_c43_empty_n, "arr1_rows_c43_empty_n");
    sc_trace(mVcdFile, val_assign_loc_chann_dout, "val_assign_loc_chann_dout");
    sc_trace(mVcdFile, val_assign_loc_chann_empty_n, "val_assign_loc_chann_empty_n");
    sc_trace(mVcdFile, arr1_cols_c44_full_n, "arr1_cols_c44_full_n");
    sc_trace(mVcdFile, arr1_cols_c44_dout, "arr1_cols_c44_dout");
    sc_trace(mVcdFile, arr1_cols_c44_empty_n, "arr1_cols_c44_empty_n");
    sc_trace(mVcdFile, param1_val_0_V_dout, "param1_val_0_V_dout");
    sc_trace(mVcdFile, param1_val_0_V_empty_n, "param1_val_0_V_empty_n");
    sc_trace(mVcdFile, param1_val_1_V_dout, "param1_val_1_V_dout");
    sc_trace(mVcdFile, param1_val_1_V_empty_n, "param1_val_1_V_empty_n");
    sc_trace(mVcdFile, mat1_data_stream_0_s_full_n, "mat1_data_stream_0_s_full_n");
    sc_trace(mVcdFile, mat1_data_stream_0_s_dout, "mat1_data_stream_0_s_dout");
    sc_trace(mVcdFile, mat1_data_stream_0_s_empty_n, "mat1_data_stream_0_s_empty_n");
    sc_trace(mVcdFile, mat1_rows_V_c_full_n, "mat1_rows_V_c_full_n");
    sc_trace(mVcdFile, mat1_rows_V_c_dout, "mat1_rows_V_c_dout");
    sc_trace(mVcdFile, mat1_rows_V_c_empty_n, "mat1_rows_V_c_empty_n");
    sc_trace(mVcdFile, mat1_cols_V_c_full_n, "mat1_cols_V_c_full_n");
    sc_trace(mVcdFile, mat1_cols_V_c_dout, "mat1_cols_V_c_dout");
    sc_trace(mVcdFile, mat1_cols_V_c_empty_n, "mat1_cols_V_c_empty_n");
    sc_trace(mVcdFile, ap_sync_done, "ap_sync_done");
    sc_trace(mVcdFile, ap_sync_ready, "ap_sync_ready");
    sc_trace(mVcdFile, ap_sync_reg_AXIvideo2Mat_U0_ap_ready, "ap_sync_reg_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_AXIvideo2Mat_U0_ap_ready, "ap_sync_AXIvideo2Mat_U0_ap_ready");
    sc_trace(mVcdFile, AXIvideo2Mat_U0_ap_ready_count, "AXIvideo2Mat_U0_ap_ready_count");
    sc_trace(mVcdFile, ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready, "ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready");
    sc_trace(mVcdFile, ap_sync_Block_Mat_exit20_pro_U0_ap_ready, "ap_sync_Block_Mat_exit20_pro_U0_ap_ready");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_ap_ready_count, "Block_Mat_exit20_pro_U0_ap_ready_count");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_start_full_n, "Block_Mat_exit20_pro_U0_start_full_n");
    sc_trace(mVcdFile, Block_Mat_exit20_pro_U0_start_write, "Block_Mat_exit20_pro_U0_start_write");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2022_p_U0_din, "start_for_Block_Mat_exit2022_p_U0_din");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2022_p_U0_full_n, "start_for_Block_Mat_exit2022_p_U0_full_n");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2022_p_U0_dout, "start_for_Block_Mat_exit2022_p_U0_dout");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2022_p_U0_empty_n, "start_for_Block_Mat_exit2022_p_U0_empty_n");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_start_full_n, "Block_Mat_exit2022_p_U0_start_full_n");
    sc_trace(mVcdFile, Block_Mat_exit2022_p_U0_start_write, "Block_Mat_exit2022_p_U0_start_write");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2027_p_U0_din, "start_for_Block_Mat_exit2027_p_U0_din");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2027_p_U0_full_n, "start_for_Block_Mat_exit2027_p_U0_full_n");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2027_p_U0_dout, "start_for_Block_Mat_exit2027_p_U0_dout");
    sc_trace(mVcdFile, start_for_Block_Mat_exit2027_p_U0_empty_n, "start_for_Block_Mat_exit2027_p_U0_empty_n");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_start_full_n, "Block_Mat_exit2027_p_U0_start_full_n");
    sc_trace(mVcdFile, Block_Mat_exit2027_p_U0_start_write, "Block_Mat_exit2027_p_U0_start_write");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_start_full_n, "Block_Mat_exit2030_p_U0_start_full_n");
    sc_trace(mVcdFile, Block_Mat_exit2030_p_U0_start_write, "Block_Mat_exit2030_p_U0_start_write");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_din, "start_for_Mat2AXIvideo_U0_din");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_full_n, "start_for_Mat2AXIvideo_U0_full_n");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_dout, "start_for_Mat2AXIvideo_U0_dout");
    sc_trace(mVcdFile, start_for_Mat2AXIvideo_U0_empty_n, "start_for_Mat2AXIvideo_U0_empty_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_full_n, "Mat2AXIvideo_U0_start_full_n");
    sc_trace(mVcdFile, Mat2AXIvideo_U0_start_write, "Mat2AXIvideo_U0_start_write");
#endif

    }
    mHdltvinHandle.open("imgproc.hdltvin.dat");
    mHdltvoutHandle.open("imgproc.hdltvout.dat");
}

imgproc::~imgproc() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete arr0_val_U;
    delete arr1_val_U;
    delete Block_Mat_exit20_pro_U0;
    delete AXIvideo2Mat_U0;
    delete Block_Mat_exit2022_p_U0;
    delete Resize_U0;
    delete Block_Mat_exit2027_p_U0;
    delete Block_Mat_exit2030_p_U0;
    delete Array2D2Mat_U0;
    delete Mat2AXIvideo_U0;
    delete mat0_rows_V_c_U;
    delete mat0_cols_V_c_U;
    delete mat0_data_stream_0_s_U;
    delete mat0_rows_V_c41_U;
    delete mat0_cols_V_c42_U;
    delete arr0_rows_c_U;
    delete arr0_cols_c_U;
    delete tmp_4_loc_channel_U;
    delete tmp_5_loc_channel_U;
    delete arr1_rows_c_U;
    delete arr1_cols_c_U;
    delete arr1_rows_c43_U;
    delete val_assign_loc_chann_U;
    delete arr1_cols_c44_U;
    delete param1_val_0_V_U;
    delete param1_val_1_V_U;
    delete mat1_data_stream_0_s_U;
    delete mat1_rows_V_c_U;
    delete mat1_cols_V_c_U;
    delete start_for_Block_Mhbi_U;
    delete start_for_Block_Mibs_U;
    delete start_for_Mat2AXIjbC_U;
}

void imgproc::thread_ap_var_for_const3() {
    ap_var_for_const3 = ap_const_logic_1;
}

void imgproc::thread_ap_var_for_const2() {
    ap_var_for_const2 = ap_const_lv8_0;
}

void imgproc::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_logic_0;
}

void imgproc::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_lv16_0;
}

void imgproc::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(AXIvideo2Mat_U0_ap_ready.read(), ap_const_logic_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()))) {
        AXIvideo2Mat_U0_ap_ready_count = (!AXIvideo2Mat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2Mat_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, AXIvideo2Mat_U0_ap_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()))) {
        AXIvideo2Mat_U0_ap_ready_count = (!AXIvideo2Mat_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(AXIvideo2Mat_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_sync_ready.read()) && 
         esl_seteq<1,1,1>(Block_Mat_exit20_pro_U0_ap_ready.read(), ap_const_logic_0))) {
        Block_Mat_exit20_pro_U0_ap_ready_count = (!Block_Mat_exit20_pro_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit20_pro_U0_ap_ready_count.read()) - sc_biguint<2>(ap_const_lv2_1));
    } else if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_sync_ready.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, Block_Mat_exit20_pro_U0_ap_ready.read()))) {
        Block_Mat_exit20_pro_U0_ap_ready_count = (!Block_Mat_exit20_pro_U0_ap_ready_count.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(Block_Mat_exit20_pro_U0_ap_ready_count.read()) + sc_biguint<2>(ap_const_lv2_1));
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready = ap_sync_AXIvideo2Mat_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (ap_start.read() & 
             ap_sync_ready.read()))) {
            ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready = ap_const_logic_0;
        } else {
            ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready = ap_sync_Block_Mat_exit20_pro_U0_ap_ready.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_arr0_val = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit2022_p_U0_ap_done.read() & 
             Block_Mat_exit2022_p_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_arr0_val = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_arr0_val = ap_sync_channel_write_arr0_val.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_param1_val_0_V = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit2030_p_U0_ap_done.read() & 
             Block_Mat_exit2030_p_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_param1_val_0_V = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_param1_val_0_V = ap_sync_channel_write_param1_val_0_V.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_param1_val_1_V = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit2030_p_U0_ap_done.read() & 
             Block_Mat_exit2030_p_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_param1_val_1_V = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_param1_val_1_V = ap_sync_channel_write_param1_val_1_V.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_4_loc_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit2022_p_U0_ap_done.read() & 
             Block_Mat_exit2022_p_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_4_loc_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_4_loc_channel = ap_sync_channel_write_tmp_4_loc_channel.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_tmp_5_loc_channel = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit2022_p_U0_ap_done.read() & 
             Block_Mat_exit2022_p_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_tmp_5_loc_channel = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_tmp_5_loc_channel = ap_sync_channel_write_tmp_5_loc_channel.read();
        }
    }
    if ( ap_rst_n_inv.read() == ap_const_logic_1) {
        ap_sync_reg_channel_write_val_assign_loc_chann = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, (Block_Mat_exit2027_p_U0_ap_done.read() & 
             Block_Mat_exit2027_p_U0_ap_continue.read()))) {
            ap_sync_reg_channel_write_val_assign_loc_chann = ap_const_logic_0;
        } else {
            ap_sync_reg_channel_write_val_assign_loc_chann = ap_sync_channel_write_val_assign_loc_chann.read();
        }
    }
}

void imgproc::thread_AXIvideo2Mat_U0_ap_continue() {
    AXIvideo2Mat_U0_ap_continue = ap_const_logic_1;
}

void imgproc::thread_AXIvideo2Mat_U0_ap_start() {
    AXIvideo2Mat_U0_ap_start = (ap_start.read() & (ap_sync_reg_AXIvideo2Mat_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_Array2D2Mat_U0_ap_continue() {
    Array2D2Mat_U0_ap_continue = ap_const_logic_1;
}

void imgproc::thread_Array2D2Mat_U0_ap_start() {
    Array2D2Mat_U0_ap_start = (arr1_val_t_empty_n.read() & param1_val_0_V_empty_n.read() & param1_val_1_V_empty_n.read());
}

void imgproc::thread_Block_Mat_exit2022_p_U0_ap_continue() {
    Block_Mat_exit2022_p_U0_ap_continue = (ap_sync_channel_write_tmp_5_loc_channel.read() & ap_sync_channel_write_tmp_4_loc_channel.read() & ap_sync_channel_write_arr0_val.read());
}

void imgproc::thread_Block_Mat_exit2022_p_U0_ap_start() {
    Block_Mat_exit2022_p_U0_ap_start = start_for_Block_Mat_exit2022_p_U0_empty_n.read();
}

void imgproc::thread_Block_Mat_exit2022_p_U0_arr0_val_full_n() {
    Block_Mat_exit2022_p_U0_arr0_val_full_n = arr0_val_i_full_n.read();
}

void imgproc::thread_Block_Mat_exit2022_p_U0_start_full_n() {
    Block_Mat_exit2022_p_U0_start_full_n = ap_const_logic_1;
}

void imgproc::thread_Block_Mat_exit2022_p_U0_start_write() {
    Block_Mat_exit2022_p_U0_start_write = ap_const_logic_0;
}

void imgproc::thread_Block_Mat_exit2027_p_U0_ap_continue() {
    Block_Mat_exit2027_p_U0_ap_continue = (ap_sync_channel_write_val_assign_loc_chann.read() & ap_sync_continue.read());
}

void imgproc::thread_Block_Mat_exit2027_p_U0_ap_start() {
    Block_Mat_exit2027_p_U0_ap_start = start_for_Block_Mat_exit2027_p_U0_empty_n.read();
}

void imgproc::thread_Block_Mat_exit2027_p_U0_start_full_n() {
    Block_Mat_exit2027_p_U0_start_full_n = ap_const_logic_1;
}

void imgproc::thread_Block_Mat_exit2027_p_U0_start_write() {
    Block_Mat_exit2027_p_U0_start_write = ap_const_logic_0;
}

void imgproc::thread_Block_Mat_exit2030_p_U0_ap_continue() {
    Block_Mat_exit2030_p_U0_ap_continue = (ap_sync_continue.read() & ap_sync_channel_write_param1_val_1_V.read() & ap_sync_channel_write_param1_val_0_V.read());
}

void imgproc::thread_Block_Mat_exit2030_p_U0_ap_start() {
    Block_Mat_exit2030_p_U0_ap_start = val_assign_loc_chann_empty_n.read();
}

void imgproc::thread_Block_Mat_exit2030_p_U0_start_full_n() {
    Block_Mat_exit2030_p_U0_start_full_n = ap_const_logic_1;
}

void imgproc::thread_Block_Mat_exit2030_p_U0_start_write() {
    Block_Mat_exit2030_p_U0_start_write = ap_const_logic_0;
}

void imgproc::thread_Block_Mat_exit20_pro_U0_ap_continue() {
    Block_Mat_exit20_pro_U0_ap_continue = ap_const_logic_1;
}

void imgproc::thread_Block_Mat_exit20_pro_U0_ap_start() {
    Block_Mat_exit20_pro_U0_ap_start = (ap_start.read() & (ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_Block_Mat_exit20_pro_U0_start_full_n() {
    Block_Mat_exit20_pro_U0_start_full_n = ap_const_logic_1;
}

void imgproc::thread_Block_Mat_exit20_pro_U0_start_write() {
    Block_Mat_exit20_pro_U0_start_write = ap_const_logic_0;
}

void imgproc::thread_M_AXIS_TDATA() {
    M_AXIS_TDATA = Mat2AXIvideo_U0_M_AXIS_TDATA.read();
}

void imgproc::thread_M_AXIS_TDEST() {
    M_AXIS_TDEST = Mat2AXIvideo_U0_M_AXIS_TDEST.read();
}

void imgproc::thread_M_AXIS_TID() {
    M_AXIS_TID = Mat2AXIvideo_U0_M_AXIS_TID.read();
}

void imgproc::thread_M_AXIS_TKEEP() {
    M_AXIS_TKEEP = Mat2AXIvideo_U0_M_AXIS_TKEEP.read();
}

void imgproc::thread_M_AXIS_TLAST() {
    M_AXIS_TLAST = Mat2AXIvideo_U0_M_AXIS_TLAST.read();
}

void imgproc::thread_M_AXIS_TSTRB() {
    M_AXIS_TSTRB = Mat2AXIvideo_U0_M_AXIS_TSTRB.read();
}

void imgproc::thread_M_AXIS_TUSER() {
    M_AXIS_TUSER = Mat2AXIvideo_U0_M_AXIS_TUSER.read();
}

void imgproc::thread_M_AXIS_TVALID() {
    M_AXIS_TVALID = Mat2AXIvideo_U0_M_AXIS_TVALID.read();
}

void imgproc::thread_Mat2AXIvideo_U0_ap_continue() {
    Mat2AXIvideo_U0_ap_continue = ap_sync_done.read();
}

void imgproc::thread_Mat2AXIvideo_U0_ap_start() {
    Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n.read();
}

void imgproc::thread_Mat2AXIvideo_U0_start_full_n() {
    Mat2AXIvideo_U0_start_full_n = ap_const_logic_1;
}

void imgproc::thread_Mat2AXIvideo_U0_start_write() {
    Mat2AXIvideo_U0_start_write = ap_const_logic_0;
}

void imgproc::thread_Resize_U0_ap_continue() {
    Resize_U0_ap_continue = arr1_val_i_full_n.read();
}

void imgproc::thread_Resize_U0_ap_start() {
    Resize_U0_ap_start = (arr0_val_t_empty_n.read() & tmp_4_loc_channel_empty_n.read() & tmp_5_loc_channel_empty_n.read());
}

void imgproc::thread_Resize_U0_dst_val_full_n() {
    Resize_U0_dst_val_full_n = arr1_val_i_full_n.read();
}

void imgproc::thread_S_AXIS_TREADY() {
    S_AXIS_TREADY = AXIvideo2Mat_U0_S_AXIS_TREADY.read();
}

void imgproc::thread_ap_channel_done_arr0_val() {
    ap_channel_done_arr0_val = (Block_Mat_exit2022_p_U0_ap_done.read() & (ap_sync_reg_channel_write_arr0_val.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_ap_channel_done_arr1_val() {
    ap_channel_done_arr1_val = Resize_U0_ap_done.read();
}

void imgproc::thread_ap_channel_done_param1_val_0_V() {
    ap_channel_done_param1_val_0_V = (Block_Mat_exit2030_p_U0_ap_done.read() & (ap_sync_reg_channel_write_param1_val_0_V.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_ap_channel_done_param1_val_1_V() {
    ap_channel_done_param1_val_1_V = (Block_Mat_exit2030_p_U0_ap_done.read() & (ap_sync_reg_channel_write_param1_val_1_V.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_ap_channel_done_tmp_4_loc_channel() {
    ap_channel_done_tmp_4_loc_channel = (Block_Mat_exit2022_p_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_4_loc_channel.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_ap_channel_done_tmp_5_loc_channel() {
    ap_channel_done_tmp_5_loc_channel = (Block_Mat_exit2022_p_U0_ap_done.read() & (ap_sync_reg_channel_write_tmp_5_loc_channel.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_ap_channel_done_val_assign_loc_chann() {
    ap_channel_done_val_assign_loc_chann = (Block_Mat_exit2027_p_U0_ap_done.read() & (ap_sync_reg_channel_write_val_assign_loc_chann.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_ap_done() {
    ap_done = ap_sync_done.read();
}

void imgproc::thread_ap_idle() {
    ap_idle = (Block_Mat_exit20_pro_U0_ap_idle.read() & AXIvideo2Mat_U0_ap_idle.read() & Block_Mat_exit2022_p_U0_ap_idle.read() & Resize_U0_ap_idle.read() & Block_Mat_exit2027_p_U0_ap_idle.read() & Block_Mat_exit2030_p_U0_ap_idle.read() & Array2D2Mat_U0_ap_idle.read() & Mat2AXIvideo_U0_ap_idle.read() & (arr0_val_t_empty_n.read() ^ 
  ap_const_logic_1) & (tmp_4_loc_channel_empty_n.read() ^ 
  ap_const_logic_1) & (tmp_5_loc_channel_empty_n.read() ^ 
  ap_const_logic_1) & (arr1_val_t_empty_n.read() ^ 
  ap_const_logic_1) & (val_assign_loc_chann_empty_n.read() ^ 
  ap_const_logic_1) & (param1_val_0_V_empty_n.read() ^ 
  ap_const_logic_1) & (param1_val_1_V_empty_n.read() ^ 
  ap_const_logic_1));
}

void imgproc::thread_ap_ready() {
    ap_ready = ap_sync_ready.read();
}

void imgproc::thread_ap_rst_n_inv() {
    ap_rst_n_inv =  (sc_logic) (~ap_rst_n.read());
}

void imgproc::thread_ap_sync_AXIvideo2Mat_U0_ap_ready() {
    ap_sync_AXIvideo2Mat_U0_ap_ready = (AXIvideo2Mat_U0_ap_ready.read() | ap_sync_reg_AXIvideo2Mat_U0_ap_ready.read());
}

void imgproc::thread_ap_sync_Block_Mat_exit20_pro_U0_ap_ready() {
    ap_sync_Block_Mat_exit20_pro_U0_ap_ready = (Block_Mat_exit20_pro_U0_ap_ready.read() | ap_sync_reg_Block_Mat_exit20_pro_U0_ap_ready.read());
}

void imgproc::thread_ap_sync_channel_write_arr0_val() {
    ap_sync_channel_write_arr0_val = ((ap_channel_done_arr0_val.read() & 
  Block_Mat_exit2022_p_U0_arr0_val_full_n.read()) | ap_sync_reg_channel_write_arr0_val.read());
}

void imgproc::thread_ap_sync_channel_write_param1_val_0_V() {
    ap_sync_channel_write_param1_val_0_V = ((ap_channel_done_param1_val_0_V.read() & 
  param1_val_0_V_full_n.read()) | ap_sync_reg_channel_write_param1_val_0_V.read());
}

void imgproc::thread_ap_sync_channel_write_param1_val_1_V() {
    ap_sync_channel_write_param1_val_1_V = ((ap_channel_done_param1_val_1_V.read() & 
  param1_val_1_V_full_n.read()) | ap_sync_reg_channel_write_param1_val_1_V.read());
}

void imgproc::thread_ap_sync_channel_write_tmp_4_loc_channel() {
    ap_sync_channel_write_tmp_4_loc_channel = ((ap_channel_done_tmp_4_loc_channel.read() & 
  tmp_4_loc_channel_full_n.read()) | ap_sync_reg_channel_write_tmp_4_loc_channel.read());
}

void imgproc::thread_ap_sync_channel_write_tmp_5_loc_channel() {
    ap_sync_channel_write_tmp_5_loc_channel = ((ap_channel_done_tmp_5_loc_channel.read() & 
  tmp_5_loc_channel_full_n.read()) | ap_sync_reg_channel_write_tmp_5_loc_channel.read());
}

void imgproc::thread_ap_sync_channel_write_val_assign_loc_chann() {
    ap_sync_channel_write_val_assign_loc_chann = ((ap_channel_done_val_assign_loc_chann.read() & 
  val_assign_loc_chann_full_n.read()) | ap_sync_reg_channel_write_val_assign_loc_chann.read());
}

void imgproc::thread_ap_sync_continue() {
    ap_sync_continue = ap_sync_done.read();
}

void imgproc::thread_ap_sync_done() {
    ap_sync_done = (Block_Mat_exit2027_p_U0_ap_done.read() & Block_Mat_exit2030_p_U0_ap_done.read() & Mat2AXIvideo_U0_ap_done.read());
}

void imgproc::thread_ap_sync_ready() {
    ap_sync_ready = (ap_sync_AXIvideo2Mat_U0_ap_ready.read() & ap_sync_Block_Mat_exit20_pro_U0_ap_ready.read());
}

void imgproc::thread_arr0_val_t_d1() {
    arr0_val_t_d1 = ap_const_lv8_0;
}

void imgproc::thread_arr0_val_t_we1() {
    arr0_val_t_we1 = ap_const_logic_0;
}

void imgproc::thread_cols1() {
    cols1 = Block_Mat_exit2030_p_U0_cols1.read();
}

void imgproc::thread_rows1() {
    rows1 = Block_Mat_exit2027_p_U0_rows1.read();
}

void imgproc::thread_start_for_Block_Mat_exit2022_p_U0_din() {
    start_for_Block_Mat_exit2022_p_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void imgproc::thread_start_for_Block_Mat_exit2027_p_U0_din() {
    start_for_Block_Mat_exit2027_p_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void imgproc::thread_start_for_Mat2AXIvideo_U0_din() {
    start_for_Mat2AXIvideo_U0_din =  (sc_lv<1>) (ap_const_logic_1);
}

void imgproc::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst_n\" :  \"" << ap_rst_n.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TDATA\" :  \"" << S_AXIS_TDATA.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TKEEP\" :  \"" << S_AXIS_TKEEP.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TSTRB\" :  \"" << S_AXIS_TSTRB.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TUSER\" :  \"" << S_AXIS_TUSER.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TLAST\" :  \"" << S_AXIS_TLAST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TID\" :  \"" << S_AXIS_TID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TDEST\" :  \"" << S_AXIS_TDEST.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"M_AXIS_TDATA\" :  \"" << M_AXIS_TDATA.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"M_AXIS_TKEEP\" :  \"" << M_AXIS_TKEEP.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"M_AXIS_TSTRB\" :  \"" << M_AXIS_TSTRB.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"M_AXIS_TUSER\" :  \"" << M_AXIS_TUSER.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"M_AXIS_TLAST\" :  \"" << M_AXIS_TLAST.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"M_AXIS_TID\" :  \"" << M_AXIS_TID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"M_AXIS_TDEST\" :  \"" << M_AXIS_TDEST.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"rows0\" :  \"" << rows0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"cols0\" :  \"" << cols0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"rows1\" :  \"" << rows1.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"cols1\" :  \"" << cols1.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"S_AXIS_TVALID\" :  \"" << S_AXIS_TVALID.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"S_AXIS_TREADY\" :  \"" << S_AXIS_TREADY.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"M_AXIS_TVALID\" :  \"" << M_AXIS_TVALID.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"M_AXIS_TREADY\" :  \"" << M_AXIS_TREADY.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

